local AirportData = {
    -- Метаданные аэропорта
    Metadata = {
        ICAO = "KNFL",
        Name = "KNFL Airport",
        Elevation = 0,
        MagVar = 0,
        Region = "Nevada"
    },

    -- Путевые точки
    Waypoints = {
        ["TYWAN"] = { lat = 39.598275, lon = -118.814430556, type = "KNFL" },
        ["BAFHU"] = { lat = 40.026330556, lon = -118.760511111, type = "KNFL" },
        ["HOROD"] = { lat = 39.1201, lon = -118.432444444, type = "KNFL" },
        ["CUPIR"] = { lat = 39.507605556, lon = -118.759683333, type = "KNFL" },
        ["CALAI"] = { lat = 39.516625, lon = -118.182652778, type = "KNFL" },
        ["FEGAB"] = { lat = 39.462972222, lon = -118.738541667, type = "KNFL" },
        ["ZIPUG"] = { lat = 39.358827778, lon = -118.645183333, type = "KNFL" },
        ["MUFIT"] = { lat = 39.197577778, lon = -118.381477778, type = "KNFL" },
        ["MIRKE"] = { lat = 39.351205556, lon = -118.607786111, type = "KNFL" },
        ["PRIMI"] = { lat = 38.641725, lon = -118.543988889, type = "ENRT" },
        ["ZOPIS"] = { lat = 39.420358333, lon = -118.425530556, type = "KNFL" },
        ["CITAB"] = { lat = 39.384066667, lon = -118.656411111, type = "KNFL" },
        ["ELMMR"] = { lat = 39.274447222, lon = -118.494508333, type = "KNFL" },
        ["WONVO"] = { lat = 39.462261111, lon = -118.732363889, type = "KNFL" },
        ["HAKOG"] = { lat = 39.307358333, lon = -118.543025, type = "KNFL" },
        ["RHIDE"] = { lat = 39.087572222, lon = -118.220430556, type = "KNFL" },
        ["CAXUL"] = { lat = 39.465066667, lon = -118.454502778, type = "KNFL" },
        ["AZGER"] = { lat = 39.578752778, lon = -118.553038889, type = "KNFL" },
        ["LENCO"] = { lat = 39.592230556, lon = -118.540336111, type = "KNFL" },
        ["BIKZE"] = { lat = 39.581063889, lon = -118.844844444, type = "KNFL" },
        ["OCERI"] = { lat = 39.188697222, lon = -118.493388889, type = "KNFL" },
        ["NUWXO"] = { lat = 39.444122222, lon = -118.721447222, type = "KNFL" },
        ["YERIN"] = { lat = 38.979686111, lon = -118.961641667, type = "ENRT" },
        ["WINED"] = { lat = 39.326027778, lon = -118.615852778, type = "KNFL" },
        ["JENGU"] = { lat = 39.496411111, lon = -118.768597222, type = "KNFL" },
        ["FITNU"] = { lat = 39.280397222, lon = -118.785552778, type = "KNFL" },
        ["WATER"] = { lat = 39.616591667, lon = -118.723133333, type = "KNFL" },
        ["FENAT"] = { lat = 39.402677778, lon = -118.683983333, type = "KNFL" },
        ["JUMLA"] = { lat = 39.24355, lon = -118.542230556, type = "KNFL" },
        ["ARDLY"] = { lat = -77.884377778, lon = 166.629352778, type = "NZFX" },
        ["PILOW"] = { lat = 39.686533333, lon = -118.451283333, type = "KNFL" },
    },

    -- Данные ВПП
    Runways = {
        ["RW07"] = {
            heading = 70,
            length = 0,
            width = 0,
            threshold = { lat = 39.413108333333334, lon = -118.71586944444445 },
            end = { lat = 39.413108333333334, lon = -118.71586944444445 }
        },
        ["RW13L"] = {
            heading = 130,
            length = 0,
            width = 0,
            threshold = { lat = 39.430563888888884, lon = -118.70514166666666 },
            end = { lat = 39.430563888888884, lon = -118.70514166666666 }
        },
        ["RW13R"] = {
            heading = 130,
            length = 0,
            width = 0,
            threshold = { lat = 39.43558888888889, lon = -118.71396111111112 },
            end = { lat = 39.43558888888889, lon = -118.71396111111112 }
        },
        ["RW25"] = {
            heading = 250,
            length = 0,
            width = 0,
            threshold = { lat = 39.41383333333333, lon = -118.69110833333333 },
            end = { lat = 39.41383333333333, lon = -118.69110833333333 }
        },
        ["RW31L"] = {
            heading = 310,
            length = 0,
            width = 0,
            threshold = { lat = 39.40403333333333, lon = -118.6856638888889 },
            end = { lat = 39.40403333333333, lon = -118.6856638888889 }
        },
        ["RW31R"] = {
            heading = 310,
            length = 0,
            width = 0,
            threshold = { lat = 39.4056, lon = -118.68275555555556 },
            end = { lat = 39.4056, lon = -118.68275555555556 }
        },
    },

    -- Процедуры SID
    SID = {
        ["TYWAN1"] = {
            name = "TYWAN1",
            runway = "RW07",
            waypoints = {
                { name = "", type = "", altitude_min = 4500 },
                { name = "NFL", type = "D" },
                { name = "TYWAN", type = "P", altitude_max = 9900, speed = 250.0 },
                { name = "", type = "", altitude_min = 4500 },
                { name = "NFL", type = "D", speed = 250.0 },
                { name = "TYWAN", type = "P", altitude_max = 9900 },
                { name = "", type = "", altitude_min = 4340 },
                { name = "", type = "", speed = 250.0 },
                { name = "TYWAN", type = "P", altitude_max = 9900 },
                { name = "", type = "", altitude_min = 4340 },
                { name = "TYWAN", type = "P", altitude_max = 9900 },
                { name = "TYWAN", type = "P", altitude_max = 9900 },
                { name = "FMG", type = "D", altitude_max = 15000 },
                { name = "TYWAN", type = "P", altitude_max = 9900 },
                { name = "HZN", type = "D", altitude_max = 15000 },
                { name = "TYWAN", type = "P", altitude_max = 9900 },
                { name = "ARDLY", type = "P", altitude_max = 15000 },
                { name = "BAFHU", type = "P", altitude_max = 15000 },
                { name = "LLC", type = "D" },
            }
        },
        ["YERIN8"] = {
            name = "YERIN8",
            runway = "RW07",
            waypoints = {
                { name = "", type = "", altitude_min = 4340 },
                { name = "", type = "", speed = 250.0 },
                { name = "FITNU", type = "P", altitude_min = 9500 },
                { name = "YERIN", type = "E" },
                { name = "", type = "", altitude_min = 4340 },
                { name = "", type = "", speed = 250.0 },
                { name = "FITNU", type = "P", altitude_min = 9500 },
                { name = "YERIN", type = "E" },
                { name = "", type = "", altitude_min = 4340 },
                { name = "", type = "", speed = 250.0 },
                { name = "FITNU", type = "P", altitude_min = 9500 },
                { name = "YERIN", type = "E" },
                { name = "", type = "", altitude_min = 4500 },
                { name = "NFL", type = "D", speed = 250.0 },
                { name = "FITNU", type = "P", altitude_min = 9500 },
                { name = "YERIN", type = "E" },
            }
        },
    },

    -- Процедуры STAR
    STAR = {
    },

    -- Процедуры захода на посадку
    APPROACH = {
        ["R13R"] = {
            name = "R13R",
            type = "A",
            runway = "R13R",
            waypoints = {
                { name = "BIKZE", transition = "BIKZE", type = "K2", altitude_max = 9800 },
                { name = "BIKZE", transition = "BIKZE", type = "K2", altitude_min = 7100, speed = 230.0 },
                { name = "HZN", transition = "HZN", type = "K2", altitude_min = 7200 },
                { name = "BIKZE", transition = "HZN", type = "K2", altitude_min = 7100 },
                { name = "BIKZE", transition = "", type = "K2", altitude_min = 7100 },
                { name = "JENGU", transition = "", type = "K2", altitude_min = 5400 },
                { name = "FEGAB", transition = "", type = "K2", altitude_min = 4620 },
                { name = "RW13R", transition = "", type = "K2" },
                { name = "", transition = "", type = "", altitude_min = 4320 },
                { name = "HOROD", transition = "", type = "K2", altitude_min = 9800 },
                { name = "HOROD", transition = "", type = "K2", altitude_max = 12800, speed = 230.0 },
            }
        },
        ["R31L"] = {
            name = "R31L",
            type = "A",
            runway = "R31L",
            waypoints = {
                { name = "MVA", transition = "MVA", type = "K2", altitude_min = 10300 },
                { name = "HOROD", transition = "MVA", type = "K2", altitude_min = 10300 },
                { name = "OCERI", transition = "MVA", type = "K2", altitude_min = 8100 },
                { name = "JUMLA", transition = "MVA", type = "K2", altitude_min = 7300 },
                { name = "PRIMI", transition = "PRIMI", type = "K2", altitude_min = 10300 },
                { name = "HOROD", transition = "PRIMI", type = "K2", altitude_min = 10300 },
                { name = "OCERI", transition = "PRIMI", type = "K2", altitude_min = 8100 },
                { name = "JUMLA", transition = "PRIMI", type = "K2", altitude_min = 7300 },
                { name = "JUMLA", transition = "", type = "K2", altitude_min = 7300 },
                { name = "WINED", transition = "", type = "K2", altitude_min = 6100 },
                { name = "ZIPUG", transition = "", type = "K2", altitude_min = 4980 },
                { name = "RW31L", transition = "", type = "K2" },
                { name = "", transition = "", type = "", altitude_min = 4200 },
                { name = "BIKZE", transition = "", type = "K2", altitude_min = 7700 },
                { name = "BIKZE", transition = "", type = "K2", altitude_max = 9000, speed = 230.0 },
            }
        },
        ["T13RY"] = {
            name = "T13RY",
            type = "A",
            runway = "T13RY",
            waypoints = {
                { name = "HZN", transition = "HZN", type = "K2", altitude_min = 10200 },
                { name = "PILOW", transition = "HZN", type = "K2", altitude_min = 10200 },
                { name = "PILOW", transition = "HZN", type = "K2", speed = 230.0 },
                { name = "AZGER", transition = "HZN", type = "K2" },
                { name = "TYWAN", transition = "HZN", type = "K2", altitude_min = 6000 },
                { name = "LLC", transition = "LLC", type = "K2", altitude_min = 10200 },
                { name = "PILOW", transition = "LLC", type = "K2", altitude_min = 10200 },
                { name = "PILOW", transition = "LLC", type = "K2", speed = 230.0 },
                { name = "AZGER", transition = "LLC", type = "K2" },
                { name = "TYWAN", transition = "LLC", type = "K2", altitude_min = 6000 },
                { name = "TYWAN", transition = "", type = "K2", altitude_min = 6000 },
                { name = "CUPIR", transition = "", type = "K2", altitude_min = 5600 },
                { name = "WONVO", transition = "", type = "K2", altitude_min = 4560 },
                { name = "NUWXO", transition = "", type = "K2" },
                { name = "NFL", transition = "", type = "K2" },
                { name = "MUFIT", transition = "", type = "K2" },
                { name = "MUFIT", transition = "", type = "K2", speed = 230.0 },
            }
        },
        ["T13RZ"] = {
            name = "T13RZ",
            type = "A",
            runway = "T13RZ",
            waypoints = {
                { name = "BAM", transition = "BAM", type = "K2", altitude_min = 20000 },
                { name = "CALAI", transition = "BAM", type = "K2", altitude_min = 20000 },
                { name = "CAXUL", transition = "BAM", type = "K2" },
                { name = "AZGER", transition = "BAM", type = "K2", altitude_min = 11000 },
                { name = "TYWAN", transition = "BAM", type = "K2", altitude_min = 6000 },
                { name = "FMG", transition = "FMG", type = "K2", altitude_min = 20000 },
                { name = "CALAI", transition = "FMG", type = "K2", altitude_min = 20000 },
                { name = "CAXUL", transition = "FMG", type = "K2" },
                { name = "AZGER", transition = "FMG", type = "K2", altitude_min = 11000 },
                { name = "TYWAN", transition = "FMG", type = "K2", altitude_min = 6000 },
                { name = "MVA", transition = "MVA", type = "K2", altitude_min = 20000 },
                { name = "CALAI", transition = "MVA", type = "K2", altitude_min = 20000 },
                { name = "CAXUL", transition = "MVA", type = "K2" },
                { name = "AZGER", transition = "MVA", type = "K2", altitude_min = 11000 },
                { name = "TYWAN", transition = "MVA", type = "K2", altitude_min = 6000 },
                { name = "TYWAN", transition = "", type = "K2", altitude_min = 6000 },
                { name = "CUPIR", transition = "", type = "K2", altitude_min = 5600 },
                { name = "WONVO", transition = "", type = "K2", altitude_min = 4540 },
                { name = "NUWXO", transition = "", type = "K2" },
                { name = "NFL", transition = "", type = "K2" },
                { name = "MUFIT", transition = "", type = "K2" },
                { name = "MUFIT", transition = "", type = "K2", speed = 310.0 },
            }
        },
        ["T31LY"] = {
            name = "T31LY",
            type = "A",
            runway = "T31LY",
            waypoints = {
                { name = "HZN", transition = "HZN1", type = "K2", altitude_min = 10200 },
                { name = "PILOW", transition = "HZN1", type = "K2", altitude_min = 10000 },
                { name = "PILOW", transition = "HZN1", type = "K2", speed = 230.0 },
                { name = "LENCO", transition = "HZN1", type = "K2" },
                { name = "ZOPIS", transition = "HZN1", type = "K2", altitude_min = 8200 },
                { name = "ELMMR", transition = "HZN1", type = "K2", altitude_min = 7600 },
                { name = "HZN", transition = "HZN2", type = "K2", altitude_min = 11000 },
                { name = "MUFIT", transition = "HZN2", type = "K2", altitude_min = 10500 },
                { name = "MUFIT", transition = "HZN2", type = "K2", speed = 230.0 },
                { name = "ELMMR", transition = "HZN2", type = "K2", altitude_min = 7600 },
                { name = "LLC", transition = "LLC", type = "K2", altitude_min = 10200 },
                { name = "PILOW", transition = "LLC", type = "K2", altitude_min = 10000 },
                { name = "PILOW", transition = "LLC", type = "K2", speed = 230.0 },
                { name = "LENCO", transition = "LLC", type = "K2" },
                { name = "ZOPIS", transition = "LLC", type = "K2", altitude_min = 8200 },
                { name = "ELMMR", transition = "LLC", type = "K2", altitude_min = 7600 },
                { name = "ELMMR", transition = "", type = "K2", altitude_min = 7600 },
                { name = "HAKOG", transition = "", type = "K2", altitude_min = 6700 },
                { name = "MIRKE", transition = "", type = "K2", altitude_min = 5700 },
                { name = "CITAB", transition = "", type = "K2", altitude_min = 4600 },
                { name = "FENAT", transition = "", type = "K2" },
                { name = "NFL", transition = "", type = "K2" },
                { name = "WATER", transition = "", type = "K2" },
                { name = "WATER", transition = "", type = "K2", speed = 230.0 },
            }
        },
        ["T31LZ"] = {
            name = "T31LZ",
            type = "A",
            runway = "T31LZ",
            waypoints = {
                { name = "BAM", transition = "BAM", type = "K2", altitude_min = 20000 },
                { name = "RHIDE", transition = "BAM", type = "K2", altitude_min = 20000 },
                { name = "MUFIT", transition = "BAM", type = "K2", altitude_min = 12000 },
                { name = "ELMMR", transition = "BAM", type = "K2", altitude_min = 7600 },
                { name = "FMG", transition = "FMG", type = "K2", altitude_min = 21000 },
                { name = "RHIDE", transition = "FMG", type = "K2", altitude_min = 20000 },
                { name = "MUFIT", transition = "FMG", type = "K2", altitude_min = 12000 },
                { name = "ELMMR", transition = "FMG", type = "K2", altitude_min = 7600 },
                { name = "MVA", transition = "MVA", type = "K2", altitude_min = 20000 },
                { name = "RHIDE", transition = "MVA", type = "K2", altitude_min = 20000 },
                { name = "MUFIT", transition = "MVA", type = "K2", altitude_min = 12000 },
                { name = "ELMMR", transition = "MVA", type = "K2", altitude_min = 7600 },
                { name = "ELMMR", transition = "", type = "K2", altitude_min = 7600 },
                { name = "HAKOG", transition = "", type = "K2", altitude_min = 6700 },
                { name = "MIRKE", transition = "", type = "K2", altitude_min = 5700 },
                { name = "CITAB", transition = "", type = "K2", altitude_min = 4600 },
                { name = "FENAT", transition = "", type = "K2" },
                { name = "NFL", transition = "", type = "K2" },
                { name = "WATER", transition = "", type = "K2" },
                { name = "WATER", transition = "", type = "K2", speed = 230.0 },
            }
        },
        ["T31RY"] = {
            name = "T31RY",
            type = "A",
            runway = "T31RY",
            waypoints = {
                { name = "HZN", transition = "HZN1", type = "K2", altitude_min = 10000 },
                { name = "PILOW", transition = "HZN1", type = "K2", altitude_min = 10000 },
                { name = "PILOW", transition = "HZN1", type = "K2", speed = 230.0 },
                { name = "LENCO", transition = "HZN1", type = "K2" },
                { name = "ZOPIS", transition = "HZN1", type = "K2", altitude_min = 8200 },
                { name = "ELMMR", transition = "HZN1", type = "K2", altitude_min = 7600 },
                { name = "HZN", transition = "HZN2", type = "K2", altitude_min = 11000 },
                { name = "MUFIT", transition = "HZN2", type = "K2", altitude_min = 10500 },
                { name = "MUFIT", transition = "HZN2", type = "K2", speed = 230.0 },
                { name = "ELMMR", transition = "HZN2", type = "K2", altitude_min = 7600 },
                { name = "LLC", transition = "LLC", type = "K2", altitude_min = 10000 },
                { name = "PILOW", transition = "LLC", type = "K2", altitude_min = 10000 },
                { name = "PILOW", transition = "LLC", type = "K2", speed = 230.0 },
                { name = "LENCO", transition = "LLC", type = "K2" },
                { name = "ZOPIS", transition = "LLC", type = "K2", altitude_min = 8200 },
                { name = "ELMMR", transition = "LLC", type = "K2", altitude_min = 7600 },
                { name = "ELMMR", transition = "", type = "K2", altitude_min = 7600 },
                { name = "HAKOG", transition = "", type = "K2", altitude_min = 6700 },
                { name = "MIRKE", transition = "", type = "K2", altitude_min = 5700 },
                { name = "CITAB", transition = "", type = "K2", altitude_min = 4600 },
                { name = "FENAT", transition = "", type = "K2" },
                { name = "NFL", transition = "", type = "K2" },
                { name = "WATER", transition = "", type = "K2" },
                { name = "WATER", transition = "", type = "K2", speed = 230.0 },
            }
        },
        ["T31RZ"] = {
            name = "T31RZ",
            type = "A",
            runway = "T31RZ",
            waypoints = {
                { name = "BAM", transition = "BAM", type = "K2", altitude_min = 20000 },
                { name = "RHIDE", transition = "BAM", type = "K2", altitude_min = 20000 },
                { name = "MUFIT", transition = "BAM", type = "K2", altitude_min = 12000 },
                { name = "ELMMR", transition = "BAM", type = "K2", altitude_min = 7600 },
                { name = "FMG", transition = "FMG", type = "K2", altitude_min = 21000 },
                { name = "RHIDE", transition = "FMG", type = "K2", altitude_min = 20000 },
                { name = "MUFIT", transition = "FMG", type = "K2", altitude_min = 12000 },
                { name = "ELMMR", transition = "FMG", type = "K2", altitude_min = 7600 },
                { name = "MVA", transition = "MVA", type = "K2", altitude_min = 20000 },
                { name = "RHIDE", transition = "MVA", type = "K2", altitude_min = 20000 },
                { name = "MUFIT", transition = "MVA", type = "K2", altitude_min = 12000 },
                { name = "ELMMR", transition = "MVA", type = "K2", altitude_min = 7600 },
                { name = "ELMMR", transition = "", type = "K2", altitude_min = 7600 },
                { name = "HAKOG", transition = "", type = "K2", altitude_min = 6700 },
                { name = "MIRKE", transition = "", type = "K2", altitude_min = 5700 },
                { name = "CITAB", transition = "", type = "K2", altitude_min = 4600 },
                { name = "FENAT", transition = "", type = "K2" },
                { name = "NFL", transition = "", type = "K2" },
                { name = "WATER", transition = "", type = "K2" },
                { name = "WATER", transition = "", type = "K2", speed = 230.0 },
            }
        },
    },

    -- Частоты
    Frequencies = {
        TOWER = 118.0,
        APPROACH = 121.0,
        DEPARTURE = 125.0,
        GROUND = 121.7,
        ATIS = 126.0,
    }
}

return AirportData
