local AirportData = {
    -- Метаданные аэропорта
    Metadata = {
        ICAO = "KNLC",
        Name = "KNLC Airport",
        Elevation = 0,
        MagVar = 0,
        Region = "Nevada"
    },

    -- Путевые точки
    Waypoints = {
        ["NAVRE"] = { lat = 36.556263889, lon = -120.220775, type = "KNLC" },
        ["WHIMP"] = { lat = 36.348694444, lon = -119.968852778, type = "KNLC" },
        ["OWLES"] = { lat = 36.267875, lon = -119.924416667, type = "KNLC" },
        ["HAWKK"] = { lat = 35.886427778, lon = -119.716055556, type = "KNLC" },
        ["HAYEN"] = { lat = 36.56095, lon = -119.975719444, type = "KNLC" },
        ["SUNGE"] = { lat = 36.420344444, lon = -120.008330556, type = "KNLC" },
        ["BEDME"] = { lat = 36.300341667, lon = -119.661730556, type = "KNLC" },
        ["SILUE"] = { lat = 36.086944444, lon = -119.809036111, type = "KNLC" },
        ["MIKSE"] = { lat = 36.456622222, lon = -120.028844444, type = "KNLC" },
        ["OYISU"] = { lat = 36.254044444, lon = -119.900136111, type = "KNLC" },
        ["BUDDZ"] = { lat = 36.307738889, lon = -120.035508333, type = "KNLC" },
        ["CREEZ"] = { lat = 36.438986111, lon = -120.207677778, type = "KNLC" },
        ["BUMPI"] = { lat = 36.2757, lon = -119.492677778, type = "KNLC" },
        ["PHARO"] = { lat = 36.237372222, lon = -119.907675, type = "KNLC" },
        ["LERNE"] = { lat = 36.22905, lon = -119.903472222, type = "KNLC" },
        ["SUZIQ"] = { lat = 36.292272222, lon = -119.937822222, type = "KNLC" },
        ["FLEET"] = { lat = 36.460875, lon = -119.971380556, type = "KNLC" },
        ["EOCIN"] = { lat = 36.533186111, lon = -119.630911111, type = "KNLC" },
        ["STRAT"] = { lat = 36.153980556, lon = -119.706327778, type = "KNLC" },
        ["JEKIR"] = { lat = 36.306222222, lon = -119.702325, type = "KNLC" },
        ["JIGAN"] = { lat = 36.487441667, lon = -119.712375, type = "KNLC" },
        ["NAKLE"] = { lat = 36.437338889, lon = -120.001038889, type = "KNLC" },
        ["PHROG"] = { lat = 36.106480556, lon = -119.838088889, type = "KNLC" },
        ["LAGVE"] = { lat = 36.468361111, lon = -119.746288889, type = "KNLC" },
        ["HELMM"] = { lat = 36.542275, lon = -120.075694444, type = "KNLC" },
        ["HOKDA"] = { lat = 36.377302778, lon = -119.967772222, type = "KNLC" },
        ["TULAR"] = { lat = 36.039052778, lon = -119.799158333, type = "KNLC" },
        ["FINUG"] = { lat = 36.488936111, lon = -120.0462, type = "KNLC" },
        ["CILUN"] = { lat = 36.208980556, lon = -119.875408333, type = "KNLC" },
        ["EDOKE"] = { lat = 36.225736111, lon = -120.190922222, type = "KNLC" },
        ["LEGDE"] = { lat = 36.080577778, lon = -119.6797, type = "KNLC" },
        ["HORNN"] = { lat = 36.145852778, lon = -119.857522222, type = "KNLC" },
        ["SINKE"] = { lat = 36.084827778, lon = -119.824152778, type = "KNLC" },
        ["CARRL"] = { lat = 36.143208333, lon = -120.346613889, type = "KNLC" },
        ["CIVUN"] = { lat = 36.547405556, lon = -120.061875, type = "KNLC" },
    },

    -- Данные ВПП
    Runways = {
        ["RW14L"] = {
            heading = 140,
            length = 0,
            width = 0,
            threshold = { lat = 36.36416388888889, lon = -119.96070277777778 },
            end = { lat = 36.36416388888889, lon = -119.96070277777778 }
        },
        ["RW14R"] = {
            heading = 140,
            length = 0,
            width = 0,
            threshold = { lat = 36.33596666666667, lon = -119.96227222222223 },
            end = { lat = 36.33596666666667, lon = -119.96227222222223 }
        },
        ["RW32L"] = {
            heading = 320,
            length = 0,
            width = 0,
            threshold = { lat = 36.30208888888889, lon = -119.94362777777778 },
            end = { lat = 36.30208888888889, lon = -119.94362777777778 }
        },
        ["RW32R"] = {
            heading = 320,
            length = 0,
            width = 0,
            threshold = { lat = 36.330286111111114, lon = -119.94204722222223 },
            end = { lat = 36.330286111111114, lon = -119.94204722222223 }
        },
    },

    -- Процедуры SID
    SID = {
    },

    -- Процедуры STAR
    STAR = {
    },

    -- Процедуры захода на посадку
    APPROACH = {
        ["R14L"] = {
            name = "R14L",
            type = "A",
            runway = "R14L",
            waypoints = {
                { name = "CIVUN", transition = "CIVUN", type = "K2", altitude_min = 1800, speed = 230.0 },
                { name = "NAVRE", transition = "NAVRE", type = "K2", altitude_min = 1800 },
                { name = "CIVUN", transition = "NAVRE", type = "K2", altitude_min = 1800 },
                { name = "CIVUN", transition = "", type = "K2", altitude_min = 1800 },
                { name = "NAKLE", transition = "", type = "K2", altitude_min = 1800 },
                { name = "RW14L", transition = "", type = "K2" },
                { name = "", transition = "", type = "", altitude_min = 1200 },
                { name = "STRAT", transition = "", type = "K2", altitude_min = 2000 },
                { name = "STRAT", transition = "", type = "K2", altitude_max = 4000, speed = 230.0 },
            }
        },
        ["R14R"] = {
            name = "R14R",
            type = "A",
            runway = "R14R",
            waypoints = {
                { name = "HELMM", transition = "HELMM", type = "K2", altitude_min = 2800, speed = 230.0 },
                { name = "NAVRE", transition = "NAVRE", type = "K2", altitude_min = 2800 },
                { name = "HELMM", transition = "NAVRE", type = "K2", altitude_min = 2800 },
                { name = "HELMM", transition = "", type = "K2", altitude_min = 2800 },
                { name = "MIKSE", transition = "", type = "K2", altitude_min = 2800 },
                { name = "RW14R", transition = "", type = "K2" },
                { name = "", transition = "", type = "", altitude_min = 1200 },
                { name = "PHROG", transition = "", type = "K2", altitude_min = 2000 },
                { name = "PHROG", transition = "", type = "K2", altitude_max = 4000, speed = 230.0 },
            }
        },
        ["R32L"] = {
            name = "R32L",
            type = "A",
            runway = "R32L",
            waypoints = {
                { name = "LEGDE", transition = "LEGDE", type = "K2", altitude_min = 1800 },
                { name = "PHROG", transition = "LEGDE", type = "K2", altitude_min = 1800 },
                { name = "PHROG", transition = "PHROG", type = "K2", altitude_min = 1800, speed = 230.0 },
                { name = "PHROG", transition = "", type = "K2", altitude_min = 1800 },
                { name = "LERNE", transition = "", type = "K2", altitude_min = 1800 },
                { name = "RW32L", transition = "", type = "K2" },
                { name = "", transition = "", type = "", altitude_min = 1000 },
                { name = "CREEZ", transition = "", type = "K2", altitude_min = 3100 },
                { name = "CREEZ", transition = "", type = "K2", altitude_max = 4100, speed = 230.0 },
            }
        },
        ["R32R"] = {
            name = "R32R",
            type = "A",
            runway = "R32R",
            waypoints = {
                { name = "LEGDE", transition = "LEGDE", type = "K2", altitude_min = 2800 },
                { name = "SILUE", transition = "LEGDE", type = "K2", altitude_min = 2800 },
                { name = "SILUE", transition = "SILUE", type = "K2", altitude_min = 2800, speed = 230.0 },
                { name = "SILUE", transition = "", type = "K2", altitude_min = 2800 },
                { name = "CILUN", transition = "", type = "K2", altitude_min = 2800 },
                { name = "OYISU", transition = "", type = "K2", altitude_min = 800 },
                { name = "RW32R", transition = "", type = "K2" },
                { name = "", transition = "", type = "", altitude_min = 1200 },
                { name = "HAYEN", transition = "", type = "K2", altitude_min = 2000 },
                { name = "HAYEN", transition = "", type = "K2", altitude_max = 4000, speed = 230.0 },
            }
        },
        ["T14LY"] = {
            name = "T14LY",
            type = "A",
            runway = "T14LY",
            waypoints = {
                { name = "AVE", transition = "AVE", type = "K2" },
                { name = "CREEZ", transition = "AVE", type = "K2", altitude_min = 4000 },
                { name = "HAYEN", transition = "AVE", type = "K2", altitude_min = 1800 },
                { name = "CZQ", transition = "CZQ", type = "K2", altitude_min = 5000 },
                { name = "CREEZ", transition = "CZQ", type = "K2", altitude_min = 4000 },
                { name = "HAYEN", transition = "CZQ", type = "K2", altitude_min = 1800 },
                { name = "PXN", transition = "PXN", type = "K2", altitude_min = 5000 },
                { name = "CREEZ", transition = "PXN", type = "K2", altitude_min = 4000 },
                { name = "HAYEN", transition = "PXN", type = "K2", altitude_min = 1800 },
                { name = "HAYEN", transition = "", type = "K2", altitude_min = 1800 },
                { name = "FLEET", transition = "", type = "K2", altitude_min = 1800 },
                { name = "HOKDA", transition = "", type = "K2" },
                { name = "", transition = "", type = "", altitude_min = 700 },
                { name = "", transition = "", type = "" },
                { name = "STRAT", transition = "", type = "K2", altitude_min = 2000 },
                { name = "STRAT", transition = "", type = "K2", altitude_max = 4000, speed = 230.0 },
            }
        },
        ["T14LZ"] = {
            name = "T14LZ",
            type = "A",
            runway = "T14LZ",
            waypoints = {
                { name = "BUDDZ", transition = "BUDDZ", type = "K2", altitude_min = 12000 },
                { name = "NLC", transition = "BUDDZ", type = "K2", altitude_min = 12000 },
                { name = "LAGVE", transition = "BUDDZ", type = "K2" },
                { name = "HAYEN", transition = "BUDDZ", type = "K2", altitude_max = 4000 },
                { name = "CARRL", transition = "CARRL", type = "K2", altitude_min = 12000 },
                { name = "BUDDZ", transition = "CARRL", type = "K2", altitude_min = 12000 },
                { name = "NLC", transition = "CARRL", type = "K2", altitude_min = 12000 },
                { name = "LAGVE", transition = "CARRL", type = "K2" },
                { name = "HAYEN", transition = "CARRL", type = "K2", altitude_max = 4000 },
                { name = "EOCIN", transition = "EOCIN", type = "K2", altitude_min = 12000 },
                { name = "JIGAN", transition = "EOCIN", type = "K2", altitude_min = 12000 },
                { name = "LAGVE", transition = "EOCIN", type = "K2" },
                { name = "HAYEN", transition = "EOCIN", type = "K2", altitude_max = 4000 },
                { name = "HAYEN", transition = "", type = "K2", altitude_min = 3000 },
                { name = "FLEET", transition = "", type = "K2", altitude_min = 1800 },
                { name = "HOKDA", transition = "", type = "K2" },
                { name = "", transition = "", type = "", altitude_min = 700 },
                { name = "", transition = "", type = "" },
                { name = "STRAT", transition = "", type = "K2", altitude_min = 2000 },
                { name = "STRAT", transition = "", type = "K2", altitude_max = 6000, speed = 230.0 },
            }
        },
        ["T14RY"] = {
            name = "T14RY",
            type = "A",
            runway = "T14RY",
            waypoints = {
                { name = "AVE", transition = "AVE", type = "K2", altitude_min = 6000 },
                { name = "CREEZ", transition = "AVE", type = "K2", altitude_min = 4000 },
                { name = "HELMM", transition = "AVE", type = "K2", altitude_min = 2800 },
                { name = "CZQ", transition = "CZQ", type = "K2" },
                { name = "CREEZ", transition = "CZQ", type = "K2", altitude_min = 5000 },
                { name = "CREEZ", transition = "CZQ", type = "K2", altitude_min = 4000, speed = 230.0 },
                { name = "HELMM", transition = "CZQ", type = "K2", altitude_min = 2800 },
                { name = "HORNN", transition = "HORNN", type = "K2" },
                { name = "CREEZ", transition = "HORNN", type = "K2", altitude_min = 2800 },
                { name = "HELMM", transition = "HORNN", type = "K2", altitude_min = 2800 },
                { name = "PXN", transition = "PXN", type = "K2", altitude_min = 5000 },
                { name = "CREEZ", transition = "PXN", type = "K2", altitude_min = 5000 },
                { name = "HELMM", transition = "PXN", type = "K2", altitude_min = 2800 },
                { name = "HELMM", transition = "", type = "K2", altitude_min = 2800 },
                { name = "FINUG", transition = "", type = "K2", altitude_min = 2800 },
                { name = "SUNGE", transition = "", type = "K2", altitude_min = 1800 },
                { name = "WHIMP", transition = "", type = "K2" },
                { name = "HORNN", transition = "", type = "K2", altitude_min = 3000 },
                { name = "HORNN", transition = "", type = "K2", altitude_max = 6000, speed = 230.0 },
            }
        },
        ["T14RZ"] = {
            name = "T14RZ",
            type = "A",
            runway = "T14RZ",
            waypoints = {
                { name = "BUDDZ", transition = "BUDDZ", type = "K2", altitude_min = 12000 },
                { name = "NLC", transition = "BUDDZ", type = "K2", altitude_min = 12000 },
                { name = "LAGVE", transition = "BUDDZ", type = "K2" },
                { name = "HAYEN", transition = "BUDDZ", type = "K2", altitude_max = 4000 },
                { name = "HELMM", transition = "BUDDZ", type = "K2", altitude_min = 3000 },
                { name = "CARRL", transition = "CARRL", type = "K2", altitude_min = 12000 },
                { name = "BUDDZ", transition = "CARRL", type = "K2", altitude_min = 12000 },
                { name = "NLC", transition = "CARRL", type = "K2", altitude_min = 12000 },
                { name = "LAGVE", transition = "CARRL", type = "K2" },
                { name = "HAYEN", transition = "CARRL", type = "K2", altitude_max = 4000 },
                { name = "HELMM", transition = "CARRL", type = "K2", altitude_min = 3000 },
                { name = "EOCIN", transition = "EOCIN", type = "K2", altitude_min = 12000 },
                { name = "JIGAN", transition = "EOCIN", type = "K2", altitude_min = 12000 },
                { name = "LAGVE", transition = "EOCIN", type = "K2" },
                { name = "HAYEN", transition = "EOCIN", type = "K2", altitude_max = 4000 },
                { name = "HELMM", transition = "EOCIN", type = "K2", altitude_min = 3000 },
                { name = "HELMM", transition = "", type = "K2", altitude_min = 3000 },
                { name = "FINUG", transition = "", type = "K2", altitude_min = 2800 },
                { name = "SUNGE", transition = "", type = "K2", altitude_min = 1800 },
                { name = "WHIMP", transition = "", type = "K2" },
                { name = "HORNN", transition = "", type = "K2", altitude_min = 3000 },
                { name = "HORNN", transition = "", type = "K2", altitude_max = 6000, speed = 230.0 },
            }
        },
        ["T32LX"] = {
            name = "T32LX",
            type = "A",
            runway = "T32LX",
            waypoints = {
                { name = "BUDDZ", transition = "BUDDZ", type = "K2", altitude_min = 12000 },
                { name = "NLC", transition = "BUDDZ", type = "K2" },
                { name = "JEKIR", transition = "BUDDZ", type = "K2" },
                { name = "HORNN", transition = "BUDDZ", type = "K2", altitude_min = 3000 },
                { name = "BUMPI", transition = "BUMPI", type = "K2", altitude_min = 12000 },
                { name = "BEDME", transition = "BUMPI", type = "K2", altitude_min = 12000 },
                { name = "JEKIR", transition = "BUMPI", type = "K2" },
                { name = "HORNN", transition = "BUMPI", type = "K2", altitude_min = 3000 },
                { name = "CARRL", transition = "CARR1", type = "K2", altitude_min = 12000 },
                { name = "EDOKE", transition = "CARR1", type = "K2" },
                { name = "HORNN", transition = "CARR1", type = "K2", altitude_min = 3000 },
                { name = "CARRL", transition = "CARR2", type = "K2", altitude_min = 12000 },
                { name = "NLC", transition = "CARR2", type = "K2", altitude_min = 12000 },
                { name = "JEKIR", transition = "CARR2", type = "K2" },
                { name = "HORNN", transition = "CARR2", type = "K2", altitude_min = 3000 },
                { name = "HORNN", transition = "", type = "K2", altitude_min = 3000 },
                { name = "PHARO", transition = "", type = "K2", altitude_min = 1800 },
                { name = "OWLES", transition = "", type = "K2", altitude_min = 1080 },
                { name = "SUZIQ", transition = "", type = "K2" },
                { name = "NLC", transition = "", type = "K2", altitude_min = 630 },
                { name = "CREEZ", transition = "", type = "K2", altitude_min = 3000 },
                { name = "CREEZ", transition = "", type = "K2", altitude_max = 4000, speed = 230.0 },
            }
        },
        ["T32LY"] = {
            name = "T32LY",
            type = "A",
            runway = "T32LY",
            waypoints = {
                { name = "AVE", transition = "AVE", type = "K2", altitude_min = 3000 },
                { name = "STRAT", transition = "AVE", type = "K2", altitude_min = 3000 },
                { name = "STRAT", transition = "AVE", type = "K2", altitude_min = 3000, speed = 230.0 },
                { name = "SINKE", transition = "AVE", type = "K2", altitude_min = 1800 },
                { name = "CZQ", transition = "CZQ", type = "K2", altitude_min = 3000 },
                { name = "STRAT", transition = "CZQ", type = "K2", altitude_min = 3000 },
                { name = "SINKE", transition = "CZQ", type = "K2", altitude_min = 1800 },
                { name = "EHF", transition = "EHF", type = "K2", altitude_min = 3000 },
                { name = "STRAT", transition = "EHF", type = "K2", altitude_min = 3000 },
                { name = "SINKE", transition = "EHF", type = "K2", altitude_min = 1800 },
                { name = "SINKE", transition = "", type = "K2", altitude_min = 1800 },
                { name = "PHARO", transition = "", type = "K2", altitude_min = 1800 },
                { name = "OWLES", transition = "", type = "K2", altitude_min = 1080 },
                { name = "SUZIQ", transition = "", type = "K2" },
                { name = "NLC", transition = "", type = "K2", altitude_min = 3000 },
                { name = "CREEZ", transition = "", type = "K2", altitude_min = 3000 },
                { name = "CREEZ", transition = "", type = "K2", speed = 230.0 },
            }
        },
        ["T32LZ"] = {
            name = "T32LZ",
            type = "A",
            runway = "T32LZ",
            waypoints = {
                { name = "AVE", transition = "AVE", type = "K2", altitude_min = 15000 },
                { name = "HAWKK", transition = "AVE", type = "K2", altitude_min = 15000 },
                { name = "TULAR", transition = "AVE", type = "K2" },
                { name = "HORNN", transition = "AVE", type = "K2", altitude_min = 3000 },
                { name = "CZQ", transition = "CZQ", type = "K2", altitude_min = 15000 },
                { name = "TULAR", transition = "CZQ", type = "K2", altitude_min = 15000 },
                { name = "TULAR", transition = "CZQ", type = "K2", altitude_min = 15000, speed = 310.0 },
                { name = "HORNN", transition = "CZQ", type = "K2", altitude_min = 3000 },
                { name = "EHF", transition = "EHF", type = "K2", altitude_min = 15000 },
                { name = "HAWKK", transition = "EHF", type = "K2", altitude_min = 15000 },
                { name = "TULAR", transition = "EHF", type = "K2" },
                { name = "HORNN", transition = "EHF", type = "K2", altitude_min = 3000 },
                { name = "HORNN", transition = "", type = "K2", altitude_min = 3000 },
                { name = "PHARO", transition = "", type = "K2", altitude_min = 1800 },
                { name = "OWLES", transition = "", type = "K2", altitude_min = 1080 },
                { name = "SUZIQ", transition = "", type = "K2" },
                { name = "NLC", transition = "", type = "K2", altitude_min = 630 },
                { name = "CREEZ", transition = "", type = "K2", altitude_min = 3000 },
                { name = "CREEZ", transition = "", type = "K2", altitude_max = 4000, speed = 230.0 },
            }
        },
    },

    -- Частоты
    Frequencies = {
        TOWER = 118.0,
        APPROACH = 121.0,
        DEPARTURE = 125.0,
        GROUND = 121.7,
        ATIS = 126.0,
    }
}

return AirportData
