local AirportData = {
    -- Метаданные аэропорта
    Metadata = {
        ICAO = "PGUM",
        Name = "PGUM Airport",
        Elevation = 0,
        MagVar = 0,
        Region = "Marianas"
    },

    -- Путевые точки
    Waypoints = {
        ["FISON"] = { lat = 13.439588889, lon = 144.702716667, type = "PGUM" },
        ["CADUK"] = { lat = 13.724119444, lon = 144.920919444, type = "PGUM" },
        ["RASPE"] = { lat = 13.467522222, lon = 144.557236111, type = "PGUM" },
        ["NOVKE"] = { lat = 13.491758333, lon = 144.812072222, type = "PGUM" },
        ["D256I"] = { lat = 23.623619444, lon = 113.085672222, type = "ZGGG" },
        ["D229I"] = { lat = 13.359302778, lon = 144.614063889, type = "PGUM" },
        ["ADAYI"] = { lat = 13.572472222, lon = 144.970844444, type = "PGUM" },
        ["MOGOE"] = { lat = 13.526175, lon = 144.879741667, type = "PGUM" },
        ["JITNO"] = { lat = 13.511683333, lon = 144.590855556, type = "PGUM" },
        ["GUMGE"] = { lat = 13.085411111, lon = 145.197808333, type = "ENRT" },
        ["HARLO"] = { lat = 13.44095, lon = 144.701038889, type = "PGUM" },
        ["WUVEN"] = { lat = 14.056186111, lon = 144.432641667, type = "ENRT" },
        ["DALPE"] = { lat = 13.389908333, lon = 144.594286111, type = "PGUM" },
        ["FIBEE"] = { lat = 13.567827778, lon = 144.973386111, type = "PGUM" },
        ["OBALE"] = { lat = 13.391655556, lon = 144.593452778, type = "PGUM" },
        ["FIGOR"] = { lat = 13.30575, lon = 144.757369444, type = "PGUM" },
        ["JOMAX"] = { lat = 13.523894444, lon = 144.887011111, type = "PGUM" },
        ["PAVYI"] = { lat = 13.534444444, lon = 144.905516667, type = "PGUM" },
        ["HAGIX"] = { lat = 13.727319444, lon = 144.923375, type = "PGUM" },
        ["FOLAP"] = { lat = 13.300197222, lon = 144.449269444, type = "PGUM" },
        ["MEMKE"] = { lat = 13.389941667, lon = 144.594269444, type = "PGUM" },
        ["JUVNI"] = { lat = 13.524169444, lon = 144.880769444, type = "PGUM" },
        ["D257I"] = { lat = 13.425761111, lon = 144.582219444, type = "PGUM" },
        ["HUKES"] = { lat = 13.452347222, lon = 144.730586111, type = "PGUM" },
        ["CIBOL"] = { lat = 13.572430556, lon = 144.993308333, type = "PGUM" },
        ["ASADE"] = { lat = 12.793166667, lon = 144.840038889, type = "ENRT" },
        ["SIDPE"] = { lat = 13.496577778, lon = 145.029469444, type = "PGUM" },
        ["PULEE"] = { lat = 13.523625, lon = 144.052730556, type = "ENRT" },
        ["ADEDE"] = { lat = 13.441391667, lon = 144.702002778, type = "PGUM" },
        ["BAGBE"] = { lat = 13.654308333, lon = 145.296286111, type = "ENRT" },
        ["RW06R"] = { lat = 40.884847222, lon = 29.302591667, type = "LTFJ" },
        ["CULPS"] = { lat = 13.997672222, lon = 144.958061111, type = "ENRT" },
        ["CETAS"] = { lat = 13.589955556, lon = 144.665788889, type = "PGUM" },
        ["BOLFY"] = { lat = 13.455513889, lon = 144.732852778, type = "PGUM" },
        ["CEGMU"] = { lat = 13.439605556, lon = 144.702716667, type = "PGUM" },
        ["HESNA"] = { lat = 13.404597222, lon = 144.412411111, type = "PGUM" },
        ["WABOX"] = { lat = 13.575619444, lon = 144.995738889, type = "PGUM" },
        ["YASSU"] = { lat = 13.470258333, lon = 144.580211111, type = "ENRT" },
        ["BURLE"] = { lat = 13.240013889, lon = 144.665758333, type = "PGUM" },
        ["D230I"] = { lat = 42.036705556, lon = 12.226616667, type = "LIRF" },
        ["FAPAM"] = { lat = 13.423894444, lon = 145.068011111, type = "PGUM" },
    },

    -- Данные ВПП
    Runways = {
        ["RW06L"] = {
            heading = 60,
            length = 0,
            width = 0,
            threshold = { lat = 13.478908333333333, lon = 144.78398055555556 },
            end = { lat = 13.478908333333333, lon = 144.78398055555556 }
        },
        ["RW06R"] = {
            heading = 60,
            length = 0,
            width = 0,
            threshold = { lat = 13.477158333333334, lon = 144.7848138888889 },
            end = { lat = 13.477158333333334, lon = 144.7848138888889 }
        },
        ["RW24L"] = {
            heading = 240,
            length = 0,
            width = 0,
            threshold = { lat = 13.487666666666666, lon = 144.80779444444445 },
            end = { lat = 13.487666666666666, lon = 144.80779444444445 }
        },
        ["RW24R"] = {
            heading = 240,
            length = 0,
            width = 0,
            threshold = { lat = 13.49175, lon = 144.81206944444446 },
            end = { lat = 13.49175, lon = 144.81206944444446 }
        },
    },

    -- Процедуры SID
    SID = {
    },

    -- Процедуры STAR
    STAR = {
    },

    -- Процедуры захода на посадку
    APPROACH = {
        ["D24R"] = {
            name = "D24R",
            type = "A",
            runway = "D24R",
            waypoints = {
                { name = "UNZ", transition = "UNZ", type = "PG" },
                { name = "FIBEE", transition = "UNZ", type = "PG", altitude_min = 2300 },
                { name = "FIBEE", transition = "UNZ", type = "PG", altitude_min = 2300 },
                { name = "FIBEE", transition = "", type = "PG", altitude_min = 2300 },
                { name = "JUVNI", transition = "", type = "PG", altitude_min = 1800 },
                { name = "NOVKE", transition = "", type = "PG" },
                { name = "", transition = "", type = "", altitude_min = 2300 },
                { name = "FIBEE", transition = "", type = "PG" },
                { name = "FIBEE", transition = "", type = "PG" },
            }
        },
        ["I06L"] = {
            name = "I06L",
            type = "A",
            runway = "I06L",
            waypoints = {
                { name = "CETAS", transition = "CETAS", type = "PG" },
                { name = "D257I", transition = "CETAS", type = "PG", altitude_min = 3000 },
                { name = "", transition = "CETAS", type = "" },
                { name = "FIGOR", transition = "FIGOR", type = "PG" },
                { name = "D230I", transition = "FIGOR", type = "PG", altitude_min = 3000 },
                { name = "", transition = "FIGOR", type = "" },
                { name = "UNZ", transition = "UNZ", type = "PG" },
                { name = "OBALE", transition = "UNZ", type = "PG", altitude_min = 3000 },
                { name = "OBALE", transition = "UNZ", type = "PG", altitude_min = 3000 },
                { name = "OBALE", transition = "", type = "PG" },
                { name = "HARLO", transition = "", type = "PG" },
                { name = "RW06L", transition = "", type = "PG" },
                { name = "", transition = "", type = "", altitude_min = 2100 },
                { name = "UNZ", transition = "", type = "PG", altitude_min = 3000 },
                { name = "OBALE", transition = "", type = "PG" },
                { name = "OBALE", transition = "", type = "PG" },
            }
        },
        ["I06R"] = {
            name = "I06R",
            type = "A",
            runway = "I06R",
            waypoints = {
                { name = "CETAS", transition = "CETAS", type = "PG" },
                { name = "JITNO", transition = "CETAS", type = "PG" },
                { name = "YASSU", transition = "CETAS", type = "PG" },
                { name = "D256I", transition = "CETAS", type = "PG", altitude_min = 3000 },
                { name = "", transition = "CETAS", type = "" },
                { name = "FIGOR", transition = "FIGOR", type = "PG" },
                { name = "D229I", transition = "FIGOR", type = "PG", altitude_min = 3000 },
                { name = "", transition = "FIGOR", type = "" },
                { name = "FOLAP", transition = "FOLAP", type = "PG" },
                { name = "", transition = "FOLAP", type = "" },
                { name = "MEMKE", transition = "FOLAP", type = "PG", altitude_min = 3000 },
                { name = "HESNA", transition = "HESNA", type = "PG" },
                { name = "", transition = "HESNA", type = "" },
                { name = "MEMKE", transition = "HESNA", type = "PG", altitude_min = 3000 },
                { name = "JITNO", transition = "JITNO", type = "PG" },
                { name = "YASSU", transition = "JITNO", type = "PG" },
                { name = "D256I", transition = "JITNO", type = "PG", altitude_min = 3000 },
                { name = "", transition = "JITNO", type = "" },
                { name = "UNZ", transition = "UNZ", type = "PG" },
                { name = "MEMKE", transition = "UNZ", type = "PG", altitude_min = 3000 },
                { name = "MEMKE", transition = "UNZ", type = "PG", altitude_min = 3000 },
                { name = "YASSU", transition = "YASSU", type = "PG" },
                { name = "D256I", transition = "YASSU", type = "PG", altitude_min = 3000 },
                { name = "", transition = "YASSU", type = "" },
                { name = "MEMKE", transition = "", type = "PG" },
                { name = "CEGMU", transition = "", type = "PG" },
                { name = "RW06R", transition = "", type = "PG" },
                { name = "", transition = "", type = "", altitude_min = 2100 },
                { name = "UNZ", transition = "", type = "PG" },
                { name = "MEMKE", transition = "", type = "PG", altitude_min = 3000 },
                { name = "MEMKE", transition = "", type = "PG" },
            }
        },
        ["Q24R"] = {
            name = "Q24R",
            type = "A",
            runway = "Q24R",
            waypoints = {
                { name = "UNZ", transition = "UNZ", type = "PG" },
                { name = "ADAYI", transition = "UNZ", type = "PG", altitude_min = 2300 },
                { name = "ADAYI", transition = "UNZ", type = "PG", altitude_min = 2300 },
                { name = "ADAYI", transition = "", type = "PG", altitude_min = 2300 },
                { name = "MOGOE", transition = "", type = "PG", altitude_min = 1800 },
                { name = "NOVKE", transition = "", type = "PG" },
                { name = "AJA", transition = "", type = "PG" },
                { name = "ADAYI", transition = "", type = "PG", altitude_min = 2300 },
                { name = "ADAYI", transition = "", type = "PG" },
            }
        },
        ["R06LY"] = {
            name = "R06LY",
            type = "A",
            runway = "R06LY",
            waypoints = {
                { name = "ASADE", transition = "ASADE", type = "PG" },
                { name = "BURLE", transition = "ASADE", type = "PG", altitude_min = 3000 },
                { name = "OBALE", transition = "ASADE", type = "PG", altitude_min = 3000 },
                { name = "PULEE", transition = "PULEE", type = "PG" },
                { name = "OBALE", transition = "PULEE", type = "PG", altitude_min = 3000 },
                { name = "UNZ", transition = "UNZ", type = "PG" },
                { name = "OBALE", transition = "UNZ", type = "PG", altitude_min = 3000 },
                { name = "OBALE", transition = "UNZ", type = "PG", altitude_min = 3000 },
                { name = "WUVEN", transition = "WUVEN", type = "PG" },
                { name = "RASPE", transition = "WUVEN", type = "PG", altitude_min = 3000 },
                { name = "OBALE", transition = "WUVEN", type = "PG", altitude_min = 3000 },
                { name = "OBALE", transition = "", type = "PG", altitude_min = 3000 },
                { name = "ADEDE", transition = "", type = "PG", altitude_min = 2000 },
                { name = "BOLFY", transition = "", type = "PG", altitude_min = 1480 },
                { name = "RW06L", transition = "", type = "PG" },
                { name = "", transition = "", type = "", altitude_min = 705 },
                { name = "WABOX", transition = "", type = "PG", altitude_min = 3000 },
                { name = "WABOX", transition = "", type = "PG" },
            }
        },
        ["R06LZ"] = {
            name = "R06LZ",
            type = "A",
            runway = "R06LZ",
            waypoints = {
                { name = "ASADE", transition = "ASADE", type = "PG", altitude_max = 15100 },
                { name = "BURLE", transition = "ASADE", type = "PG", altitude_min = 3000, altitude_max = 6100 },
                { name = "OBALE", transition = "ASADE", type = "PG", altitude_min = 3000 },
                { name = "PULEE", transition = "PULEE", type = "PG", altitude_max = 13300 },
                { name = "OBALE", transition = "PULEE", type = "PG", altitude_min = 3000 },
                { name = "WUVEN", transition = "WUVEN", type = "PG", altitude_max = 15900 },
                { name = "RASPE", transition = "WUVEN", type = "PG", altitude_min = 3000, altitude_max = 4500, speed = 210.0 },
                { name = "OBALE", transition = "WUVEN", type = "PG", altitude_min = 3000 },
                { name = "OBALE", transition = "", type = "PG", altitude_min = 3000 },
                { name = "ADEDE", transition = "", type = "PG", altitude_min = 2000 },
                { name = "RW06L", transition = "", type = "PG" },
                { name = "WABOX", transition = "", type = "PG", altitude_min = 3000 },
                { name = "WABOX", transition = "", type = "PG" },
            }
        },
        ["R06RY"] = {
            name = "R06RY",
            type = "A",
            runway = "R06RY",
            waypoints = {
                { name = "ASADE", transition = "ASADE", type = "PG" },
                { name = "BURLE", transition = "ASADE", type = "PG", altitude_min = 3000 },
                { name = "DALPE", transition = "ASADE", type = "PG", altitude_min = 3000 },
                { name = "PULEE", transition = "PULEE", type = "PG" },
                { name = "DALPE", transition = "PULEE", type = "PG", altitude_min = 3000 },
                { name = "UNZ", transition = "UNZ", type = "PG" },
                { name = "DALPE", transition = "UNZ", type = "PG", altitude_min = 3000 },
                { name = "DALPE", transition = "UNZ", type = "PG", altitude_min = 3000 },
                { name = "WUVEN", transition = "WUVEN", type = "PG" },
                { name = "RASPE", transition = "WUVEN", type = "PG", altitude_min = 3000 },
                { name = "DALPE", transition = "WUVEN", type = "PG", altitude_min = 3000 },
                { name = "DALPE", transition = "", type = "PG", altitude_min = 3000 },
                { name = "FISON", transition = "", type = "PG", altitude_min = 2000 },
                { name = "HUKES", transition = "", type = "PG", altitude_min = 1440 },
                { name = "RW06R", transition = "", type = "PG" },
                { name = "", transition = "", type = "", altitude_min = 705 },
                { name = "CIBOL", transition = "", type = "PG", altitude_min = 3000 },
                { name = "CIBOL", transition = "", type = "PG" },
            }
        },
        ["R06RZ"] = {
            name = "R06RZ",
            type = "A",
            runway = "R06RZ",
            waypoints = {
                { name = "ASADE", transition = "ASADE", type = "PG", altitude_max = 15100 },
                { name = "BURLE", transition = "ASADE", type = "PG", altitude_min = 3000, altitude_max = 6100 },
                { name = "DALPE", transition = "ASADE", type = "PG", altitude_min = 3000 },
                { name = "PULEE", transition = "PULEE", type = "PG", altitude_max = 13300 },
                { name = "DALPE", transition = "PULEE", type = "PG", altitude_min = 3000 },
                { name = "WUVEN", transition = "WUVEN", type = "PG", altitude_max = 16000 },
                { name = "RASPE", transition = "WUVEN", type = "PG", altitude_min = 3000, altitude_max = 4600, speed = 210.0 },
                { name = "DALPE", transition = "WUVEN", type = "PG", altitude_min = 3000 },
                { name = "DALPE", transition = "", type = "PG", altitude_min = 3000 },
                { name = "FISON", transition = "", type = "PG", altitude_min = 2000 },
                { name = "RW06R", transition = "", type = "PG" },
                { name = "CIBOL", transition = "", type = "PG", altitude_min = 3000 },
                { name = "CIBOL", transition = "", type = "PG" },
            }
        },
        ["R24LY"] = {
            name = "R24LY",
            type = "A",
            runway = "R24LY",
            waypoints = {
                { name = "BAGBE", transition = "BAGBE", type = "PG" },
                { name = "CIBOL", transition = "BAGBE", type = "PG", altitude_min = 3000 },
                { name = "CULPS", transition = "CULPS", type = "PG" },
                { name = "CADUK", transition = "CULPS", type = "PG", altitude_min = 3000 },
                { name = "CIBOL", transition = "CULPS", type = "PG", altitude_min = 3000 },
                { name = "GUMGE", transition = "GUMGE", type = "PG" },
                { name = "SIDPE", transition = "GUMGE", type = "PG", altitude_min = 3000 },
                { name = "CIBOL", transition = "GUMGE", type = "PG", altitude_min = 3000 },
                { name = "UNZ", transition = "UNZ", type = "PG" },
                { name = "CIBOL", transition = "UNZ", type = "PG", altitude_min = 3000 },
                { name = "CIBOL", transition = "UNZ", type = "PG", altitude_min = 3000 },
                { name = "CIBOL", transition = "", type = "PG", altitude_min = 3000 },
                { name = "JOMAX", transition = "", type = "PG", altitude_min = 2000 },
                { name = "RW24L", transition = "", type = "PG" },
                { name = "", transition = "", type = "", altitude_min = 705 },
                { name = "DALPE", transition = "", type = "PG", altitude_min = 3000 },
                { name = "DALPE", transition = "", type = "PG" },
            }
        },
        ["R24LZ"] = {
            name = "R24LZ",
            type = "A",
            runway = "R24LZ",
            waypoints = {
                { name = "BAGBE", transition = "BAGBE", type = "PG", altitude_max = 8800 },
                { name = "CIBOL", transition = "BAGBE", type = "PG", altitude_min = 3000 },
                { name = "CULPS", transition = "CULPS", type = "PG", altitude_max = 11300 },
                { name = "CADUK", transition = "CULPS", type = "PG", altitude_min = 3000, altitude_max = 6100 },
                { name = "CIBOL", transition = "CULPS", type = "PG", altitude_min = 3000 },
                { name = "GUMGE", transition = "GUMGE", type = "PG", altitude_max = 12900 },
                { name = "SIDPE", transition = "GUMGE", type = "PG", altitude_min = 3000, altitude_max = 4500 },
                { name = "CIBOL", transition = "GUMGE", type = "PG", altitude_min = 3000 },
                { name = "CIBOL", transition = "", type = "PG", altitude_min = 3000 },
                { name = "JOMAX", transition = "", type = "PG", altitude_min = 2000 },
                { name = "RW24L", transition = "", type = "PG" },
                { name = "DALPE", transition = "", type = "PG", altitude_min = 3000 },
                { name = "DALPE", transition = "", type = "PG" },
            }
        },
        ["R24RY"] = {
            name = "R24RY",
            type = "A",
            runway = "R24RY",
            waypoints = {
                { name = "BAGBE", transition = "BAGBE", type = "PG" },
                { name = "WABOX", transition = "BAGBE", type = "PG", altitude_min = 3000 },
                { name = "CULPS", transition = "CULPS", type = "PG" },
                { name = "HAGIX", transition = "CULPS", type = "PG", altitude_min = 3000 },
                { name = "WABOX", transition = "CULPS", type = "PG", altitude_min = 3000 },
                { name = "GUMGE", transition = "GUMGE", type = "PG" },
                { name = "FAPAM", transition = "GUMGE", type = "PG", altitude_min = 3000 },
                { name = "WABOX", transition = "GUMGE", type = "PG", altitude_min = 3000 },
                { name = "UNZ", transition = "UNZ", type = "PG" },
                { name = "WABOX", transition = "UNZ", type = "PG", altitude_min = 3000 },
                { name = "WABOX", transition = "UNZ", type = "PG", altitude_min = 3000 },
                { name = "WABOX", transition = "", type = "PG", altitude_min = 3000 },
                { name = "PAVYI", transition = "", type = "PG", altitude_min = 2300 },
                { name = "RW24R", transition = "", type = "PG" },
                { name = "", transition = "", type = "", altitude_min = 705 },
                { name = "OBALE", transition = "", type = "PG", altitude_min = 3000 },
                { name = "OBALE", transition = "", type = "PG" },
            }
        },
        ["R24RZ"] = {
            name = "R24RZ",
            type = "A",
            runway = "R24RZ",
            waypoints = {
                { name = "BAGBE", transition = "BAGBE", type = "PG" },
                { name = "WABOX", transition = "BAGBE", type = "PG", altitude_min = 3000 },
                { name = "CULPS", transition = "CULPS", type = "PG" },
                { name = "HAGIX", transition = "CULPS", type = "PG", altitude_min = 3000 },
                { name = "WABOX", transition = "CULPS", type = "PG", altitude_min = 3000 },
                { name = "GUMGE", transition = "GUMGE", type = "PG" },
                { name = "FAPAM", transition = "GUMGE", type = "PG", altitude_min = 3000 },
                { name = "WABOX", transition = "GUMGE", type = "PG", altitude_min = 3000 },
                { name = "WABOX", transition = "", type = "PG", altitude_min = 3000 },
                { name = "PAVYI", transition = "", type = "PG", altitude_min = 2300 },
                { name = "RW24R", transition = "", type = "PG" },
                { name = "OBALE", transition = "", type = "PG", altitude_min = 3000 },
                { name = "OBALE", transition = "", type = "PG" },
            }
        },
        ["T24R"] = {
            name = "T24R",
            type = "A",
            runway = "T24R",
            waypoints = {
                { name = "UNZ", transition = "UNZ", type = "PG" },
                { name = "FIBEE", transition = "UNZ", type = "PG", altitude_min = 2300 },
                { name = "FIBEE", transition = "UNZ", type = "PG", altitude_min = 2300 },
                { name = "FIBEE", transition = "", type = "PG", altitude_min = 2300 },
                { name = "JUVNI", transition = "", type = "PG", altitude_min = 1800 },
                { name = "NOVKE", transition = "", type = "PG" },
                { name = "", transition = "", type = "", altitude_min = 2300 },
                { name = "FIBEE", transition = "", type = "PG" },
                { name = "FIBEE", transition = "", type = "PG" },
            }
        },
    },

    -- Частоты
    Frequencies = {
        TOWER = 118.0,
        APPROACH = 121.0,
        DEPARTURE = 125.0,
        GROUND = 121.7,
        ATIS = 126.0,
    }
}

return AirportData
