-- Example MOOSE data file for KJFK (John F. Kennedy) airport
-- Generated by dtc_parser.py
-- Date: April 2025

local KJFK_Data = {}

-- Airport metadata
KJFK_Data.metadata = {
    ICAO = "KJFK",
    name = "John F. Kennedy International Airport",
    elevation = 13,
    lat = 40.639751,
    lon = -73.778925,
    magvar = -13.0
}

-- Runways
KJFK_Data.runways = {
    ["04L"] = {
        heading = 40,
        length = 12079,
        width = 200,
        threshold = {
            lat = 40.6297,
            lon = -73.7922
        },
        end_point = {
            lat = 40.6456,
            lon = -73.7705
        }
    },
    ["22R"] = {
        heading = 220,
        length = 12079,
        width = 200,
        threshold = {
            lat = 40.6456,
            lon = -73.7705
        },
        end_point = {
            lat = 40.6297,
            lon = -73.7922
        }
    },
    ["04R"] = {
        heading = 40,
        length = 8400,
        width = 200,
        threshold = {
            lat = 40.6222,
            lon = -73.7839
        },
        end_point = {
            lat = 40.6339,
            lon = -73.7683
        }
    },
    ["22L"] = {
        heading = 220,
        length = 8400,
        width = 200,
        threshold = {
            lat = 40.6339,
            lon = -73.7683
        },
        end_point = {
            lat = 40.6222,
            lon = -73.7839
        }
    },
    ["13L"] = {
        heading = 130,
        length = 10000,
        width = 200,
        threshold = {
            lat = 40.6456,
            lon = -73.7922
        },
        end_point = {
            lat = 40.6339,
            lon = -73.7683
        }
    },
    ["31R"] = {
        heading = 310,
        length = 10000,
        width = 200,
        threshold = {
            lat = 40.6339,
            lon = -73.7683
        },
        end_point = {
            lat = 40.6456,
            lon = -73.7922
        }
    },
    ["13R"] = {
        heading = 130,
        length = 14511,
        width = 200,
        threshold = {
            lat = 40.6456,
            lon = -73.8039
        },
        end_point = {
            lat = 40.6222,
            lon = -73.7683
        }
    },
    ["31L"] = {
        heading = 310,
        length = 14511,
        width = 200,
        threshold = {
            lat = 40.6222,
            lon = -73.7683
        },
        end_point = {
            lat = 40.6456,
            lon = -73.8039
        }
    }
}

-- Waypoints
KJFK_Data.waypoints = {
    ["CAMRN"] = {
        type = "FIX",
        lat = 40.7500,
        lon = -73.9000
    },
    ["LENDY"] = {
        type = "FIX",
        lat = 40.8000,
        lon = -73.8000
    },
    ["ROBER"] = {
        type = "FIX",
        lat = 40.6500,
        lon = -73.6000
    },
    ["MERIT"] = {
        type = "FIX",
        lat = 40.5000,
        lon = -73.5000
    },
    ["BETTE"] = {
        type = "FIX",
        lat = 40.4000,
        lon = -73.4000
    },
    ["JFK"] = {
        type = "VOR",
        lat = 40.6398,
        lon = -73.7789,
        frequency = 115.9
    },
    ["IDLEWILD"] = {
        type = "NDB",
        lat = 40.6380,
        lon = -73.7770,
        frequency = 278
    }
}

-- SID procedures
KJFK_Data.sids = {
    ["DEEZZ5"] = {
        runway = "13L",
        waypoints = {
            {name = "JFK", altitude_min = 1000, altitude_max = nil, speed = 210},
            {name = "CAMRN", altitude_min = 3000, altitude_max = nil, speed = 250},
            {name = "LENDY", altitude_min = 5000, altitude_max = nil, speed = 280}
        }
    },
    ["SKORR3"] = {
        runway = "31R",
        waypoints = {
            {name = "JFK", altitude_min = 1000, altitude_max = nil, speed = 210},
            {name = "ROBER", altitude_min = 3000, altitude_max = nil, speed = 250},
            {name = "MERIT", altitude_min = 5000, altitude_max = nil, speed = 280}
        }
    },
    ["GAYEL4"] = {
        runway = "04L",
        waypoints = {
            {name = "IDLEWILD", altitude_min = 1000, altitude_max = nil, speed = 210},
            {name = "BETTE", altitude_min = 3000, altitude_max = nil, speed = 250},
            {name = "MERIT", altitude_min = 5000, altitude_max = nil, speed = 280}
        }
    }
}

-- STAR procedures
KJFK_Data.stars = {
    ["CAMRN4"] = {
        runway = "22R",
        waypoints = {
            {name = "LENDY", altitude_min = 10000, altitude_max = nil, speed = 280},
            {name = "CAMRN", altitude_min = 7000, altitude_max = 10000, speed = 250},
            {name = "JFK", altitude_min = 3000, altitude_max = 7000, speed = 210}
        }
    },
    ["LENDY3"] = {
        runway = "04L",
        waypoints = {
            {name = "MERIT", altitude_min = 10000, altitude_max = nil, speed = 280},
            {name = "ROBER", altitude_min = 7000, altitude_max = 10000, speed = 250},
            {name = "JFK", altitude_min = 3000, altitude_max = 7000, speed = 210}
        }
    },
    ["ROBER2"] = {
        runway = "13L",
        waypoints = {
            {name = "MERIT", altitude_min = 10000, altitude_max = nil, speed = 280},
            {name = "BETTE", altitude_min = 7000, altitude_max = 10000, speed = 250},
            {name = "IDLEWILD", altitude_min = 3000, altitude_max = 7000, speed = 210}
        }
    }
}

-- Approach procedures
KJFK_Data.approaches = {
    ["ILS04L"] = {
        type = "ILS",
        runway = "04L",
        waypoints = {
            {name = "JFK", altitude_min = 3000, altitude_max = nil, speed = 210},
            {name = "ROBER", altitude_min = 2000, altitude_max = 3000, speed = 180},
            {name = "CAMRN", altitude_min = 1000, altitude_max = 2000, speed = 160}
        }
    },
    ["ILS22R"] = {
        type = "ILS",
        runway = "22R",
        waypoints = {
            {name = "JFK", altitude_min = 3000, altitude_max = nil, speed = 210},
            {name = "CAMRN", altitude_min = 2000, altitude_max = 3000, speed = 180},
            {name = "ROBER", altitude_min = 1000, altitude_max = 2000, speed = 160}
        }
    },
    ["VOR13L"] = {
        type = "VOR",
        runway = "13L",
        waypoints = {
            {name = "JFK", altitude_min = 3000, altitude_max = nil, speed = 210},
            {name = "BETTE", altitude_min = 2000, altitude_max = 3000, speed = 180},
            {name = "MERIT", altitude_min = 1000, altitude_max = 2000, speed = 160}
        }
    },
    ["NDB31R"] = {
        type = "NDB",
        runway = "31R",
        waypoints = {
            {name = "IDLEWILD", altitude_min = 3000, altitude_max = nil, speed = 210},
            {name = "MERIT", altitude_min = 2000, altitude_max = 3000, speed = 180},
            {name = "BETTE", altitude_min = 1000, altitude_max = 2000, speed = 160}
        }
    }
}

-- Frequencies
KJFK_Data.frequencies = {
    ["ATIS"] = 128.725,
    ["GROUND"] = 121.9,
    ["TOWER"] = 119.1,
    ["APPROACH"] = 124.35,
    ["DEPARTURE"] = 135.9
}

return KJFK_Data
