-- Example MOOSE data file for UUWW (Vnukovo) airport
-- Generated by dtc_parser.py
-- Date: April 2025

local UUWW_Data = {}

-- Airport metadata
UUWW_Data.metadata = {
    ICAO = "UUWW",
    name = "Vnukovo",
    elevation = 686,
    lat = 55.591531,
    lon = 37.261486,
    magvar = 10.0
}

-- Runways
UUWW_Data.runways = {
    ["06"] = {
        heading = 59,
        length = 10499,
        width = 197,
        threshold = {
            lat = 55.5882,
            lon = 37.2472
        },
        end_point = {
            lat = 55.5992,
            lon = 37.2792
        }
    },
    ["24"] = {
        heading = 239,
        length = 10499,
        width = 197,
        threshold = {
            lat = 55.5992,
            lon = 37.2792
        },
        end_point = {
            lat = 55.5882,
            lon = 37.2472
        }
    },
    ["01"] = {
        heading = 14,
        length = 10039,
        width = 197,
        threshold = {
            lat = 55.5832,
            lon = 37.2622
        },
        end_point = {
            lat = 55.6022,
            lon = 37.2722
        }
    },
    ["19"] = {
        heading = 194,
        length = 10039,
        width = 197,
        threshold = {
            lat = 55.6022,
            lon = 37.2722
        },
        end_point = {
            lat = 55.5832,
            lon = 37.2622
        }
    }
}

-- Waypoints
UUWW_Data.waypoints = {
    ["ABCDE"] = {
        type = "FIX",
        lat = 55.7500,
        lon = 37.4000
    },
    ["DEFGH"] = {
        type = "FIX",
        lat = 55.8000,
        lon = 37.5000
    },
    ["FGHIJ"] = {
        type = "FIX",
        lat = 55.6500,
        lon = 37.3000
    },
    ["JKLMN"] = {
        type = "FIX",
        lat = 55.5000,
        lon = 37.1000
    },
    ["OPQRS"] = {
        type = "FIX",
        lat = 55.4000,
        lon = 37.0000
    },
    ["VNO"] = {
        type = "VOR",
        lat = 55.5915,
        lon = 37.2615,
        frequency = 117.3
    },
    ["VN"] = {
        type = "NDB",
        lat = 55.5900,
        lon = 37.2600,
        frequency = 342
    }
}

-- SID procedures
UUWW_Data.sids = {
    ["ABCDE1A"] = {
        runway = "06",
        waypoints = {
            {name = "VNO", altitude_min = 1000, altitude_max = nil, speed = 210},
            {name = "ABCDE", altitude_min = 3000, altitude_max = nil, speed = 250},
            {name = "DEFGH", altitude_min = 5000, altitude_max = nil, speed = 280}
        }
    },
    ["FGHIJ2B"] = {
        runway = "24",
        waypoints = {
            {name = "VNO", altitude_min = 1000, altitude_max = nil, speed = 210},
            {name = "FGHIJ", altitude_min = 3000, altitude_max = nil, speed = 250},
            {name = "JKLMN", altitude_min = 5000, altitude_max = nil, speed = 280}
        }
    },
    ["OPQRS3C"] = {
        runway = "01",
        waypoints = {
            {name = "VN", altitude_min = 1000, altitude_max = nil, speed = 210},
            {name = "OPQRS", altitude_min = 3000, altitude_max = nil, speed = 250},
            {name = "JKLMN", altitude_min = 5000, altitude_max = nil, speed = 280}
        }
    }
}

-- STAR procedures
UUWW_Data.stars = {
    ["ABCDE1A"] = {
        runway = "24",
        waypoints = {
            {name = "DEFGH", altitude_min = 10000, altitude_max = nil, speed = 280},
            {name = "ABCDE", altitude_min = 7000, altitude_max = 10000, speed = 250},
            {name = "VNO", altitude_min = 3000, altitude_max = 7000, speed = 210}
        }
    },
    ["FGHIJ2B"] = {
        runway = "06",
        waypoints = {
            {name = "JKLMN", altitude_min = 10000, altitude_max = nil, speed = 280},
            {name = "FGHIJ", altitude_min = 7000, altitude_max = 10000, speed = 250},
            {name = "VNO", altitude_min = 3000, altitude_max = 7000, speed = 210}
        }
    },
    ["OPQRS3C"] = {
        runway = "19",
        waypoints = {
            {name = "JKLMN", altitude_min = 10000, altitude_max = nil, speed = 280},
            {name = "OPQRS", altitude_min = 7000, altitude_max = 10000, speed = 250},
            {name = "VN", altitude_min = 3000, altitude_max = 7000, speed = 210}
        }
    }
}

-- Approach procedures
UUWW_Data.approaches = {
    ["ILS06"] = {
        type = "ILS",
        runway = "06",
        waypoints = {
            {name = "VNO", altitude_min = 3000, altitude_max = nil, speed = 210},
            {name = "FGHIJ", altitude_min = 2000, altitude_max = 3000, speed = 180},
            {name = "ABCDE", altitude_min = 1000, altitude_max = 2000, speed = 160}
        }
    },
    ["ILS24"] = {
        type = "ILS",
        runway = "24",
        waypoints = {
            {name = "VNO", altitude_min = 3000, altitude_max = nil, speed = 210},
            {name = "ABCDE", altitude_min = 2000, altitude_max = 3000, speed = 180},
            {name = "FGHIJ", altitude_min = 1000, altitude_max = 2000, speed = 160}
        }
    },
    ["VOR01"] = {
        type = "VOR",
        runway = "01",
        waypoints = {
            {name = "VNO", altitude_min = 3000, altitude_max = nil, speed = 210},
            {name = "OPQRS", altitude_min = 2000, altitude_max = 3000, speed = 180},
            {name = "JKLMN", altitude_min = 1000, altitude_max = 2000, speed = 160}
        }
    },
    ["NDB19"] = {
        type = "NDB",
        runway = "19",
        waypoints = {
            {name = "VN", altitude_min = 3000, altitude_max = nil, speed = 210},
            {name = "JKLMN", altitude_min = 2000, altitude_max = 3000, speed = 180},
            {name = "OPQRS", altitude_min = 1000, altitude_max = 2000, speed = 160}
        }
    }
}

-- Frequencies
UUWW_Data.frequencies = {
    ["ATIS"] = 125.2,
    ["GROUND"] = 119.0,
    ["TOWER"] = 118.5,
    ["APPROACH"] = 121.75,
    ["DEPARTURE"] = 125.25
}

return UUWW_Data
