local AirportData = {
    -- Метаданные аэропорта
    Metadata = {
        ICAO = "OMAA",
        Name = "OMAA Airport",
        Elevation = 0,
        MagVar = 0,
        Region = "PersianGulf"
    },

    -- Путевые точки
    Waypoints = {
        ["VEGIR"] = { lat = 24.19675, lon = 54.776777778, type = "ENRT" },
        ["PEKAX"] = { lat = 24.582111111, lon = 54.174444444, type = "ENRT" },
        ["AA641"] = { lat = 24.558527778, lon = 54.519277778, type = "OMAA" },
        ["KINIL"] = { lat = 24.577388889, lon = 54.447416667, type = "OMAA" },
        ["AA408"] = { lat = 24.632722222, lon = 54.401833333, type = "OMAA" },
        ["AA644"] = { lat = 24.584916667, lon = 54.657888889, type = "OMAA" },
        ["IMTUP"] = { lat = 24.322861111, lon = 55.062583333, type = "ENRT" },
        ["IVEGU"] = { lat = 24.381277778, lon = 54.75625, type = "OMAA" },
        ["AA822"] = { lat = 24.529055556, lon = 54.35825, type = "OMAA" },
        ["AA823"] = { lat = 24.528416667, lon = 54.054805556, type = "OMAA" },
        ["AA771"] = { lat = 24.322805556, lon = 54.806277778, type = "OMAA" },
        ["PUVOD"] = { lat = 24.591638889, lon = 54.459527778, type = "OMAA" },
        ["SETRU"] = { lat = 24.303638889, lon = 54.86575, type = "OMAA" },
        ["AA653"] = { lat = 24.410083333, lon = 54.483416667, type = "OMAA" },
        ["AA673"] = { lat = 24.614805556, lon = 54.518888889, type = "OMAA" },
        ["DERVA"] = { lat = 24.529916667, lon = 54.546777778, type = "OMAA" },
        ["NOPNU"] = { lat = 24.3255, lon = 54.684861111, type = "OMAA" },
        ["AA623"] = { lat = 24.432444444, lon = 54.482361111, type = "OMAA" },
        ["MEPDO"] = { lat = 24.526388889, lon = 54.449527778, type = "ENRT" },
        ["AA721"] = { lat = 24.306027778, lon = 54.777583333, type = "OMAA" },
        ["AA827"] = { lat = 24.554388889, lon = 54.818694444, type = "OMAA" },
        ["ORMED"] = { lat = 24.419583333, lon = 54.522611111, type = "ENRT" },
        ["RUDON"] = { lat = 24.401777778, lon = 54.727416667, type = "OMAA" },
        ["OBMUK"] = { lat = 24.734194444, lon = 54.491777778, type = "ENRT" },
        ["KUSOK"] = { lat = 24.360944444, lon = 54.752666667, type = "OMAA" },
        ["AA526"] = { lat = 24.185833333, lon = 55.030194444, type = "OMAA" },
        ["DEGVO"] = { lat = 24.58525, lon = 54.319416667, type = "ENRT" },
        ["OVOLA"] = { lat = 24.703944444, lon = 54.420138889, type = "ENRT" },
        ["AA524"] = { lat = 24.303138889, lon = 55.014361111, type = "OMAA" },
        ["VUTOK"] = { lat = 24.551277778, lon = 54.273916667, type = "OMAA" },
        ["AA732"] = { lat = 24.427972222, lon = 54.881055556, type = "OMAA" },
        ["PUVUT"] = { lat = 24.120277778, lon = 54.9725, type = "ENRT" },
        ["30VOR"] = { lat = 35.37105, lon = 4.246863889, type = "DAAD" },
        ["LOVUB"] = { lat = 24.506027778, lon = 54.580527778, type = "OMAA" },
        ["AA611"] = { lat = 24.564555556, lon = 54.497833333, type = "OMAA" },
        ["AA842"] = { lat = 24.405444444, lon = 54.838888889, type = "OMAA" },
        ["AA420"] = { lat = 9.035588889, lon = 7.386466667, type = "DNAA" },
        ["RESIG"] = { lat = 24.525611111, lon = 54.552888889, type = "OMAA" },
        ["AA652"] = { lat = 24.47225, lon = 54.448222222, type = "OMAA" },
        ["AA722"] = { lat = 24.260972222, lon = 54.744638889, type = "OMAA" },
        ["MENDU"] = { lat = 24.526666667, lon = 54.551361111, type = "OMAA" },
        ["ASMUP"] = { lat = 24.322972222, lon = 54.806055556, type = "OMAA" },
        ["AA430"] = { lat = 8.900319444, lon = 7.187958333, type = "DNAA" },
        ["MUTOP"] = { lat = 24.77425, lon = 54.595888889, type = "ENRT" },
        ["KUVIN"] = { lat = 24.661138889, lon = 54.44325, type = "OMAA" },
        ["MERPU"] = { lat = 24.05425, lon = 55.033888889, type = "ENRT" },
        ["TOMDO"] = { lat = 24.83325, lon = 54.386444444, type = "ENRT" },
        ["LUBUS"] = { lat = 24.736777778, lon = 54.44175, type = "OMAA" },
        ["AA520"] = { lat = 40.361472222, lon = 116.569472222, type = "ZBAA" },
        ["DAXIB"] = { lat = 24.912916667, lon = 54.150305556, type = "ENRT" },
        ["KANIP"] = { lat = 24.177777778, lon = 55.345, type = "ENRT" },
        ["AA522"] = { lat = 24.559666667, lon = 54.683583333, type = "OMAA" },
        ["SODEL"] = { lat = 24.652833333, lon = 54.4925, type = "ENRT" },
        ["AA642"] = { lat = 24.608388889, lon = 54.543583333, type = "OMAA" },
        ["AA631"] = { lat = 24.420027778, lon = 54.720305556, type = "OMAA" },
        ["AA701"] = { lat = 24.522833333, lon = 54.816555556, type = "OMAA" },
        ["SITIB"] = { lat = 24.022555556, lon = 55.101305556, type = "OMAA" },
        ["AA743"] = { lat = 24.28525, lon = 54.661083333, type = "OMAA" },
        ["AA416"] = { lat = 16.643472222, lon = -99.672, type = "MMAA" },
        ["MUSUL"] = { lat = 24.679944444, lon = 54.250833333, type = "ENRT" },
        ["EMATI"] = { lat = 24.391944444, lon = 54.918055556, type = "ENRT" },
        ["MUNPA"] = { lat = 24.618527778, lon = 54.926833333, type = "ENRT" },
        ["LUBIK"] = { lat = 24.288527778, lon = 54.854388889, type = "OMAA" },
        ["ITLIV"] = { lat = 24.751472222, lon = 54.822694444, type = "ENRT" },
        ["AA751"] = { lat = 24.497166667, lon = 54.610611111, type = "OMAA" },
        ["MD13R"] = { lat = 37.926777778, lon = 12.463394444, type = "LICT" },
        ["AA643"] = { lat = 24.610138889, lon = 54.637083333, type = "OMAA" },
        ["AA825"] = { lat = 24.613527778, lon = 54.719361111, type = "OMAA" },
        ["PATAM"] = { lat = 24.496555556, lon = 54.925472222, type = "ENRT" },
        ["AA432"] = { lat = 24.536666667, lon = 54.537222222, type = "OMAA" },
        ["ORGAD"] = { lat = 24.593555556, lon = 54.332194444, type = "ENRT" },
        ["LORID"] = { lat = 24.93125, lon = 54.651138889, type = "ENRT" },
        ["TADBU"] = { lat = 24.619805556, lon = 54.569083333, type = "OMAA" },
        ["AA820"] = { lat = 24.524222222, lon = 54.522583333, type = "OMAA" },
        ["RUKOS"] = { lat = 24.390194444, lon = 54.505222222, type = "ENRT" },
        ["RABDU"] = { lat = 24.401944444, lon = 54.646083333, type = "ENRT" },
        ["UKILI"] = { lat = 24.637638889, lon = 53.943444444, type = "ENRT" },
        ["AA671"] = { lat = 24.543333333, lon = 54.495555556, type = "OMAA" },
        ["DASNU"] = { lat = 24.414972222, lon = 54.89425, type = "OMAA" },
        ["ORSOB"] = { lat = 24.484638889, lon = 54.578444444, type = "OMAA" },
        ["TUGVA"] = { lat = 24.583888889, lon = 54.904222222, type = "OMAA" },
        ["ORDAK"] = { lat = 24.673555556, lon = 54.343916667, type = "OMAA" },
        ["OTUTU"] = { lat = 24.467944444, lon = 54.335555556, type = "ENRT" },
        ["AA604"] = { lat = 24.597472222, lon = 54.647555556, type = "OMAA" },
        ["LORUP"] = { lat = 24.417666667, lon = 55.000666667, type = "ENRT" },
        ["AA621"] = { lat = 24.533388889, lon = 54.487444444, type = "OMAA" },
        ["LONUP"] = { lat = 24.602444444, lon = 54.767861111, type = "ENRT" },
        ["AA731"] = { lat = 24.367833333, lon = 54.820027778, type = "OMAA" },
        ["AA834"] = { lat = 24.366666667, lon = 54.912027778, type = "OMAA" },
        ["ALSOV"] = { lat = 24.315277778, lon = 55.04325, type = "OMAA" },
        ["KATIG"] = { lat = 24.381444444, lon = 54.723833333, type = "OMAA" },
        ["AA530"] = { lat = 24.478472222, lon = 54.352916667, type = "OMAA" },
        ["SISUG"] = { lat = 24.469166667, lon = 54.831361111, type = "ENRT" },
        ["EMOSU"] = { lat = 24.329555556, lon = 54.796777778, type = "OMAA" },
        ["AA568"] = { lat = 24.714388889, lon = 54.286, type = "OMAA" },
        ["AA613"] = { lat = 24.637083333, lon = 54.536972222, type = "OMAA" },
        ["EMERU"] = { lat = 24.808055556, lon = 55.050833333, type = "ENRT" },
        ["AA415"] = { lat = 24.431444444, lon = 54.685666667, type = "OMAA" },
        ["PAXIK"] = { lat = 24.648305556, lon = 54.230194444, type = "ENRT" },
        ["AA602"] = { lat = 24.624916667, lon = 54.562777778, type = "OMAA" },
        ["AA839"] = { lat = 24.257361111, lon = 54.898083333, type = "OMAA" },
        ["ORPEP"] = { lat = 24.533722222, lon = 54.192944444, type = "ENRT" },
        ["PEGUM"] = { lat = 24.220611111, lon = 54.981583333, type = "ENRT" },
        ["AA711"] = { lat = 24.347583333, lon = 54.816805556, type = "OMAA" },
        ["AA826"] = { lat = 24.570944444, lon = 54.103777778, type = "OMAA" },
        ["GIPNA"] = { lat = 24.377833333, lon = 54.761083333, type = "OMAA" },
        ["RADSO"] = { lat = 24.367722222, lon = 54.745361111, type = "OMAA" },
        ["AA622"] = { lat = 24.490194444, lon = 54.451916667, type = "OMAA" },
        ["AA712"] = { lat = 24.407416667, lon = 54.877416667, type = "OMAA" },
        ["AA713"] = { lat = 24.485194444, lon = 54.823611111, type = "OMAA" },
        ["ELEXU"] = { lat = 24.543083333, lon = 54.495916667, type = "OMAA" },
        ["IMSIG"] = { lat = 24.659333333, lon = 54.331861111, type = "OMAA" },
        ["MURSU"] = { lat = 24.805638889, lon = 54.669888889, type = "ENRT" },
        ["EGSUP"] = { lat = 24.365277778, lon = 54.360916667, type = "ENRT" },
        ["ITREN"] = { lat = 24.206333333, lon = 54.969472222, type = "ENRT" },
        ["MUVUM"] = { lat = 24.634083333, lon = 54.629166667, type = "ENRT" },
        ["AA442"] = { lat = 24.500555556, lon = 54.765277778, type = "OMAA" },
        ["LOSOV"] = { lat = 24.382138889, lon = 54.755027778, type = "OMAA" },
        ["SOKOV"] = { lat = 24.536555556, lon = 54.50525, type = "OMAA" },
        ["AA651"] = { lat = 24.51425, lon = 54.485416667, type = "OMAA" },
        ["AA817"] = { lat = 24.132027778, lon = 55.250888889, type = "OMAA" },
        ["TONKI"] = { lat = 24.445861111, lon = 54.814222222, type = "ENRT" },
        ["AA723"] = { lat = 24.273611111, lon = 54.663111111, type = "OMAA" },
        ["AA741"] = { lat = 24.32725, lon = 54.783638889, type = "OMAA" },
        ["MEKRI"] = { lat = 24.523, lon = 53.916666667, type = "ENRT" },
        ["ITKOV"] = { lat = 24.288416667, lon = 54.854527778, type = "OMAA" },
        ["RIBUV"] = { lat = 24.718805556, lon = 54.548638889, type = "ENRT" },
        ["AA583"] = { lat = 40.406583333, lon = 116.544861111, type = "ZBAA" },
        ["AA601"] = { lat = 24.5815, lon = 54.5275, type = "OMAA" },
        ["ROVOS"] = { lat = 24.306944444, lon = 55.361944444, type = "ENRT" },
        ["AA762"] = { lat = 24.332444444, lon = 54.877722222, type = "OMAA" },
        ["GIDOB"] = { lat = 24.745916667, lon = 53.997944444, type = "ENRT" },
        ["TAPTO"] = { lat = 24.208333333, lon = 54.818305556, type = "ENRT" },
        ["AA441"] = { lat = 24.615277778, lon = 54.603611111, type = "OMAA" },
        ["LAGVU"] = { lat = 24.484916667, lon = 54.089666667, type = "ENRT" },
        ["RALDA"] = { lat = 24.551972222, lon = 54.4855, type = "OMAA" },
        ["GEXOD"] = { lat = 24.393611111, lon = 55.079166667, type = "ENRT" },
        ["AA672"] = { lat = 24.555388889, lon = 54.462583333, type = "OMAA" },
        ["BOMOS"] = { lat = 24.316472222, lon = 54.817416667, type = "OMAA" },
        ["SIVOV"] = { lat = 24.533972222, lon = 54.391527778, type = "ENRT" },
        ["AA824"] = { lat = 24.768277778, lon = 54.576611111, type = "OMAA" },
        ["UKPAP"] = { lat = 24.617166667, lon = 54.876888889, type = "ENRT" },
        ["OBTOL"] = { lat = 24.606083333, lon = 54.406777778, type = "OMAA" },
        ["LOVIM"] = { lat = 24.49575, lon = 54.564972222, type = "OMAA" },
        ["ELOVU"] = { lat = 24.955916667, lon = 54.338194444, type = "ENRT" },
        ["AA742"] = { lat = 24.278361111, lon = 54.756027778, type = "OMAA" },
        ["ULALA"] = { lat = 24.409, lon = 54.855527778, type = "ENRT" },
        ["NOBTO"] = { lat = 23.923611111, lon = 55.311111111, type = "ENRT" },
        ["BOSIG"] = { lat = 24.105638889, lon = 54.962083333, type = "ENRT" },
        ["LOSID"] = { lat = 24.670722222, lon = 54.496611111, type = "ENRT" },
        ["LOXIX"] = { lat = 24.354527778, lon = 54.942416667, type = "ENRT" },
        ["OBVIK"] = { lat = 24.434277778, lon = 54.531694444, type = "ENRT" },
        ["ORNEL"] = { lat = 24.05325, lon = 55.328361111, type = "ENRT" },
        ["TUMEX"] = { lat = 24.511388889, lon = 54.692222222, type = "ENRT" },
        ["RIDIB"] = { lat = 24.541333333, lon = 54.877472222, type = "ENRT" },
        ["AA428"] = { lat = 24.618361111, lon = 54.389638889, type = "OMAA" },
        ["ITUGO"] = { lat = 24.516111111, lon = 54.715361111, type = "ENRT" },
        ["IVEPO"] = { lat = 24.579611111, lon = 54.596027778, type = "ENRT" },
        ["ATUDO"] = { lat = 24.285555556, lon = 54.575555556, type = "ENRT" },
        ["RIGIP"] = { lat = 24.767111111, lon = 54.3305, type = "ENRT" },
        ["AA612"] = { lat = 24.578138889, lon = 54.455527778, type = "OMAA" },
        ["RETUX"] = { lat = 24.506722222, lon = 54.547277778, type = "OMAA" },
        ["AA761"] = { lat = 24.343111111, lon = 54.809861111, type = "OMAA" },
        ["BOSEV"] = { lat = 24.837027778, lon = 54.080222222, type = "ENRT" },
        ["PUXUT"] = { lat = 24.636972222, lon = 54.363194444, type = "ENRT" },
        ["AA772"] = { lat = 24.314305556, lon = 54.880277778, type = "OMAA" },
        ["ELEPO"] = { lat = 24.536388889, lon = 54.736111111, type = "ENRT" },
        ["AA519"] = { lat = 24.157, lon = 54.890222222, type = "OMAA" },
        ["KITOX"] = { lat = 24.361527778, lon = 55.184305556, type = "ENRT" },
        ["VEDEX"] = { lat = 24.567222222, lon = 54.461666667, type = "OMAA" },
        ["AA836"] = { lat = 24.402083333, lon = 54.911527778, type = "OMAA" },
        ["AA733"] = { lat = 24.508166667, lon = 54.810888889, type = "OMAA" },
        ["GISVU"] = { lat = 24.251722222, lon = 55.086277778, type = "ENRT" },
        ["TULON"] = { lat = 24.919833333, lon = 54.794194444, type = "ENRT" },
        ["AA603"] = { lat = 24.617027778, lon = 54.631027778, type = "OMAA" },
        ["PEGEB"] = { lat = 24.322611111, lon = 54.955083333, type = "ENRT" },
    },

    -- Данные ВПП
    Runways = {
        ["RW13L"] = {
            heading = 130,
            length = 0,
            width = 0,
            threshold = { lat = 24.465080555555556, lon = 54.63825277777778 },
            end = { lat = 24.465080555555556, lon = 54.63825277777778 }
        },
        ["RW13R"] = {
            heading = 130,
            length = 0,
            width = 0,
            threshold = { lat = 24.444411111111112, lon = 54.63518611111111 },
            end = { lat = 24.444411111111112, lon = 54.63518611111111 }
        },
        ["RW31L"] = {
            heading = 310,
            length = 0,
            width = 0,
            threshold = { lat = 24.4217, lon = 54.667183333333334 },
            end = { lat = 24.4217, lon = 54.667183333333334 }
        },
        ["RW31R"] = {
            heading = 310,
            length = 0,
            width = 0,
            threshold = { lat = 24.4424, lon = 54.67021111111111 },
            end = { lat = 24.4424, lon = 54.67021111111111 }
        },
    },

    -- Процедуры SID
    SID = {
        ["ATUD1U"] = {
            name = "ATUD1U",
            runway = "RW31L",
            waypoints = {
                { name = "AA820", type = "P", speed = 220.0 },
                { name = "OBTOL", type = "P", altitude_min = 5000 },
                { name = "KUVIN", type = "P", speed = 220.0 },
                { name = "MUVUM", type = "E" },
                { name = "AA825", type = "P", altitude_max = 9000 },
                { name = "LONUP", type = "E", altitude_min = 10000 },
                { name = "AA827", type = "P", altitude_min = 11000, speed = 220.0 },
                { name = "ATUDO", type = "E", altitude_min = 12000 },
            }
        },
        ["ATUD3P"] = {
            name = "ATUD3P",
            runway = "RW31R",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "TADBU", type = "P", altitude_min = 3500 },
                { name = "MURSU", type = "E", altitude_max = 9000 },
                { name = "ITLIV", type = "E", altitude_min = 9000, speed = 230.0 },
                { name = "LONUP", type = "E", altitude_min = 10000 },
                { name = "ATUDO", type = "E", altitude_min = 12000 },
            }
        },
        ["ATUD4K"] = {
            name = "ATUD4K",
            runway = "RW31L",
            waypoints = {
                { name = "AA820", type = "P" },
                { name = "OBTOL", type = "P", altitude_min = 5000 },
                { name = "KUVIN", type = "P" },
                { name = "OBMUK", type = "E", altitude_min = 7500 },
                { name = "AA824", type = "P", altitude_max = 9000, speed = 230.0 },
                { name = "MURSU", type = "E", altitude_min = 10000 },
                { name = "ITLIV", type = "E", altitude_min = 11000, speed = 250.0 },
                { name = "LONUP", type = "E", altitude_min = 12000 },
                { name = "ATUDO", type = "E" },
            }
        },
        ["ATUD5F"] = {
            name = "ATUD5F",
            runway = "RW13L",
            waypoints = {
                { name = "", type = "", altitude_min = 500 },
                { name = "AA836", type = "P", altitude_min = 4000, speed = 230.0 },
                { name = "PATAM", type = "E", altitude_min = 5000, altitude_max = 7000 },
                { name = "UKPAP", type = "E", altitude_max = 8000, speed = 230.0 },
                { name = "LONUP", type = "E", altitude_min = 9000, speed = 250.0 },
                { name = "RABDU", type = "E", altitude_min = 10000 },
                { name = "ATUDO", type = "E", altitude_min = 12000 },
            }
        },
        ["ATUD5G"] = {
            name = "ATUD5G",
            runway = "RW13R",
            waypoints = {
                { name = "ITKOV", type = "P", altitude_min = 4000 },
                { name = "AA839", type = "P", altitude_min = 5000, speed = 230.0 },
                { name = "PEGEB", type = "E", speed = 230.0 },
                { name = "AA842", type = "P", altitude_max = 7000 },
                { name = "RABDU", type = "E", altitude_min = 10000 },
                { name = "ATUDO", type = "E", altitude_min = 12000 },
            }
        },
        ["BOSE1F"] = {
            name = "BOSE1F",
            runway = "RW13L",
            waypoints = {
                { name = "", type = "", altitude_min = 500 },
                { name = "ULALA", type = "E", speed = 230.0 },
                { name = "AA834", type = "P", altitude_min = 4500, altitude_max = 7000 },
                { name = "ITKOV", type = "P", altitude_min = 6000 },
                { name = "VEGIR", type = "E", speed = 230.0 },
                { name = "RUKOS", type = "E", altitude_max = 7000 },
                { name = "EGSUP", type = "E", altitude_min = 9000 },
                { name = "MUSUL", type = "E", altitude_min = 13000 },
                { name = "BOSEV", type = "E", altitude_min = 15000 },
            }
        },
        ["BOSE1G"] = {
            name = "BOSE1G",
            runway = "RW13R",
            waypoints = {
                { name = "ITKOV", type = "P", altitude_min = 4000 },
                { name = "VEGIR", type = "E", speed = 230.0 },
                { name = "RUKOS", type = "E", altitude_max = 7000 },
                { name = "EGSUP", type = "E", altitude_min = 9000 },
                { name = "MUSUL", type = "E", altitude_min = 13000 },
                { name = "BOSEV", type = "E", altitude_min = 15000 },
            }
        },
        ["BOSE1K"] = {
            name = "BOSE1K",
            runway = "RW31L",
            waypoints = {
                { name = "AA820", type = "P" },
                { name = "OBTOL", type = "P", altitude_min = 5000 },
                { name = "PUXUT", type = "E", altitude_max = 9000, speed = 250.0 },
                { name = "BOSEV", type = "E", altitude_min = 10000 },
            }
        },
        ["BOSE1P"] = {
            name = "BOSE1P",
            runway = "RW31R",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "TADBU", type = "P", altitude_min = 3500, speed = 230.0 },
                { name = "LOSID", type = "E", altitude_min = 5000 },
                { name = "BOSEV", type = "E", altitude_min = 10000 },
            }
        },
        ["DAXI1F"] = {
            name = "DAXI1F",
            runway = "RW13L",
            waypoints = {
                { name = "", type = "", altitude_min = 500 },
                { name = "AA836", type = "P", altitude_min = 4000, speed = 230.0 },
                { name = "PATAM", type = "E", altitude_min = 5000, altitude_max = 7000 },
                { name = "UKPAP", type = "E", altitude_max = 8000 },
                { name = "ITLIV", type = "E", altitude_min = 9500 },
                { name = "MURSU", type = "E", altitude_min = 12000 },
                { name = "DAXIB", type = "E", altitude_min = 15000 },
            }
        },
        ["DAXI1G"] = {
            name = "DAXI1G",
            runway = "RW13R",
            waypoints = {
                { name = "ITKOV", type = "P", altitude_min = 4000 },
                { name = "AA839", type = "P", altitude_min = 5000, speed = 230.0 },
                { name = "PEGEB", type = "E", speed = 230.0 },
                { name = "PATAM", type = "E", altitude_min = 5000, altitude_max = 7000 },
                { name = "UKPAP", type = "E", altitude_max = 8000 },
                { name = "ITLIV", type = "E", altitude_min = 9500 },
                { name = "MURSU", type = "E", altitude_min = 12000 },
                { name = "DAXIB", type = "E", altitude_min = 15000 },
            }
        },
        ["DAXI1K"] = {
            name = "DAXI1K",
            runway = "RW31L",
            waypoints = {
                { name = "AA820", type = "P" },
                { name = "OBTOL", type = "P", altitude_min = 5000 },
                { name = "PUXUT", type = "E", altitude_max = 9000, speed = 250.0 },
                { name = "DAXIB", type = "E", altitude_min = 10000 },
            }
        },
        ["DAXI1P"] = {
            name = "DAXI1P",
            runway = "RW31R",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "TADBU", type = "P", altitude_min = 3500, speed = 230.0 },
                { name = "LOSID", type = "E", altitude_min = 5000 },
                { name = "DAXIB", type = "E", altitude_min = 10000 },
            }
        },
        ["KANI1N"] = {
            name = "KANI1N",
            runway = "RW31R",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "TADBU", type = "P", altitude_min = 3500 },
                { name = "MURSU", type = "E", altitude_max = 9000 },
                { name = "ITLIV", type = "E", altitude_min = 9000, speed = 230.0 },
                { name = "LONUP", type = "E", altitude_min = 10000 },
                { name = "AA827", type = "P", altitude_min = 11000 },
                { name = "IMTUP", type = "E", altitude_min = 15000 },
                { name = "KANIP", type = "E" },
            }
        },
        ["KANI2U"] = {
            name = "KANI2U",
            runway = "RW31L",
            waypoints = {
                { name = "AA820", type = "P" },
                { name = "OBTOL", type = "P", altitude_min = 5000 },
                { name = "KUVIN", type = "P" },
                { name = "OBMUK", type = "E", altitude_min = 7500 },
                { name = "AA824", type = "P", altitude_max = 9000, speed = 230.0 },
                { name = "MURSU", type = "E", altitude_min = 10000 },
                { name = "ITLIV", type = "E", altitude_min = 11000, speed = 250.0 },
                { name = "LONUP", type = "E", altitude_min = 12000 },
                { name = "AA827", type = "P" },
                { name = "IMTUP", type = "E", altitude_min = 15000 },
                { name = "KANIP", type = "E" },
            }
        },
        ["KANI3F"] = {
            name = "KANI3F",
            runway = "RW13L",
            waypoints = {
                { name = "", type = "", altitude_min = 500 },
                { name = "ULALA", type = "E" },
                { name = "AA834", type = "P", altitude_min = 4500, altitude_max = 7000, speed = 230.0 },
                { name = "KANIP", type = "E", altitude_min = 11000 },
            }
        },
        ["KANI3G"] = {
            name = "KANI3G",
            runway = "RW13R",
            waypoints = {
                { name = "ITKOV", type = "P", altitude_min = 4000 },
                { name = "AA839", type = "P", altitude_min = 5000, speed = 230.0 },
                { name = "ITREN", type = "E", altitude_max = 7000, speed = 230.0 },
                { name = "KANIP", type = "E", altitude_min = 11000 },
            }
        },
        ["KANI3P"] = {
            name = "KANI3P",
            runway = "RW31R",
            waypoints = {
                { name = "AA432", type = "P", altitude_min = 2200, speed = 220.0 },
                { name = "AA441", type = "P", altitude_min = 4000, speed = 220.0 },
                { name = "AA442", type = "P" },
                { name = "EMATI", type = "E" },
                { name = "IMTUP", type = "E", altitude_min = 15000 },
                { name = "KANIP", type = "E" },
            }
        },
        ["KANI4K"] = {
            name = "KANI4K",
            runway = "RW31L",
            waypoints = {
                { name = "AA820", type = "P" },
                { name = "OBTOL", type = "P", altitude_min = 5000 },
                { name = "KUVIN", type = "P", speed = 220.0 },
                { name = "MUVUM", type = "E" },
                { name = "AA825", type = "P", altitude_max = 9000 },
                { name = "LONUP", type = "E", altitude_min = 10000 },
                { name = "AA827", type = "P", altitude_min = 11000 },
                { name = "IMTUP", type = "E", altitude_min = 15000 },
                { name = "KANIP", type = "E" },
            }
        },
        ["LORI1F"] = {
            name = "LORI1F",
            runway = "RW13L",
            waypoints = {
                { name = "", type = "", altitude_min = 500 },
                { name = "AA836", type = "P", altitude_min = 4000, speed = 230.0 },
                { name = "PATAM", type = "E", altitude_min = 5000, altitude_max = 7000 },
                { name = "UKPAP", type = "E", altitude_max = 8000 },
                { name = "ITLIV", type = "E" },
                { name = "MURSU", type = "E" },
                { name = "LORID", type = "E" },
            }
        },
        ["LORI1G"] = {
            name = "LORI1G",
            runway = "RW13R",
            waypoints = {
                { name = "ITKOV", type = "P", altitude_min = 4000 },
                { name = "AA839", type = "P", altitude_min = 5000, speed = 230.0 },
                { name = "PEGEB", type = "E", speed = 230.0 },
                { name = "PATAM", type = "E", altitude_min = 5000, altitude_max = 7000 },
                { name = "UKPAP", type = "E", altitude_max = 8000 },
                { name = "ITLIV", type = "E" },
                { name = "MURSU", type = "E" },
                { name = "LORID", type = "E" },
            }
        },
        ["LORI1P"] = {
            name = "LORI1P",
            runway = "RW31R",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "TADBU", type = "P", altitude_min = 3500, speed = 230.0 },
                { name = "MURSU", type = "E", altitude_max = 9000 },
                { name = "LORID", type = "E" },
            }
        },
        ["LORI2K"] = {
            name = "LORI2K",
            runway = "RW31L",
            waypoints = {
                { name = "AA820", type = "P" },
                { name = "OBTOL", type = "P", altitude_min = 5000 },
                { name = "KUVIN", type = "P" },
                { name = "OBMUK", type = "E", altitude_min = 7500 },
                { name = "AA824", type = "P", altitude_max = 9000, speed = 230.0 },
                { name = "MURSU", type = "E", altitude_min = 10000 },
                { name = "LORID", type = "E" },
            }
        },
        ["MEKR1F"] = {
            name = "MEKR1F",
            runway = "RW13L",
            waypoints = {
                { name = "", type = "", altitude_min = 500 },
                { name = "ULALA", type = "E", speed = 230.0 },
                { name = "AA834", type = "P", altitude_min = 4500, altitude_max = 7000 },
                { name = "ITKOV", type = "P", altitude_min = 6000 },
                { name = "VEGIR", type = "E", speed = 230.0 },
                { name = "RUKOS", type = "E", altitude_max = 7000 },
                { name = "EGSUP", type = "E", altitude_min = 9000 },
                { name = "LAGVU", type = "E", altitude_min = 11000 },
                { name = "MEKRI", type = "E" },
            }
        },
        ["MEKR1G"] = {
            name = "MEKR1G",
            runway = "RW13R",
            waypoints = {
                { name = "ITKOV", type = "P", altitude_min = 4000 },
                { name = "VEGIR", type = "E", speed = 230.0 },
                { name = "RUKOS", type = "E", altitude_max = 7000 },
                { name = "EGSUP", type = "E", altitude_min = 9000 },
                { name = "LAGVU", type = "E", altitude_min = 11000 },
                { name = "MEKRI", type = "E" },
            }
        },
        ["MEKR1P"] = {
            name = "MEKR1P",
            runway = "RW31R",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "TADBU", type = "P", altitude_min = 3500, speed = 230.0 },
                { name = "LOSID", type = "E", altitude_min = 5000 },
                { name = "PUXUT", type = "E", altitude_max = 9000 },
                { name = "AA826", type = "P", altitude_max = 10000 },
                { name = "MEKRI", type = "E", altitude_min = 11000 },
            }
        },
        ["MEKR2K"] = {
            name = "MEKR2K",
            runway = "RW31L",
            waypoints = {
                { name = "AA820", type = "P" },
                { name = "MEPDO", type = "E", altitude_min = 4000, speed = 250.0 },
                { name = "AA822", type = "P", altitude_max = 6000 },
                { name = "ORPEP", type = "E" },
                { name = "AA823", type = "P", altitude_max = 10000 },
                { name = "MEKRI", type = "E", altitude_min = 11000 },
            }
        },
        ["ORNE1F"] = {
            name = "ORNE1F",
            runway = "RW13L",
            waypoints = {
                { name = "", type = "", altitude_min = 500 },
                { name = "ULALA", type = "E" },
                { name = "AA834", type = "P", altitude_min = 4500, altitude_max = 7000, speed = 230.0 },
                { name = "ORNEL", type = "E", altitude_min = 11000 },
            }
        },
        ["ORNE1G"] = {
            name = "ORNE1G",
            runway = "RW13R",
            waypoints = {
                { name = "ITKOV", type = "P", altitude_min = 4000 },
                { name = "AA839", type = "P", altitude_min = 5000, speed = 230.0 },
                { name = "ITREN", type = "E", altitude_max = 7000, speed = 230.0 },
                { name = "ORNEL", type = "E", altitude_min = 11000 },
            }
        },
        ["ORNE1P"] = {
            name = "ORNE1P",
            runway = "RW31R",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "TADBU", type = "P", altitude_min = 3500 },
                { name = "MURSU", type = "E", altitude_max = 9000 },
                { name = "ITLIV", type = "E", altitude_min = 9000, speed = 230.0 },
                { name = "LONUP", type = "E", altitude_min = 10000 },
                { name = "AA827", type = "P", altitude_min = 11000 },
                { name = "IMTUP", type = "E", altitude_min = 15000 },
                { name = "AA817", type = "P" },
                { name = "ORNEL", type = "E" },
            }
        },
        ["ORNE1U"] = {
            name = "ORNE1U",
            runway = "RW31L",
            waypoints = {
                { name = "AA820", type = "P" },
                { name = "OBTOL", type = "P", altitude_min = 5000 },
                { name = "KUVIN", type = "P", speed = 220.0 },
                { name = "MUVUM", type = "E" },
                { name = "AA825", type = "P", altitude_max = 9000 },
                { name = "LONUP", type = "E", altitude_min = 10000 },
                { name = "AA827", type = "P", altitude_min = 11000 },
                { name = "IMTUP", type = "E", altitude_min = 15000 },
                { name = "AA817", type = "P" },
                { name = "ORNEL", type = "E" },
            }
        },
        ["ORNE2K"] = {
            name = "ORNE2K",
            runway = "RW31L",
            waypoints = {
                { name = "AA820", type = "P" },
                { name = "OBTOL", type = "P", altitude_min = 5000 },
                { name = "KUVIN", type = "P" },
                { name = "OBMUK", type = "E", altitude_min = 7500 },
                { name = "AA824", type = "P", altitude_max = 9000, speed = 230.0 },
                { name = "MURSU", type = "E", altitude_min = 10000 },
                { name = "ITLIV", type = "E", altitude_min = 11000, speed = 250.0 },
                { name = "LONUP", type = "E", altitude_min = 12000 },
                { name = "AA827", type = "P" },
                { name = "IMTUP", type = "E", altitude_min = 15000 },
                { name = "AA817", type = "P" },
                { name = "ORNEL", type = "E" },
            }
        },
        ["TULO1F"] = {
            name = "TULO1F",
            runway = "RW13L",
            waypoints = {
                { name = "", type = "", altitude_min = 500 },
                { name = "AA836", type = "P", altitude_min = 4000, speed = 230.0 },
                { name = "PATAM", type = "E", altitude_min = 5000, altitude_max = 7000 },
                { name = "UKPAP", type = "E", altitude_max = 8000 },
                { name = "ITLIV", type = "E", altitude_min = 9500 },
                { name = "TULON", type = "E", altitude_min = 12000 },
            }
        },
        ["TULO1G"] = {
            name = "TULO1G",
            runway = "RW13R",
            waypoints = {
                { name = "ITKOV", type = "P", altitude_min = 4000 },
                { name = "AA839", type = "P", altitude_min = 5000, speed = 230.0 },
                { name = "PEGEB", type = "E", speed = 230.0 },
                { name = "PATAM", type = "E", altitude_min = 5000, altitude_max = 7000 },
                { name = "UKPAP", type = "E", altitude_max = 8000 },
                { name = "ITLIV", type = "E", altitude_min = 9500 },
                { name = "TULON", type = "E", altitude_min = 12000 },
            }
        },
        ["TULO1P"] = {
            name = "TULO1P",
            runway = "RW31R",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "TADBU", type = "P", altitude_min = 3500, speed = 230.0 },
                { name = "MURSU", type = "E", altitude_max = 9000 },
                { name = "TULON", type = "E", altitude_min = 12000 },
            }
        },
        ["TULO2K"] = {
            name = "TULO2K",
            runway = "RW31L",
            waypoints = {
                { name = "AA820", type = "P" },
                { name = "OBTOL", type = "P", altitude_min = 5000 },
                { name = "KUVIN", type = "P" },
                { name = "OBMUK", type = "E", altitude_min = 7500 },
                { name = "AA824", type = "P", altitude_max = 9000, speed = 230.0 },
                { name = "MURSU", type = "E", altitude_min = 10000 },
                { name = "TULON", type = "E", altitude_min = 12000 },
            }
        },
    },

    -- Процедуры STAR
    STAR = {
        ["ATUD2A"] = {
            name = "ATUD2A",
            runway = "RW13B",
            waypoints = {
                { name = "ATUDO", type = "OM", altitude_min = 12000, speed = 250.0 },
                { name = "TUMEX", type = "OM", altitude_min = 7000, altitude_max = 8000 },
                { name = "IVEPO", type = "OM" },
                { name = "SODEL", type = "OM", speed = 230.0 },
                { name = "OVOLA", type = "OM" },
                { name = "RIGIP", type = "OM", altitude_max = 5000, speed = 210.0 },
                { name = "AA568", type = "OM" },
                { name = "ORDAK", type = "OM", speed = 210.0 },
            }
        },
        ["ATUD2C"] = {
            name = "ATUD2C",
            runway = "RW31B",
            waypoints = {
                { name = "ATUDO", type = "OM", altitude_min = 12000, speed = 250.0 },
                { name = "ITUGO", type = "OM", altitude_max = 9000 },
                { name = "TONKI", type = "OM", altitude_max = 8000, speed = 230.0 },
                { name = "LOXIX", type = "OM" },
                { name = "AA524", type = "OM" },
                { name = "GISVU", type = "OM", altitude_max = 5000, speed = 210.0 },
                { name = "AA526", type = "OM" },
                { name = "PEGUM", type = "OM", speed = 210.0 },
            }
        },
        ["ATUD4B"] = {
            name = "ATUD4B",
            runway = "RW13B",
            waypoints = {
                { name = "ATUDO", type = "OM", altitude_min = 12000, speed = 250.0 },
                { name = "TUMEX", type = "OM", altitude_min = 7000, altitude_max = 8000 },
                { name = "IVEPO", type = "OM" },
                { name = "SODEL", type = "OM", speed = 230.0 },
                { name = "SODEL", type = "OM" },
            }
        },
        ["ATUD4D"] = {
            name = "ATUD4D",
            runway = "RW31B",
            waypoints = {
                { name = "ATUDO", type = "OM", altitude_min = 12000, speed = 250.0 },
                { name = "ITUGO", type = "OM", altitude_max = 9000 },
                { name = "TONKI", type = "OM", altitude_max = 8000, speed = 230.0 },
                { name = "LOXIX", type = "OM" },
                { name = "LOXIX", type = "OM" },
            }
        },
        ["ELOV2B"] = {
            name = "ELOV2B",
            runway = "RW13B",
            waypoints = {
                { name = "ELOVU", type = "OM", speed = 250.0 },
                { name = "MUTOP", type = "OM" },
                { name = "RIBUV", type = "OM", altitude_min = 5000, speed = 230.0 },
                { name = "SODEL", type = "OM" },
                { name = "SODEL", type = "OM" },
            }
        },
        ["ELOV2D"] = {
            name = "ELOV2D",
            runway = "RW31B",
            waypoints = {
                { name = "ELOVU", type = "OM", altitude_max = 15000, speed = 250.0 },
                { name = "MUVUM", type = "OM", altitude_min = 11000 },
                { name = "AA522", type = "OM", altitude_min = 10000 },
                { name = "ITUGO", type = "OM", altitude_max = 9000 },
                { name = "TONKI", type = "OM", altitude_max = 8000, speed = 230.0 },
                { name = "LOXIX", type = "OM" },
                { name = "LOXIX", type = "OM" },
            }
        },
        ["ELOV3A"] = {
            name = "ELOV3A",
            runway = "RW13B",
            waypoints = {
                { name = "ELOVU", type = "OM", speed = 250.0 },
                { name = "MUTOP", type = "OM" },
                { name = "RIBUV", type = "OM", altitude_min = 5000, speed = 230.0 },
                { name = "SODEL", type = "OM" },
                { name = "OVOLA", type = "OM" },
                { name = "RIGIP", type = "OM", altitude_max = 5000, speed = 210.0 },
                { name = "AA568", type = "OM" },
                { name = "ORDAK", type = "OM", speed = 210.0 },
            }
        },
        ["ELOV3C"] = {
            name = "ELOV3C",
            runway = "RW31B",
            waypoints = {
                { name = "ELOVU", type = "OM", altitude_max = 15000, speed = 250.0 },
                { name = "MUVUM", type = "OM", altitude_min = 11000 },
                { name = "AA522", type = "OM", altitude_min = 10000 },
                { name = "ITUGO", type = "OM", altitude_max = 9000 },
                { name = "TONKI", type = "OM", altitude_max = 8000, speed = 230.0 },
                { name = "LOXIX", type = "OM" },
                { name = "AA524", type = "OM" },
                { name = "GISVU", type = "OM", altitude_max = 5000, speed = 210.0 },
                { name = "AA526", type = "OM" },
                { name = "PEGUM", type = "OM", speed = 210.0 },
            }
        },
        ["EMER1B"] = {
            name = "EMER1B",
            runway = "RW13B",
            waypoints = {
                { name = "EMERU", type = "OM", altitude_max = 16000, speed = 250.0 },
                { name = "MUNPA", type = "OM", altitude_min = 10000 },
                { name = "RIDIB", type = "OM", altitude_min = 9000 },
                { name = "SISUG", type = "OM" },
                { name = "TUMEX", type = "OM", altitude_min = 7000, altitude_max = 8000 },
                { name = "IVEPO", type = "OM" },
                { name = "SODEL", type = "OM", speed = 230.0 },
                { name = "SODEL", type = "OM" },
            }
        },
        ["EMER2A"] = {
            name = "EMER2A",
            runway = "RW13B",
            waypoints = {
                { name = "EMERU", type = "OM", altitude_max = 16000, speed = 250.0 },
                { name = "MUNPA", type = "OM", altitude_min = 10000 },
                { name = "RIDIB", type = "OM", altitude_min = 9000 },
                { name = "SISUG", type = "OM" },
                { name = "TUMEX", type = "OM", altitude_min = 7000, altitude_max = 8000 },
                { name = "IVEPO", type = "OM" },
                { name = "SODEL", type = "OM", speed = 230.0 },
                { name = "OVOLA", type = "OM" },
                { name = "RIGIP", type = "OM", altitude_max = 5000, speed = 210.0 },
                { name = "AA568", type = "OM" },
                { name = "ORDAK", type = "OM", speed = 210.0 },
            }
        },
        ["EMER2D"] = {
            name = "EMER2D",
            runway = "RW31B",
            waypoints = {
                { name = "EMERU", type = "OM", altitude_max = 16000, speed = 250.0 },
                { name = "TUGVA", type = "OM", altitude_max = 10000 },
                { name = "TONKI", type = "OM", altitude_max = 8000, speed = 230.0 },
                { name = "LOXIX", type = "OM" },
                { name = "LOXIX", type = "OM" },
            }
        },
        ["EMER3C"] = {
            name = "EMER3C",
            runway = "RW31B",
            waypoints = {
                { name = "EMERU", type = "OM", altitude_max = 16000, speed = 250.0 },
                { name = "TUGVA", type = "OM", altitude_max = 10000 },
                { name = "TONKI", type = "OM", altitude_max = 8000, speed = 230.0 },
                { name = "LOXIX", type = "OM" },
                { name = "AA524", type = "OM" },
                { name = "GISVU", type = "OM", altitude_max = 5000, speed = 210.0 },
                { name = "AA526", type = "OM" },
                { name = "PEGUM", type = "OM", speed = 210.0 },
            }
        },
        ["GIDO1D"] = {
            name = "GIDO1D",
            runway = "RW31B",
            waypoints = {
                { name = "GIDOB", type = "OM", altitude_max = 15000, speed = 250.0 },
                { name = "ORGAD", type = "OM" },
                { name = "VEDEX", type = "OM", altitude_min = 11000 },
                { name = "ITUGO", type = "OM", altitude_max = 9000 },
                { name = "TONKI", type = "OM", altitude_max = 8000, speed = 230.0 },
                { name = "LOXIX", type = "OM" },
                { name = "LOXIX", type = "OM" },
            }
        },
        ["GIDO2B"] = {
            name = "GIDO2B",
            runway = "RW13B",
            waypoints = {
                { name = "GIDOB", type = "OM", altitude_max = 12000, speed = 250.0 },
                { name = "TOMDO", type = "OM", altitude_min = 8000, altitude_max = 10000 },
                { name = "RIBUV", type = "OM", altitude_min = 5000, speed = 230.0 },
                { name = "SODEL", type = "OM" },
                { name = "SODEL", type = "OM" },
            }
        },
        ["GIDO2C"] = {
            name = "GIDO2C",
            runway = "RW31B",
            waypoints = {
                { name = "GIDOB", type = "OM", altitude_max = 15000, speed = 250.0 },
                { name = "ORGAD", type = "OM" },
                { name = "VEDEX", type = "OM", altitude_min = 11000 },
                { name = "ITUGO", type = "OM", altitude_max = 9000 },
                { name = "TONKI", type = "OM", altitude_max = 8000, speed = 230.0 },
                { name = "LOXIX", type = "OM" },
                { name = "AA524", type = "OM" },
                { name = "GISVU", type = "OM", altitude_max = 5000, speed = 210.0 },
                { name = "AA526", type = "OM" },
                { name = "PEGUM", type = "OM", speed = 210.0 },
            }
        },
        ["GIDO2M"] = {
            name = "GIDO2M",
            runway = "RW31B",
            waypoints = {
                { name = "GIDOB", type = "OM", altitude_max = 15000, speed = 250.0 },
                { name = "ORGAD", type = "OM", altitude_min = 11000 },
                { name = "ORMED", type = "OM", altitude_min = 7000, altitude_max = 9000, speed = 230.0 },
                { name = "TAPTO", type = "OM" },
                { name = "TAPTO", type = "OM" },
            }
        },
        ["GIDO3A"] = {
            name = "GIDO3A",
            runway = "RW13B",
            waypoints = {
                { name = "GIDOB", type = "OM", altitude_max = 12000, speed = 250.0 },
                { name = "TOMDO", type = "OM", altitude_min = 8000, altitude_max = 10000 },
                { name = "RIBUV", type = "OM", altitude_min = 5000, speed = 230.0 },
                { name = "SODEL", type = "OM" },
                { name = "OVOLA", type = "OM" },
                { name = "RIGIP", type = "OM", altitude_max = 5000, speed = 210.0 },
                { name = "AA568", type = "OM" },
                { name = "ORDAK", type = "OM", speed = 210.0 },
            }
        },
        ["GIDO3J"] = {
            name = "GIDO3J",
            runway = "RW31B",
            waypoints = {
                { name = "GIDOB", type = "OM", altitude_max = 15000, speed = 250.0 },
                { name = "ORGAD", type = "OM", altitude_min = 11000 },
                { name = "ORMED", type = "OM", altitude_min = 7000, altitude_max = 9000, speed = 230.0 },
                { name = "TAPTO", type = "OM" },
                { name = "AA519", type = "OM" },
                { name = "BOSIG", type = "OM", speed = 210.0 },
                { name = "AA520", type = "OM", altitude_min = 6000 },
                { name = "ITREN", type = "OM", altitude_min = 5000, speed = 210.0 },
            }
        },
        ["NOBT3H"] = {
            name = "NOBT3H",
            runway = "RW13B",
            waypoints = {
                { name = "NOBTO", type = "OM", altitude_max = 15000, speed = 250.0 },
                { name = "SITIB", type = "OM" },
                { name = "PUVUT", type = "OM", altitude_min = 10000 },
                { name = "SISUG", type = "OM" },
                { name = "TUMEX", type = "OM", altitude_min = 7000, altitude_max = 8000 },
                { name = "IVEPO", type = "OM" },
                { name = "SODEL", type = "OM", speed = 230.0 },
                { name = "OVOLA", type = "OM" },
                { name = "RIGIP", type = "OM", altitude_max = 5000, speed = 210.0 },
                { name = "AA568", type = "OM" },
                { name = "ORDAK", type = "OM", speed = 210.0 },
            }
        },
        ["NOBT4J"] = {
            name = "NOBT4J",
            runway = "RW31B",
            waypoints = {
                { name = "NOBTO", type = "OM", altitude_min = 10000, altitude_max = 13000, speed = 250.0 },
                { name = "SITIB", type = "OM", speed = 230.0 },
                { name = "KITOX", type = "OM", altitude_max = 12000 },
                { name = "GEXOD", type = "OM", altitude_min = 6000, speed = 230.0 },
                { name = "LORUP", type = "OM", altitude_max = 9000 },
                { name = "LOXIX", type = "OM" },
                { name = "AA524", type = "OM" },
                { name = "GISVU", type = "OM", altitude_max = 5000, speed = 210.0 },
                { name = "AA526", type = "OM" },
                { name = "PEGUM", type = "OM", speed = 210.0 },
            }
        },
        ["NOBT6B"] = {
            name = "NOBT6B",
            runway = "RW13B",
            waypoints = {
                { name = "NOBTO", type = "OM", altitude_max = 15000, speed = 250.0 },
                { name = "SITIB", type = "OM" },
                { name = "PUVUT", type = "OM", altitude_min = 10000 },
                { name = "NOPNU", type = "OM", altitude_max = 9000 },
                { name = "OBVIK", type = "OM", altitude_min = 8000 },
                { name = "SIVOV", type = "OM", speed = 230.0 },
                { name = "SIVOV", type = "OM" },
            }
        },
        ["NOBT6D"] = {
            name = "NOBT6D",
            runway = "RW31B",
            waypoints = {
                { name = "NOBTO", type = "OM", altitude_min = 10000, altitude_max = 13000, speed = 250.0 },
                { name = "SITIB", type = "OM", speed = 230.0 },
                { name = "MERPU", type = "OM", altitude_min = 7000 },
                { name = "MERPU", type = "OM" },
            }
        },
        ["NOBT7A"] = {
            name = "NOBT7A",
            runway = "RW13B",
            waypoints = {
                { name = "NOBTO", type = "OM", altitude_max = 15000, speed = 250.0 },
                { name = "SITIB", type = "OM" },
                { name = "PUVUT", type = "OM", altitude_min = 10000 },
                { name = "NOPNU", type = "OM", altitude_max = 9000 },
                { name = "OBVIK", type = "OM", altitude_min = 8000 },
                { name = "SIVOV", type = "OM", speed = 230.0 },
                { name = "DEGVO", type = "OM" },
                { name = "PAXIK", type = "OM", speed = 210.0 },
                { name = "AA583", type = "OM", altitude_min = 6000 },
                { name = "IMSIG", type = "OM", altitude_min = 5000, speed = 210.0 },
            }
        },
        ["NOBT7C"] = {
            name = "NOBT7C",
            runway = "RW31B",
            waypoints = {
                { name = "NOBTO", type = "OM", altitude_min = 10000, altitude_max = 13000, speed = 250.0 },
                { name = "SITIB", type = "OM", speed = 230.0 },
                { name = "MERPU", type = "OM", altitude_min = 7000 },
                { name = "BOSIG", type = "OM", speed = 210.0 },
                { name = "AA520", type = "OM", altitude_min = 6000 },
                { name = "ITREN", type = "OM", altitude_min = 5000, speed = 210.0 },
            }
        },
        ["ROVO3H"] = {
            name = "ROVO3H",
            runway = "RW13B",
            waypoints = {
                { name = "ROVOS", type = "OM", altitude_max = 15000, speed = 250.0 },
                { name = "PUVUT", type = "OM", altitude_min = 10000 },
                { name = "NOPNU", type = "OM", altitude_max = 9000 },
                { name = "OBVIK", type = "OM", altitude_min = 8000 },
                { name = "SIVOV", type = "OM", speed = 230.0 },
                { name = "DEGVO", type = "OM" },
                { name = "PAXIK", type = "OM", speed = 210.0 },
                { name = "AA583", type = "OM", altitude_min = 6000 },
                { name = "IMSIG", type = "OM", altitude_min = 5000, speed = 210.0 },
            }
        },
        ["ROVO3J"] = {
            name = "ROVO3J",
            runway = "RW31B",
            waypoints = {
                { name = "ROVOS", type = "OM", altitude_min = 10000, altitude_max = 13000, speed = 250.0 },
                { name = "MERPU", type = "OM", altitude_min = 7000, speed = 230.0 },
                { name = "BOSIG", type = "OM", speed = 210.0 },
                { name = "AA520", type = "OM", altitude_min = 6000 },
                { name = "ITREN", type = "OM", altitude_min = 5000, speed = 210.0 },
            }
        },
        ["ROVO4B"] = {
            name = "ROVO4B",
            runway = "RW13B",
            waypoints = {
                { name = "ROVOS", type = "OM", altitude_max = 15000, speed = 250.0 },
                { name = "KITOX", type = "OM" },
                { name = "GEXOD", type = "OM" },
                { name = "LORUP", type = "OM" },
                { name = "SISUG", type = "OM" },
                { name = "TUMEX", type = "OM", altitude_min = 7000, altitude_max = 8000 },
                { name = "IVEPO", type = "OM" },
                { name = "SODEL", type = "OM", speed = 230.0 },
                { name = "SODEL", type = "OM" },
            }
        },
        ["ROVO5A"] = {
            name = "ROVO5A",
            runway = "RW13B",
            waypoints = {
                { name = "ROVOS", type = "OM", altitude_max = 15000, speed = 250.0 },
                { name = "KITOX", type = "OM" },
                { name = "GEXOD", type = "OM" },
                { name = "LORUP", type = "OM" },
                { name = "SISUG", type = "OM" },
                { name = "TUMEX", type = "OM", altitude_min = 7000, altitude_max = 8000 },
                { name = "IVEPO", type = "OM" },
                { name = "SODEL", type = "OM", speed = 230.0 },
                { name = "OVOLA", type = "OM" },
                { name = "RIGIP", type = "OM", altitude_max = 5000, speed = 210.0 },
                { name = "AA568", type = "OM" },
                { name = "ORDAK", type = "OM", speed = 210.0 },
            }
        },
        ["ROVO5D"] = {
            name = "ROVO5D",
            runway = "RW31B",
            waypoints = {
                { name = "ROVOS", type = "OM", altitude_min = 10000, altitude_max = 13000, speed = 250.0 },
                { name = "KITOX", type = "OM", altitude_max = 12000 },
                { name = "GEXOD", type = "OM", altitude_min = 6000, speed = 230.0 },
                { name = "LORUP", type = "OM", altitude_max = 9000 },
                { name = "LOXIX", type = "OM" },
                { name = "LOXIX", type = "OM" },
            }
        },
        ["ROVO6C"] = {
            name = "ROVO6C",
            runway = "RW31B",
            waypoints = {
                { name = "ROVOS", type = "OM", altitude_min = 10000, altitude_max = 13000, speed = 250.0 },
                { name = "KITOX", type = "OM", altitude_max = 12000 },
                { name = "GEXOD", type = "OM", altitude_min = 6000, speed = 230.0 },
                { name = "LORUP", type = "OM", altitude_max = 9000 },
                { name = "LOXIX", type = "OM" },
                { name = "AA524", type = "OM" },
                { name = "GISVU", type = "OM", altitude_max = 5000, speed = 210.0 },
                { name = "AA526", type = "OM" },
                { name = "PEGUM", type = "OM", speed = 210.0 },
            }
        },
        ["UKIL1B"] = {
            name = "UKIL1B",
            runway = "RW13B",
            waypoints = {
                { name = "UKILI", type = "OM", altitude_max = 12000, speed = 250.0 },
                { name = "PEKAX", type = "OM", altitude_max = 8000 },
                { name = "OTUTU", type = "OM", speed = 230.0 },
                { name = "SIVOV", type = "OM" },
                { name = "SIVOV", type = "OM" },
            }
        },
        ["UKIL2A"] = {
            name = "UKIL2A",
            runway = "RW13B",
            waypoints = {
                { name = "UKILI", type = "OM", altitude_max = 12000, speed = 250.0 },
                { name = "PEKAX", type = "OM", altitude_max = 8000 },
                { name = "OTUTU", type = "OM", speed = 230.0 },
                { name = "SIVOV", type = "OM", speed = 230.0 },
                { name = "DEGVO", type = "OM" },
                { name = "PAXIK", type = "OM", speed = 210.0 },
                { name = "AA583", type = "OM", altitude_min = 6000 },
                { name = "IMSIG", type = "OM", altitude_min = 5000, speed = 210.0 },
            }
        },
        ["UKIL2J"] = {
            name = "UKIL2J",
            runway = "RW31B",
            waypoints = {
                { name = "UKILI", type = "OM", altitude_max = 15000, speed = 250.0 },
                { name = "ORGAD", type = "OM" },
                { name = "VEDEX", type = "OM", altitude_min = 11000 },
                { name = "ITUGO", type = "OM", altitude_max = 9000 },
                { name = "TONKI", type = "OM", altitude_max = 8000, speed = 230.0 },
                { name = "LOXIX", type = "OM" },
                { name = "AA524", type = "OM" },
                { name = "GISVU", type = "OM", altitude_max = 5000, speed = 210.0 },
                { name = "AA526", type = "OM" },
                { name = "PEGUM", type = "OM", speed = 210.0 },
            }
        },
        ["UKIL3D"] = {
            name = "UKIL3D",
            runway = "RW31B",
            waypoints = {
                { name = "UKILI", type = "OM", altitude_max = 15000, speed = 250.0 },
                { name = "ORPEP", type = "OM", altitude_min = 12000 },
                { name = "AA530", type = "OM", altitude_min = 11000 },
                { name = "ORMED", type = "OM", altitude_min = 7000, altitude_max = 9000, speed = 230.0 },
                { name = "TAPTO", type = "OM" },
                { name = "TAPTO", type = "OM" },
            }
        },
        ["UKIL4C"] = {
            name = "UKIL4C",
            runway = "RW31B",
            waypoints = {
                { name = "UKILI", type = "OM", altitude_max = 15000, speed = 250.0 },
                { name = "ORPEP", type = "OM", altitude_min = 12000 },
                { name = "AA530", type = "OM", altitude_min = 11000 },
                { name = "ORMED", type = "OM", altitude_min = 7000, altitude_max = 9000, speed = 230.0 },
                { name = "TAPTO", type = "OM" },
                { name = "AA519", type = "OM" },
                { name = "BOSIG", type = "OM", speed = 210.0 },
                { name = "AA520", type = "OM", altitude_min = 6000 },
                { name = "ITREN", type = "OM", altitude_min = 5000, speed = 210.0 },
            }
        },
    },

    -- Процедуры захода на посадку
    APPROACH = {
        ["D13R"] = {
            name = "D13R",
            type = "A",
            runway = "D13R",
            waypoints = {
                { name = "ADV", transition = "ADV1", type = "OM", altitude_min = 4000 },
                { name = "ADV", transition = "ADV1", type = "OM", altitude_min = 2000 },
                { name = "RALDA", transition = "ADV1", type = "OM", altitude_min = 2000, speed = 200.0 },
                { name = "ADV", transition = "ADV2", type = "OM", altitude_min = 4000 },
                { name = "ADV", transition = "ADV2", type = "OM", altitude_min = 2000 },
                { name = "RALDA", transition = "ADV2", type = "OM", altitude_min = 2000 },
                { name = "RALDA", transition = "", type = "OM", altitude_min = 2000 },
                { name = "LOVIM", transition = "", type = "OM", altitude_min = 1700 },
                { name = "MD13R", transition = "", type = "OM" },
                { name = "ADV", transition = "", type = "OM" },
                { name = "ADV", transition = "", type = "OM" },
                { name = "ADV", transition = "", type = "OM" },
                { name = "ADV", transition = "", type = "OM" },
            }
        },
        ["D31L"] = {
            name = "D31L",
            type = "A",
            runway = "D31L",
            waypoints = {
                { name = "ADV", transition = "ADV1", type = "OM", altitude_min = 4000 },
                { name = "ADV", transition = "ADV1", type = "OM", altitude_min = 2000 },
                { name = "BOMOS", transition = "ADV1", type = "OM", altitude_min = 2000 },
                { name = "ADV", transition = "ADV2", type = "OM", altitude_min = 4000 },
                { name = "ADV", transition = "ADV2", type = "OM", altitude_min = 2000 },
                { name = "BOMOS", transition = "ADV2", type = "OM", altitude_min = 2000 },
                { name = "BOMOS", transition = "", type = "OM", altitude_min = 2000 },
                { name = "RADSO", transition = "", type = "OM", altitude_min = 1840 },
                { name = "30VOR", transition = "", type = "OM", altitude_min = 1204 },
                { name = "ADV", transition = "", type = "OM" },
                { name = "", transition = "", type = "", altitude_min = 490 },
                { name = "ADV", transition = "", type = "OM" },
                { name = "ADV", transition = "", type = "OM" },
                { name = "ADV", transition = "", type = "OM" },
            }
        },
        ["I13L"] = {
            name = "I13L",
            type = "A",
            runway = "I13L",
            waypoints = {
                { name = "IMSIG", transition = "IMSIG", type = "OM", altitude_min = 5000, speed = 210.0 },
                { name = "PUVOD", transition = "IMSIG", type = "OM" },
                { name = "ORDAK", transition = "ORDAK", type = "OM", speed = 210.0 },
                { name = "AA408", transition = "ORDAK", type = "OM" },
                { name = "PUVOD", transition = "ORDAK", type = "OM" },
                { name = "PUVOD", transition = "", type = "OM" },
                { name = "RESIG", transition = "", type = "OM" },
                { name = "RW13L", transition = "", type = "OM" },
                { name = "AA415", transition = "", type = "OM", speed = 210.0 },
                { name = "DASNU", transition = "", type = "OM", speed = 210.0 },
                { name = "ALSOV", transition = "", type = "OM", altitude_min = 4000, speed = 210.0 },
                { name = "ALSOV", transition = "", type = "OM", altitude_max = 6000, speed = 210.0 },
            }
        },
        ["I13R"] = {
            name = "I13R",
            type = "A",
            runway = "I13R",
            waypoints = {
                { name = "IMSIG", transition = "IMSIG", type = "OM", altitude_min = 5000, speed = 210.0 },
                { name = "AA428", transition = "IMSIG", type = "OM", altitude_min = 4000 },
                { name = "KINIL", transition = "IMSIG", type = "OM" },
                { name = "ORDAK", transition = "ORDAK", type = "OM", speed = 210.0 },
                { name = "KINIL", transition = "ORDAK", type = "OM" },
                { name = "KINIL", transition = "", type = "OM" },
                { name = "SOKOV", transition = "", type = "OM" },
                { name = "RW13R", transition = "", type = "OM" },
                { name = "ITKOV", transition = "", type = "OM", altitude_min = 4000, speed = 210.0 },
                { name = "ITKOV", transition = "", type = "OM", altitude_max = 6000, speed = 210.0 },
            }
        },
        ["I31L"] = {
            name = "I31L",
            type = "A",
            runway = "I31L",
            waypoints = {
                { name = "ITREN", transition = "ITREN", type = "OM", altitude_min = 5000, speed = 210.0 },
                { name = "AA430", transition = "ITREN", type = "OM", altitude_min = 4000 },
                { name = "LUBIK", transition = "ITREN", type = "OM" },
                { name = "PEGUM", transition = "PEGUM", type = "OM", speed = 210.0 },
                { name = "LUBIK", transition = "PEGUM", type = "OM" },
                { name = "LUBIK", transition = "", type = "OM" },
                { name = "EMOSU", transition = "", type = "OM" },
                { name = "RW31L", transition = "", type = "OM" },
                { name = "VEDEX", transition = "", type = "OM", speed = 210.0 },
                { name = "VUTOK", transition = "", type = "OM", altitude_min = 4000, speed = 210.0 },
                { name = "VUTOK", transition = "", type = "OM", altitude_max = 6000, speed = 210.0 },
            }
        },
        ["I31R"] = {
            name = "I31R",
            type = "A",
            runway = "I31R",
            waypoints = {
                { name = "ITREN", transition = "ITREN", type = "OM", altitude_min = 5000, speed = 210.0 },
                { name = "SETRU", transition = "ITREN", type = "OM" },
                { name = "PEGUM", transition = "PEGUM", type = "OM", speed = 210.0 },
                { name = "AA420", transition = "PEGUM", type = "OM" },
                { name = "SETRU", transition = "PEGUM", type = "OM" },
                { name = "SETRU", transition = "", type = "OM" },
                { name = "LOSOV", transition = "", type = "OM" },
                { name = "RW31R", transition = "", type = "OM" },
                { name = "AA416", transition = "", type = "OM", speed = 210.0 },
                { name = "TADBU", transition = "", type = "OM", speed = 210.0 },
                { name = "LUBUS", transition = "", type = "OM", altitude_min = 4000, speed = 210.0 },
                { name = "LUBUS", transition = "", type = "OM", altitude_max = 6000, speed = 210.0 },
            }
        },
        ["R13LY"] = {
            name = "R13LY",
            type = "A",
            runway = "R13LY",
            waypoints = {
                { name = "NOPNU", transition = "NOPNU", type = "OM", altitude_max = 9000 },
                { name = "AA623", transition = "NOPNU", type = "OM", altitude_min = 4000, speed = 210.0 },
                { name = "AA622", transition = "NOPNU", type = "OM", altitude_min = 4000 },
                { name = "AA621", transition = "NOPNU", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "MENDU", transition = "NOPNU", type = "OM", altitude_min = 1900 },
                { name = "PEKAX", transition = "PEKAX", type = "OM", altitude_max = 8000 },
                { name = "AA612", transition = "PEKAX", type = "OM", speed = 210.0 },
                { name = "AA611", transition = "PEKAX", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "MENDU", transition = "PEKAX", type = "OM", altitude_min = 1900 },
                { name = "RIBUV", transition = "RIBUV", type = "OM", speed = 230.0 },
                { name = "AA613", transition = "RIBUV", type = "OM" },
                { name = "AA601", transition = "RIBUV", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "MENDU", transition = "RIBUV", type = "OM", altitude_min = 1900 },
                { name = "RIDIB", transition = "RIDIB", type = "OM", altitude_min = 9000 },
                { name = "AA701", transition = "RIDIB", type = "OM", speed = 230.0 },
                { name = "ELEPO", transition = "RIDIB", type = "OM" },
                { name = "AA603", transition = "RIDIB", type = "OM", speed = 220.0 },
                { name = "AA602", transition = "RIDIB", type = "OM" },
                { name = "AA601", transition = "RIDIB", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "MENDU", transition = "RIDIB", type = "OM", altitude_min = 1900 },
                { name = "SISUG", transition = "SISUG", type = "OM" },
                { name = "ELEPO", transition = "SISUG", type = "OM" },
                { name = "AA603", transition = "SISUG", type = "OM", speed = 220.0 },
                { name = "AA602", transition = "SISUG", type = "OM" },
                { name = "AA601", transition = "SISUG", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "MENDU", transition = "SISUG", type = "OM", altitude_min = 1900 },
                { name = "TUMEX", transition = "TUMEX", type = "OM", altitude_min = 7000, altitude_max = 8000 },
                { name = "AA604", transition = "TUMEX", type = "OM", speed = 220.0 },
                { name = "AA603", transition = "TUMEX", type = "OM", speed = 220.0 },
                { name = "AA602", transition = "TUMEX", type = "OM" },
                { name = "AA601", transition = "TUMEX", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "MENDU", transition = "TUMEX", type = "OM", altitude_min = 1900 },
                { name = "MENDU", transition = "", type = "OM", altitude_min = 1900 },
                { name = "LOVUB", transition = "", type = "OM", speed = 160.0 },
                { name = "RW13L", transition = "", type = "OM" },
                { name = "AA415", transition = "", type = "OM", speed = 210.0 },
                { name = "AA631", transition = "", type = "OM", speed = 210.0 },
                { name = "DASNU", transition = "", type = "OM", speed = 210.0 },
                { name = "ALSOV", transition = "", type = "OM", altitude_min = 4000, speed = 210.0 },
                { name = "ALSOV", transition = "", type = "OM", altitude_max = 6000, speed = 210.0 },
            }
        },
        ["R13LZ"] = {
            name = "R13LZ",
            type = "A",
            runway = "R13LZ",
            waypoints = {
                { name = "IMSIG", transition = "IMSIG", type = "OM", altitude_min = 5000, speed = 210.0 },
                { name = "PUVOD", transition = "IMSIG", type = "OM" },
                { name = "ORDAK", transition = "ORDAK", type = "OM", speed = 210.0 },
                { name = "AA408", transition = "ORDAK", type = "OM" },
                { name = "PUVOD", transition = "ORDAK", type = "OM" },
                { name = "PUVOD", transition = "", type = "OM" },
                { name = "DERVA", transition = "", type = "OM" },
                { name = "RW13L", transition = "", type = "OM" },
                { name = "AA415", transition = "", type = "OM", speed = 210.0 },
                { name = "DASNU", transition = "", type = "OM", speed = 210.0 },
                { name = "ALSOV", transition = "", type = "OM", altitude_min = 4000, speed = 210.0 },
                { name = "ALSOV", transition = "", type = "OM", altitude_max = 6000, speed = 210.0 },
            }
        },
        ["R13RY"] = {
            name = "R13RY",
            type = "A",
            runway = "R13RY",
            waypoints = {
                { name = "NOPNU", transition = "NOPNU", type = "OM", altitude_max = 9000 },
                { name = "AA653", transition = "NOPNU", type = "OM", altitude_min = 4000, speed = 210.0 },
                { name = "AA652", transition = "NOPNU", type = "OM", altitude_min = 4000 },
                { name = "AA651", transition = "NOPNU", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "RETUX", transition = "NOPNU", type = "OM", altitude_min = 1900 },
                { name = "PEKAX", transition = "PEKAX", type = "OM", altitude_max = 8000 },
                { name = "AA672", transition = "PEKAX", type = "OM", speed = 210.0 },
                { name = "AA671", transition = "PEKAX", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "RETUX", transition = "PEKAX", type = "OM", altitude_min = 1900 },
                { name = "RIBUV", transition = "RIBUV", type = "OM", speed = 230.0 },
                { name = "AA673", transition = "RIBUV", type = "OM" },
                { name = "AA641", transition = "RIBUV", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "RETUX", transition = "RIBUV", type = "OM", altitude_min = 1900 },
                { name = "RIDIB", transition = "RIDIB", type = "OM", altitude_min = 9000 },
                { name = "AA701", transition = "RIDIB", type = "OM", speed = 230.0 },
                { name = "ELEPO", transition = "RIDIB", type = "OM" },
                { name = "AA643", transition = "RIDIB", type = "OM", speed = 220.0 },
                { name = "AA642", transition = "RIDIB", type = "OM" },
                { name = "AA641", transition = "RIDIB", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "RETUX", transition = "RIDIB", type = "OM", altitude_min = 1900 },
                { name = "SISUG", transition = "SISUG", type = "OM" },
                { name = "ELEPO", transition = "SISUG", type = "OM" },
                { name = "AA643", transition = "SISUG", type = "OM", speed = 220.0 },
                { name = "AA642", transition = "SISUG", type = "OM" },
                { name = "AA641", transition = "SISUG", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "RETUX", transition = "SISUG", type = "OM", altitude_min = 1900 },
                { name = "TUMEX", transition = "TUMEX", type = "OM", altitude_min = 7000, altitude_max = 8000 },
                { name = "AA644", transition = "TUMEX", type = "OM", speed = 220.0 },
                { name = "AA643", transition = "TUMEX", type = "OM", speed = 220.0 },
                { name = "AA642", transition = "TUMEX", type = "OM" },
                { name = "AA641", transition = "TUMEX", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "RETUX", transition = "TUMEX", type = "OM", altitude_min = 1900 },
                { name = "RETUX", transition = "", type = "OM", altitude_min = 1900 },
                { name = "ORSOB", transition = "", type = "OM", speed = 160.0 },
                { name = "RW13R", transition = "", type = "OM" },
                { name = "ITKOV", transition = "", type = "OM", altitude_min = 4000, speed = 210.0 },
                { name = "ITKOV", transition = "", type = "OM", altitude_max = 6000, speed = 210.0 },
            }
        },
        ["R13RZ"] = {
            name = "R13RZ",
            type = "A",
            runway = "R13RZ",
            waypoints = {
                { name = "IMSIG", transition = "IMSIG", type = "OM", altitude_min = 5000, speed = 210.0 },
                { name = "AA428", transition = "IMSIG", type = "OM", altitude_min = 4000 },
                { name = "KINIL", transition = "IMSIG", type = "OM" },
                { name = "ORDAK", transition = "ORDAK", type = "OM", speed = 210.0 },
                { name = "KINIL", transition = "ORDAK", type = "OM" },
                { name = "KINIL", transition = "", type = "OM" },
                { name = "ELEXU", transition = "", type = "OM" },
                { name = "RW13R", transition = "", type = "OM" },
                { name = "ITKOV", transition = "", type = "OM", altitude_min = 4000, speed = 210.0 },
                { name = "ITKOV", transition = "", type = "OM", altitude_max = 6000, speed = 210.0 },
            }
        },
        ["R31LY"] = {
            name = "R31LY",
            type = "A",
            runway = "R31LY",
            waypoints = {
                { name = "GEXOD", transition = "GEXOD", type = "OM", altitude_min = 6000, speed = 230.0 },
                { name = "AA772", transition = "GEXOD", type = "OM" },
                { name = "AA771", transition = "GEXOD", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "KUSOK", transition = "GEXOD", type = "OM", altitude_min = 1900 },
                { name = "ITUGO", transition = "ITUGO", type = "OM", altitude_max = 9000 },
                { name = "AA713", transition = "ITUGO", type = "OM", speed = 220.0 },
                { name = "AA712", transition = "ITUGO", type = "OM", altitude_min = 4000, speed = 220.0 },
                { name = "AA711", transition = "ITUGO", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "KUSOK", transition = "ITUGO", type = "OM", altitude_min = 1900 },
                { name = "MERPU", transition = "MERPU", type = "OM", altitude_min = 6500, speed = 230.0 },
                { name = "ITREN", transition = "MERPU", type = "OM", altitude_min = 5000 },
                { name = "AA771", transition = "MERPU", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "KUSOK", transition = "MERPU", type = "OM", altitude_min = 1900 },
                { name = "ORMED", transition = "ORMED", type = "OM", altitude_min = 7000, altitude_max = 9000, speed = 230.0 },
                { name = "AA723", transition = "ORMED", type = "OM", speed = 210.0 },
                { name = "AA722", transition = "ORMED", type = "OM" },
                { name = "AA721", transition = "ORMED", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "KUSOK", transition = "ORMED", type = "OM", altitude_min = 1900 },
                { name = "TUGVA", transition = "TUGVA", type = "OM", altitude_max = 10000 },
                { name = "AA712", transition = "TUGVA", type = "OM", altitude_min = 4000, speed = 220.0 },
                { name = "AA711", transition = "TUGVA", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "KUSOK", transition = "TUGVA", type = "OM", altitude_min = 1900 },
                { name = "KUSOK", transition = "", type = "OM", altitude_min = 1900 },
                { name = "KATIG", transition = "", type = "OM", speed = 160.0 },
                { name = "RW31L", transition = "", type = "OM" },
                { name = "VEDEX", transition = "", type = "OM", speed = 210.0 },
                { name = "VUTOK", transition = "", type = "OM", altitude_min = 4000, speed = 210.0 },
                { name = "VUTOK", transition = "", type = "OM", altitude_max = 6000, speed = 210.0 },
            }
        },
        ["R31LZ"] = {
            name = "R31LZ",
            type = "A",
            runway = "R31LZ",
            waypoints = {
                { name = "ITREN", transition = "ITREN", type = "OM", altitude_min = 5000, speed = 210.0 },
                { name = "AA430", transition = "ITREN", type = "OM", altitude_min = 4000 },
                { name = "LUBIK", transition = "ITREN", type = "OM" },
                { name = "PEGUM", transition = "PEGUM", type = "OM", speed = 210.0 },
                { name = "LUBIK", transition = "PEGUM", type = "OM" },
                { name = "LUBIK", transition = "", type = "OM" },
                { name = "ASMUP", transition = "", type = "OM" },
                { name = "RW31L", transition = "", type = "OM" },
                { name = "VEDEX", transition = "", type = "OM", speed = 210.0 },
                { name = "VUTOK", transition = "", type = "OM", altitude_min = 4000, speed = 210.0 },
                { name = "VUTOK", transition = "", type = "OM", altitude_max = 6000, speed = 210.0 },
            }
        },
        ["R31RY"] = {
            name = "R31RY",
            type = "A",
            runway = "R31RY",
            waypoints = {
                { name = "GEXOD", transition = "GEXOD", type = "OM", altitude_min = 6000, speed = 230.0 },
                { name = "AA762", transition = "GEXOD", type = "OM" },
                { name = "AA761", transition = "GEXOD", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "IVEGU", transition = "GEXOD", type = "OM", altitude_min = 1900 },
                { name = "ITUGO", transition = "ITUGO", type = "OM", altitude_max = 9000 },
                { name = "AA733", transition = "ITUGO", type = "OM", speed = 220.0 },
                { name = "AA732", transition = "ITUGO", type = "OM", altitude_min = 4000, speed = 220.0 },
                { name = "AA731", transition = "ITUGO", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "IVEGU", transition = "ITUGO", type = "OM", altitude_min = 1900 },
                { name = "MERPU", transition = "MERPU", type = "OM", altitude_min = 6500, speed = 230.0 },
                { name = "PEGUM", transition = "MERPU", type = "OM" },
                { name = "AA761", transition = "MERPU", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "IVEGU", transition = "MERPU", type = "OM", altitude_min = 1900 },
                { name = "ORMED", transition = "ORMED", type = "OM", altitude_min = 7000, altitude_max = 9000, speed = 230.0 },
                { name = "AA743", transition = "ORMED", type = "OM", speed = 220.0 },
                { name = "AA742", transition = "ORMED", type = "OM" },
                { name = "AA741", transition = "ORMED", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "IVEGU", transition = "ORMED", type = "OM", altitude_min = 1900 },
                { name = "TUGVA", transition = "TUGVA", type = "OM", altitude_max = 10000 },
                { name = "AA732", transition = "TUGVA", type = "OM", altitude_min = 4000, speed = 220.0 },
                { name = "AA731", transition = "TUGVA", type = "OM", altitude_min = 3000, speed = 180.0 },
                { name = "IVEGU", transition = "TUGVA", type = "OM", altitude_min = 1900 },
                { name = "IVEGU", transition = "", type = "OM", altitude_min = 1900 },
                { name = "RUDON", transition = "", type = "OM", speed = 160.0 },
                { name = "RW31R", transition = "", type = "OM" },
                { name = "AA416", transition = "", type = "OM", speed = 210.0 },
                { name = "AA751", transition = "", type = "OM", speed = 210.0 },
                { name = "TADBU", transition = "", type = "OM", speed = 210.0 },
                { name = "LUBUS", transition = "", type = "OM", altitude_min = 4000, speed = 210.0 },
                { name = "LUBUS", transition = "", type = "OM", altitude_max = 6000, speed = 210.0 },
            }
        },
        ["R31RZ"] = {
            name = "R31RZ",
            type = "A",
            runway = "R31RZ",
            waypoints = {
                { name = "ITREN", transition = "ITREN", type = "OM", altitude_min = 5000, speed = 210.0 },
                { name = "SETRU", transition = "ITREN", type = "OM" },
                { name = "PEGUM", transition = "PEGUM", type = "OM", speed = 210.0 },
                { name = "AA420", transition = "PEGUM", type = "OM" },
                { name = "SETRU", transition = "PEGUM", type = "OM" },
                { name = "SETRU", transition = "", type = "OM" },
                { name = "GIPNA", transition = "", type = "OM" },
                { name = "RW31R", transition = "", type = "OM" },
                { name = "AA416", transition = "", type = "OM", speed = 210.0 },
                { name = "TADBU", transition = "", type = "OM", speed = 210.0 },
                { name = "LUBUS", transition = "", type = "OM", altitude_min = 4000, speed = 210.0 },
                { name = "LUBUS", transition = "", type = "OM", altitude_max = 6000, speed = 210.0 },
            }
        },
    },

    -- Частоты
    Frequencies = {
        TOWER = 118.0,
        APPROACH = 121.0,
        DEPARTURE = 125.0,
        GROUND = 121.7,
        ATIS = 126.0,
    }
}

return AirportData
