local AirportData = {
    -- Метаданные аэропорта
    Metadata = {
        ICAO = "OMDW",
        Name = "OMDW Airport",
        Elevation = 0,
        MagVar = 0,
        Region = "PersianGulf"
    },

    -- Путевые точки
    Waypoints = {
        ["DW426"] = { lat = 25.443722222, lon = 55.003305556, type = "OMDW" },
        ["PUVAL"] = { lat = 25.599444444, lon = 55.716111111, type = "ENRT" },
        ["MISOL"] = { lat = 24.894861111, lon = 54.451972222, type = "OMDW" },
        ["SERSA"] = { lat = 25.329166667, lon = 55.521666667, type = "ENRT" },
        ["DW661"] = { lat = 24.956333333, lon = 55.053027778, type = "OMDW" },
        ["GIDIS"] = { lat = 24.6, lon = 55.933333333, type = "ENRT" },
        ["NOLSU"] = { lat = 25.213333333, lon = 56.127166667, type = "ENRT" },
        ["TOVLA"] = { lat = 24.972361111, lon = 54.709166667, type = "OMDW" },
        ["SINPU"] = { lat = 24.667055556, lon = 55.597111111, type = "OMDW" },
        ["DW406"] = { lat = 24.957527778, lon = 55.227694444, type = "OMDW" },
        ["EF853"] = { lat = 24.855416667, lon = 55.023388889, type = "OMDW" },
        ["GINLA"] = { lat = 25.140833333, lon = 54.927222222, type = "ENRT" },
        ["DW459"] = { lat = 24.818472222, lon = 55.475555556, type = "OMDW" },
        ["EF671"] = { lat = 25.011805556, lon = 54.896888889, type = "OMDW" },
        ["DW400"] = { lat = 52.971580556, lon = 9.163986111, type = "EDDW" },
        ["SIBVA"] = { lat = 24.769027778, lon = 55.214972222, type = "OMDW" },
        ["DW423"] = { lat = 24.886083333, lon = 55.180138889, type = "OMDW" },
        ["DW456"] = { lat = 24.748055556, lon = 55.428888889, type = "OMDW" },
        ["DETGU"] = { lat = 25.439972222, lon = 55.601277778, type = "ENRT" },
        ["GERUL"] = { lat = 25.000388889, lon = 54.445666667, type = "ENRT" },
        ["EF813"] = { lat = 24.813972222, lon = 55.254861111, type = "OMDW" },
        ["LOPAP"] = { lat = 25.197805556, lon = 54.764861111, type = "ENRT" },
        ["DW467"] = { lat = 25.241583333, lon = 55.055333333, type = "OMDW" },
        ["DATOB"] = { lat = 25.514722222, lon = 54.782472222, type = "ENRT" },
        ["MIROT"] = { lat = 25.102444444, lon = 54.513555556, type = "ENRT" },
        ["LADMO"] = { lat = 25.016916667, lon = 54.943194444, type = "OMDW" },
        ["DW458"] = { lat = 24.817222222, lon = 55.651861111, type = "ENRT" },
        ["DW552"] = { lat = 53.31925, lon = -5.856583333, type = "EIDW" },
        ["ALRAR"] = { lat = 25.682833333, lon = 55.030388889, type = "ENRT" },
        ["EF670"] = { lat = 24.962694444, lon = 54.864277778, type = "OMDW" },
        ["DW475"] = { lat = 25.106277778, lon = 55.808583333, type = "OMDW" },
        ["DW761"] = { lat = 24.838277778, lon = 55.266416667, type = "OMDW" },
        ["NITRI"] = { lat = 25.034305556, lon = 54.911805556, type = "OMDW" },
        ["KUKPO"] = { lat = 24.568583333, lon = 55.347277778, type = "OMDW" },
        ["EF851"] = { lat = 24.890305556, lon = 55.117972222, type = "OMDW" },
        ["DW416"] = { lat = 24.657861111, lon = 55.415222222, type = "OMDW" },
        ["IVOPU"] = { lat = 24.928111111, lon = 54.927055556, type = "OMDW" },
        ["DW452"] = { lat = 24.821, lon = 55.297638889, type = "OMDW" },
        ["DW473"] = { lat = 24.892444444, lon = 55.345222222, type = "OMDW" },
        ["OBROG"] = { lat = 25.668277778, lon = 55.451416667, type = "ENRT" },
        ["EF673"] = { lat = 24.843944444, lon = 55.200722222, type = "OMDW" },
        ["LORID"] = { lat = 24.93125, lon = 54.651138889, type = "ENRT" },
        ["EF801"] = { lat = 24.843694444, lon = 55.201194444, type = "OMDW" },
        ["DW474"] = { lat = 25.064833333, lon = 55.685888889, type = "OMDW" },
        ["RAPMO"] = { lat = 24.941694444, lon = 55.698638889, type = "ENRT" },
        ["SOBOB"] = { lat = 24.67125, lon = 55.390888889, type = "ENRT" },
        ["ANVIX"] = { lat = -1.743947222, lon = 53.560097222, type = "ENRT" },
        ["IVOXI"] = { lat = 25.211, lon = 55.420305556, type = "ENRT" },
        ["EF803"] = { lat = 24.690555556, lon = 55.390805556, type = "OMDW" },
        ["EF866"] = { lat = 24.810444444, lon = 55.261194444, type = "OMDW" },
        ["DW427"] = { lat = 25.087305556, lon = 55.314472222, type = "OMDW" },
        ["KIRUK"] = { lat = 24.966333333, lon = 55.035055556, type = "OMDW" },
        ["DAVMO"] = { lat = 25.8575, lon = 55.65, type = "ENRT" },
        ["EF802"] = { lat = 24.7725, lon = 55.243333333, type = "OMDW" },
        ["REVUL"] = { lat = 24.794861111, lon = 55.344694444, type = "OMDW" },
        ["KIXOG"] = { lat = 25.402583333, lon = 54.718833333, type = "ENRT" },
        ["EF871"] = { lat = 24.772388889, lon = 55.329861111, type = "OMDW" },
        ["DW460"] = { lat = 24.866277778, lon = 55.392305556, type = "OMDW" },
        ["EMERU"] = { lat = 24.808055556, lon = 55.050833333, type = "ENRT" },
        ["EF855"] = { lat = 24.862027778, lon = 55.289972222, type = "OMDW" },
        ["DW479"] = { lat = 24.766305556, lon = 55.487555556, type = "OMDW" },
        ["GONVI"] = { lat = 25.711055556, lon = 54.941805556, type = "ENRT" },
        ["PUSVO"] = { lat = 24.999666667, lon = 54.974611111, type = "OMDW" },
        ["DW660"] = { lat = 24.960666667, lon = 55.045194444, type = "OMDW" },
        ["LOVEM"] = { lat = 25.445944444, lon = 55.244555556, type = "ENRT" },
        ["UMAMI"] = { lat = 24.853805556, lon = 56.039805556, type = "ENRT" },
        ["DEDAX"] = { lat = 24.814722222, lon = 55.132777778, type = "OMDW" },
        ["ORPAT"] = { lat = 24.878944444, lon = 55.016138889, type = "OMDW" },
        ["RIDAP"] = { lat = 25.431583333, lon = 54.617, type = "ENRT" },
        ["IVILI"] = { lat = 25.280138889, lon = 54.746388889, type = "ENRT" },
        ["KUTLI"] = { lat = 24.86425, lon = 54.938333333, type = "ENRT" },
        ["EF854"] = { lat = 24.799777778, lon = 55.124222222, type = "OMDW" },
        ["MITIX"] = { lat = 25.296222222, lon = 55.124916667, type = "ENRT" },
        ["DW425"] = { lat = 24.804972222, lon = 55.821972222, type = "OMDW" },
        ["EF872"] = { lat = 24.846888889, lon = 55.090138889, type = "OMDW" },
        ["ULADO"] = { lat = 25.02, lon = 55.553638889, type = "ENRT" },
        ["NABIX"] = { lat = 25.211416667, lon = 54.529805556, type = "ENRT" },
        ["IMGIL"] = { lat = 24.97025, lon = 55.407416667, type = "OMDW" },
        ["PEBER"] = { lat = 24.741, lon = 55.386416667, type = "OMDW" },
        ["ORGUR"] = { lat = 25.103583333, lon = 54.785972222, type = "ENRT" },
        ["TATMO"] = { lat = 24.954, lon = 54.879416667, type = "OMDW" },
        ["ELOVU"] = { lat = 24.955916667, lon = 54.338194444, type = "ENRT" },
        ["EF672"] = { lat = 24.977194444, lon = 54.959666667, type = "OMDW" },
        ["LOPUV"] = { lat = 24.841972222, lon = 55.849111111, type = "ENRT" },
        ["SEVNU"] = { lat = 24.769166667, lon = 55.215, type = "OMDW" },
        ["EF869"] = { lat = 24.689166667, lon = 55.479694444, type = "OMDW" },
        ["RERAG"] = { lat = 24.666944444, lon = 55.833583333, type = "OMDW" },
        ["EF667"] = { lat = 24.92225, lon = 55.059166667, type = "OMDW" },
        ["DW760"] = { lat = 24.834083333, lon = 55.273972222, type = "OMDW" },
        ["XARTA"] = { lat = 25.025861111, lon = 54.927222222, type = "ENRT" },
        ["DW465"] = { lat = 24.860138889, lon = 55.050333333, type = "OMDW" },
        ["EF852"] = { lat = 24.883777778, lon = 55.042972222, type = "OMDW" },
        ["UKSUL"] = { lat = 24.742777778, lon = 55.438611111, type = "OMDW" },
        ["ODGAK"] = { lat = 24.723361111, lon = 55.297222222, type = "OMDW" },
        ["EF868"] = { lat = 24.889472222, lon = 55.118444444, type = "OMDW" },
        ["GEXIK"] = { lat = 24.775861111, lon = 55.378861111, type = "OMDW" },
        ["DW478"] = { lat = 24.961222222, lon = 55.147472222, type = "OMDW" },
        ["EF870"] = { lat = 24.691916667, lon = 55.353694444, type = "OMDW" },
        ["SENPA"] = { lat = 25.333222222, lon = 54.53625, type = "ENRT" },
        ["DW412"] = { lat = 52.951652778, lon = 8.305175, type = "EDDW" },
        ["DW466"] = { lat = 24.917583333, lon = 55.265055556, type = "OMDW" },
        ["EF856"] = { lat = 25.043083333, lon = 54.745805556, type = "OMDW" },
        ["DW422"] = { lat = 24.897222222, lon = 55.972555556, type = "OMDW" },
    },

    -- Данные ВПП
    Runways = {
        ["RW12"] = {
            heading = 120,
            length = 0,
            width = 0,
            threshold = { lat = 24.907149999999998, lon = 55.142069444444445 },
            end = { lat = 24.907149999999998, lon = 55.142069444444445 }
        },
        ["RW13"] = {
            heading = 130,
            length = 0.0,
            width = 0,
            threshold = { lat = 24.869972222222223, lon = 55.153725 },
            end = { lat = 24.869972222222223, lon = 55.153725 }
        },
        ["RW30"] = {
            heading = 300,
            length = 0,
            width = 0,
            threshold = { lat = 24.88607777777778, lon = 55.18015 },
            end = { lat = 24.88607777777778, lon = 55.18015 }
        },
        ["RW31"] = {
            heading = 310,
            length = 0.0,
            width = 0,
            threshold = { lat = 24.862772222222222, lon = 55.166736111111106 },
            end = { lat = 24.862772222222222, lon = 55.166736111111106 }
        },
    },

    -- Процедуры SID
    SID = {
        ["ANVI1P"] = {
            name = "ANVI1P",
            runway = "RW31",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "EF851", type = "P" },
                { name = "EF852", type = "P", speed = 130.0 },
                { name = "EF853", type = "P", speed = 130.0 },
                { name = "EF854", type = "P", speed = 220.0 },
                { name = "EF855", type = "P", altitude_min = 7000 },
                { name = "IMGIL", type = "P", altitude_min = 10000 },
                { name = "ULADO", type = "E", altitude_min = 11000 },
                { name = "RAPMO", type = "E", altitude_min = 13000 },
                { name = "LOPUV", type = "E" },
                { name = "ANVIX", type = "E" },
            }
        },
        ["ANVI2N"] = {
            name = "ANVI2N",
            runway = "RW13",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "EF801", type = "P" },
                { name = "EF802", type = "P" },
                { name = "EF803", type = "P" },
                { name = "DW456", type = "P", altitude_min = 5000, speed = 220.0 },
                { name = "DW479", type = "P", altitude_min = 6000 },
                { name = "DW458", type = "E" },
                { name = "LOPUV", type = "E" },
                { name = "ANVIX", type = "E", altitude_min = 10000 },
            }
        },
        ["ANVI4L"] = {
            name = "ANVI4L",
            runway = "RW30",
            waypoints = {
                { name = "", type = "", altitude_min = 520 },
                { name = "KIRUK", type = "P", altitude_min = 2000 },
                { name = "DW552", type = "P", altitude_min = 3000 },
                { name = "DW465", type = "P", altitude_min = 4000, speed = 220.0 },
                { name = "DW423", type = "P" },
                { name = "DW466", type = "P", altitude_min = 7000 },
                { name = "IMGIL", type = "P", altitude_min = 10000 },
                { name = "ULADO", type = "E", altitude_min = 11000 },
                { name = "RAPMO", type = "E", altitude_min = 13000 },
                { name = "LOPUV", type = "E" },
                { name = "ANVIX", type = "E" },
            }
        },
        ["ANVI6J"] = {
            name = "ANVI6J",
            runway = "RW12",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "DW452", type = "P", altitude_min = 2000 },
                { name = "DW456", type = "P", altitude_min = 5000, speed = 220.0 },
                { name = "DW479", type = "P", altitude_min = 6000 },
                { name = "DW458", type = "E" },
                { name = "LOPUV", type = "E" },
                { name = "ANVIX", type = "E", altitude_min = 10000 },
            }
        },
        ["DAVM4L"] = {
            name = "DAVM4L",
            runway = "RW30",
            waypoints = {
                { name = "", type = "", altitude_min = 520 },
                { name = "KIRUK", type = "P", altitude_min = 2000 },
                { name = "XARTA", type = "E", speed = 220.0 },
                { name = "GINLA", type = "E" },
                { name = "DW467", type = "P", altitude_min = 10000 },
                { name = "MITIX", type = "E", altitude_min = 11000 },
                { name = "LOVEM", type = "E", altitude_min = 15000 },
                { name = "OBROG", type = "E" },
                { name = "DAVMO", type = "E" },
            }
        },
        ["DAVM5J"] = {
            name = "DAVM5J",
            runway = "RW12",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "DW452", type = "P", altitude_min = 2000 },
                { name = "DW456", type = "P", altitude_min = 5000, speed = 220.0 },
                { name = "DW459", type = "P", altitude_min = 6000 },
                { name = "DW460", type = "P", altitude_min = 7000, speed = 220.0 },
                { name = "DW473", type = "P" },
                { name = "DW406", type = "P" },
                { name = "DW478", type = "P" },
                { name = "KIRUK", type = "P", altitude_min = 7000 },
                { name = "XARTA", type = "E", altitude_min = 8000 },
                { name = "GINLA", type = "E", altitude_min = 10000 },
                { name = "DW467", type = "P", altitude_min = 12000 },
                { name = "MITIX", type = "E", altitude_min = 13000 },
                { name = "LOVEM", type = "E", altitude_min = 15000 },
                { name = "OBROG", type = "E" },
                { name = "DAVMO", type = "E" },
            }
        },
        ["EMER1L"] = {
            name = "EMER1L",
            runway = "RW30",
            waypoints = {
                { name = "", type = "", altitude_min = 520 },
                { name = "KIRUK", type = "P", altitude_min = 2000 },
                { name = "DW552", type = "P", altitude_min = 3000 },
                { name = "DW465", type = "P", altitude_min = 4000, speed = 220.0 },
                { name = "EMERU", type = "E" },
            }
        },
        ["EMER3J"] = {
            name = "EMER3J",
            runway = "RW12",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "DW452", type = "P", altitude_min = 2000 },
                { name = "DW456", type = "P", altitude_min = 5000, speed = 220.0 },
                { name = "DW459", type = "P", altitude_min = 6000 },
                { name = "DW460", type = "P", altitude_min = 7000, speed = 220.0 },
                { name = "DW473", type = "P" },
                { name = "DW406", type = "P" },
                { name = "DW478", type = "P" },
                { name = "EMERU", type = "E" },
            }
        },
        ["KUTL3L"] = {
            name = "KUTL3L",
            runway = "RW30",
            waypoints = {
                { name = "", type = "", altitude_min = 520 },
                { name = "KIRUK", type = "P", altitude_min = 2000 },
                { name = "XARTA", type = "E", speed = 220.0 },
                { name = "TATMO", type = "P", speed = 220.0 },
                { name = "KUTLI", type = "E", altitude_min = 8000 },
            }
        },
        ["KUTL4J"] = {
            name = "KUTL4J",
            runway = "RW12",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "DW452", type = "P", altitude_min = 2000 },
                { name = "DW456", type = "P", altitude_min = 5000, speed = 220.0 },
                { name = "DW459", type = "P", altitude_min = 6000 },
                { name = "DW460", type = "P", altitude_min = 7000, speed = 220.0 },
                { name = "DW473", type = "P" },
                { name = "DW406", type = "P" },
                { name = "DW478", type = "P" },
                { name = "KIRUK", type = "P", altitude_min = 7000 },
                { name = "KUTLI", type = "E", altitude_min = 8000 },
            }
        },
        ["MIRO1N"] = {
            name = "MIRO1N",
            runway = "RW13",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "EF801", type = "P" },
                { name = "EF802", type = "P" },
                { name = "EF803", type = "P" },
                { name = "DW456", type = "P", altitude_min = 5000, speed = 220.0 },
                { name = "DW459", type = "P", altitude_min = 6000 },
                { name = "DW460", type = "P", altitude_min = 7000 },
                { name = "DW473", type = "P" },
                { name = "DW406", type = "P" },
                { name = "DW478", type = "P" },
                { name = "KIRUK", type = "P", altitude_min = 7000 },
                { name = "XARTA", type = "E", altitude_min = 8000 },
                { name = "DW412", type = "P" },
                { name = "ORGUR", type = "E" },
                { name = "MIROT", type = "E" },
            }
        },
        ["MIRO1P"] = {
            name = "MIRO1P",
            runway = "RW31",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "EF851", type = "P" },
                { name = "EF852", type = "P", speed = 130.0 },
                { name = "DW552", type = "P" },
                { name = "TATMO", type = "P", speed = 220.0 },
                { name = "EF856", type = "P" },
                { name = "MIROT", type = "E" },
            }
        },
        ["MIRO3L"] = {
            name = "MIRO3L",
            runway = "RW30",
            waypoints = {
                { name = "", type = "", altitude_min = 520 },
                { name = "KIRUK", type = "P", altitude_min = 2000 },
                { name = "XARTA", type = "E", speed = 220.0 },
                { name = "ORGUR", type = "E" },
                { name = "MIROT", type = "E" },
            }
        },
        ["MIRO4J"] = {
            name = "MIRO4J",
            runway = "RW12",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "DW452", type = "P", altitude_min = 2000 },
                { name = "DW456", type = "P", altitude_min = 5000, speed = 220.0 },
                { name = "DW459", type = "P", altitude_min = 6000 },
                { name = "DW460", type = "P", altitude_min = 7000, speed = 220.0 },
                { name = "DW473", type = "P" },
                { name = "DW406", type = "P" },
                { name = "DW478", type = "P" },
                { name = "KIRUK", type = "P", altitude_min = 7000 },
                { name = "XARTA", type = "E", altitude_min = 8000 },
                { name = "DW412", type = "P" },
                { name = "ORGUR", type = "E" },
                { name = "MIROT", type = "E" },
            }
        },
        ["NABI1N"] = {
            name = "NABI1N",
            runway = "RW13",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "EF801", type = "P" },
                { name = "EF802", type = "P" },
                { name = "EF803", type = "P" },
                { name = "DW456", type = "P", altitude_min = 5000, speed = 220.0 },
                { name = "DW459", type = "P", altitude_min = 6000 },
                { name = "DW460", type = "P", altitude_min = 7000 },
                { name = "DW473", type = "P" },
                { name = "DW406", type = "P" },
                { name = "DW478", type = "P" },
                { name = "KIRUK", type = "P", altitude_min = 7000 },
                { name = "XARTA", type = "E", altitude_min = 8000 },
                { name = "DW412", type = "P" },
                { name = "ORGUR", type = "E" },
                { name = "NABIX", type = "E" },
            }
        },
        ["NABI1P"] = {
            name = "NABI1P",
            runway = "RW31",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "EF851", type = "P" },
                { name = "EF852", type = "P", speed = 130.0 },
                { name = "DW552", type = "P" },
                { name = "TATMO", type = "P", speed = 220.0 },
                { name = "EF856", type = "P" },
                { name = "NABIX", type = "E" },
            }
        },
        ["NABI3L"] = {
            name = "NABI3L",
            runway = "RW30",
            waypoints = {
                { name = "", type = "", altitude_min = 520 },
                { name = "KIRUK", type = "P", altitude_min = 2000 },
                { name = "XARTA", type = "E", speed = 220.0 },
                { name = "ORGUR", type = "E" },
                { name = "NABIX", type = "E" },
            }
        },
        ["NABI4J"] = {
            name = "NABI4J",
            runway = "RW12",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "DW452", type = "P", altitude_min = 2000 },
                { name = "DW456", type = "P", altitude_min = 5000, speed = 220.0 },
                { name = "DW459", type = "P", altitude_min = 6000 },
                { name = "DW460", type = "P", altitude_min = 7000, speed = 220.0 },
                { name = "DW473", type = "P" },
                { name = "DW406", type = "P" },
                { name = "DW478", type = "P" },
                { name = "KIRUK", type = "P", altitude_min = 7000 },
                { name = "XARTA", type = "E", altitude_min = 8000 },
                { name = "DW412", type = "P" },
                { name = "ORGUR", type = "E" },
                { name = "NABIX", type = "E" },
            }
        },
        ["NOLS3J"] = {
            name = "NOLS3J",
            runway = "RW12",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "DW452", type = "P", altitude_min = 2000 },
                { name = "DW456", type = "P", altitude_min = 5000, speed = 220.0 },
                { name = "DW459", type = "P", altitude_min = 6000 },
                { name = "DW460", type = "P", altitude_min = 7000, speed = 220.0 },
                { name = "IMGIL", type = "P", altitude_min = 9000 },
                { name = "ULADO", type = "E", altitude_min = 11000 },
                { name = "DW474", type = "P" },
                { name = "DW475", type = "P", altitude_min = 12000 },
                { name = "NOLSU", type = "E", altitude_min = 15000 },
            }
        },
        ["NOLS3L"] = {
            name = "NOLS3L",
            runway = "RW30",
            waypoints = {
                { name = "", type = "", altitude_min = 520 },
                { name = "KIRUK", type = "P", altitude_min = 2000 },
                { name = "DW552", type = "P", altitude_min = 3000 },
                { name = "DW465", type = "P", altitude_min = 4000, speed = 220.0 },
                { name = "DW423", type = "P" },
                { name = "DW466", type = "P", altitude_min = 7000 },
                { name = "IMGIL", type = "P", altitude_min = 10000 },
                { name = "ULADO", type = "E", altitude_min = 11000 },
                { name = "DW474", type = "P" },
                { name = "DW475", type = "P", altitude_min = 12000 },
                { name = "NOLSU", type = "E", altitude_min = 15000 },
            }
        },
        ["RIDA3L"] = {
            name = "RIDA3L",
            runway = "RW30",
            waypoints = {
                { name = "", type = "", altitude_min = 520 },
                { name = "KIRUK", type = "P", altitude_min = 2000 },
                { name = "XARTA", type = "E", speed = 220.0 },
                { name = "ORGUR", type = "E" },
                { name = "LOPAP", type = "E" },
                { name = "IVILI", type = "E" },
                { name = "KIXOG", type = "E" },
                { name = "RIDAP", type = "E" },
            }
        },
        ["RIDA4J"] = {
            name = "RIDA4J",
            runway = "RW12",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "DW452", type = "P", altitude_min = 2000 },
                { name = "DW456", type = "P", altitude_min = 5000, speed = 220.0 },
                { name = "DW459", type = "P", altitude_min = 6000 },
                { name = "DW460", type = "P", altitude_min = 7000, speed = 220.0 },
                { name = "DW473", type = "P" },
                { name = "DW406", type = "P" },
                { name = "DW478", type = "P" },
                { name = "KIRUK", type = "P", altitude_min = 7000 },
                { name = "XARTA", type = "E", altitude_min = 8000 },
                { name = "DW412", type = "P" },
                { name = "ORGUR", type = "E" },
                { name = "LOPAP", type = "E" },
                { name = "IVILI", type = "E" },
                { name = "KIXOG", type = "E" },
                { name = "RIDAP", type = "E" },
            }
        },
        ["SENP3L"] = {
            name = "SENP3L",
            runway = "RW30",
            waypoints = {
                { name = "", type = "", altitude_min = 520 },
                { name = "KIRUK", type = "P", altitude_min = 2000 },
                { name = "XARTA", type = "E", speed = 220.0 },
                { name = "ORGUR", type = "E" },
                { name = "LOPAP", type = "E" },
                { name = "IVILI", type = "E" },
                { name = "SENPA", type = "E" },
            }
        },
        ["SENP4J"] = {
            name = "SENP4J",
            runway = "RW12",
            waypoints = {
                { name = "", type = "", altitude_min = 570 },
                { name = "DW452", type = "P", altitude_min = 2000 },
                { name = "DW456", type = "P", altitude_min = 5000, speed = 220.0 },
                { name = "DW459", type = "P", altitude_min = 6000 },
                { name = "DW460", type = "P", altitude_min = 7000, speed = 220.0 },
                { name = "DW473", type = "P" },
                { name = "DW406", type = "P" },
                { name = "DW478", type = "P" },
                { name = "KIRUK", type = "P", altitude_min = 7000 },
                { name = "XARTA", type = "E", altitude_min = 8000 },
                { name = "DW412", type = "P" },
                { name = "ORGUR", type = "E" },
                { name = "LOPAP", type = "E" },
                { name = "IVILI", type = "E" },
                { name = "SENPA", type = "E" },
            }
        },
    },

    -- Процедуры STAR
    STAR = {
        ["DATO5Y"] = {
            name = "DATO5Y",
            runway = "RW12",
            waypoints = {
                { name = "DATOB", type = "OM", altitude_max = 16000, speed = 230.0 },
                { name = "DW426", type = "OM" },
                { name = "MITIX", type = "OM", altitude_max = 15000 },
                { name = "DW427", type = "OM", altitude_min = 10000 },
                { name = "DW406", type = "OM", altitude_max = 10000 },
                { name = "DW423", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "ORPAT", type = "OM", altitude_max = 6000 },
                { name = "IVOPU", type = "OM" },
                { name = "DW400", type = "OM", speed = 185.0 },
                { name = "DW412", type = "OM" },
                { name = "NITRI", type = "OM", altitude_min = 3000 },
                { name = "DATOB", type = "OM", altitude_max = 16000, speed = 230.0 },
                { name = "DW426", type = "OM" },
                { name = "MITIX", type = "OM", altitude_max = 15000 },
                { name = "DW427", type = "OM", altitude_min = 10000 },
                { name = "DW406", type = "OM", altitude_max = 10000 },
                { name = "DW423", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "ORPAT", type = "OM", altitude_max = 6000 },
                { name = "IVOPU", type = "OM" },
                { name = "DW400", type = "OM", speed = 185.0 },
                { name = "DW412", type = "OM" },
                { name = "NITRI", type = "OM", altitude_min = 3000 },
            }
        },
        ["DATO5Z"] = {
            name = "DATO5Z",
            runway = "RW30",
            waypoints = {
                { name = "DATOB", type = "OM", altitude_max = 16000, speed = 230.0 },
                { name = "DW426", type = "OM" },
                { name = "MITIX", type = "OM", altitude_max = 15000 },
                { name = "DW427", type = "OM", altitude_min = 10000 },
                { name = "DW406", type = "OM", altitude_max = 10000 },
                { name = "DW423", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "SIBVA", type = "OM" },
                { name = "ODGAK", type = "OM" },
                { name = "SOBOB", type = "OM", speed = 185.0 },
                { name = "UKSUL", type = "OM", speed = 185.0 },
                { name = "GEXIK", type = "OM", altitude_min = 3000 },
                { name = "DATOB", type = "OM", altitude_max = 16000, speed = 230.0 },
                { name = "DW426", type = "OM" },
                { name = "MITIX", type = "OM", altitude_max = 15000 },
                { name = "DW427", type = "OM", altitude_min = 10000 },
                { name = "DW406", type = "OM", altitude_max = 10000 },
                { name = "DW423", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "SIBVA", type = "OM" },
                { name = "ODGAK", type = "OM" },
                { name = "SOBOB", type = "OM", speed = 185.0 },
                { name = "UKSUL", type = "OM", speed = 185.0 },
                { name = "GEXIK", type = "OM", altitude_min = 3000 },
            }
        },
        ["ELOV3Y"] = {
            name = "ELOV3Y",
            runway = "RW12",
            waypoints = {
                { name = "ELOVU", type = "OM", altitude_max = 12000, speed = 230.0 },
                { name = "MISOL", type = "OM" },
                { name = "LORID", type = "OM", altitude_max = 9000, speed = 210.0 },
                { name = "TOVLA", type = "OM", altitude_max = 7000 },
                { name = "DW400", type = "OM", speed = 185.0 },
                { name = "DW412", type = "OM" },
                { name = "NITRI", type = "OM", altitude_min = 3000 },
                { name = "ELOVU", type = "OM", altitude_max = 12000, speed = 230.0 },
                { name = "MISOL", type = "OM" },
                { name = "LORID", type = "OM", altitude_max = 9000, speed = 210.0 },
                { name = "TOVLA", type = "OM", altitude_max = 7000 },
                { name = "DW400", type = "OM", speed = 185.0 },
                { name = "DW412", type = "OM" },
                { name = "NITRI", type = "OM", altitude_min = 3000 },
            }
        },
        ["ELOV3Z"] = {
            name = "ELOV3Z",
            runway = "RW30",
            waypoints = {
                { name = "ELOVU", type = "OM", altitude_max = 12000, speed = 230.0 },
                { name = "MISOL", type = "OM" },
                { name = "LORID", type = "OM", altitude_max = 11000, speed = 230.0 },
                { name = "TOVLA", type = "OM", altitude_max = 10000 },
                { name = "TATMO", type = "OM" },
                { name = "ORPAT", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "SIBVA", type = "OM" },
                { name = "ODGAK", type = "OM" },
                { name = "SOBOB", type = "OM", speed = 185.0 },
                { name = "UKSUL", type = "OM", speed = 185.0 },
                { name = "GEXIK", type = "OM", altitude_min = 3000 },
                { name = "ELOVU", type = "OM", altitude_max = 12000, speed = 230.0 },
                { name = "MISOL", type = "OM" },
                { name = "LORID", type = "OM", altitude_max = 11000, speed = 230.0 },
                { name = "TOVLA", type = "OM", altitude_max = 10000 },
                { name = "TATMO", type = "OM" },
                { name = "ORPAT", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "SIBVA", type = "OM" },
                { name = "ODGAK", type = "OM" },
                { name = "SOBOB", type = "OM", speed = 185.0 },
                { name = "UKSUL", type = "OM", speed = 185.0 },
                { name = "GEXIK", type = "OM", altitude_min = 3000 },
            }
        },
        ["GERU3Y"] = {
            name = "GERU3Y",
            runway = "RW12",
            waypoints = {
                { name = "GERUL", type = "OM", altitude_max = 10000, speed = 210.0 },
                { name = "TOVLA", type = "OM", altitude_max = 7000 },
                { name = "DW400", type = "OM", speed = 185.0 },
                { name = "DW412", type = "OM" },
                { name = "NITRI", type = "OM", altitude_min = 3000 },
                { name = "GERUL", type = "OM", altitude_max = 10000, speed = 210.0 },
                { name = "TOVLA", type = "OM", altitude_max = 7000 },
                { name = "DW400", type = "OM", speed = 185.0 },
                { name = "DW412", type = "OM" },
                { name = "NITRI", type = "OM", altitude_min = 3000 },
            }
        },
        ["GERU3Z"] = {
            name = "GERU3Z",
            runway = "RW30",
            waypoints = {
                { name = "GERUL", type = "OM", altitude_max = 11000, speed = 230.0 },
                { name = "TOVLA", type = "OM", altitude_max = 10000 },
                { name = "TATMO", type = "OM" },
                { name = "ORPAT", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "SIBVA", type = "OM" },
                { name = "ODGAK", type = "OM" },
                { name = "SOBOB", type = "OM", speed = 185.0 },
                { name = "UKSUL", type = "OM", speed = 185.0 },
                { name = "GEXIK", type = "OM", altitude_min = 3000 },
                { name = "GERUL", type = "OM", altitude_max = 11000, speed = 230.0 },
                { name = "TOVLA", type = "OM", altitude_max = 10000 },
                { name = "TATMO", type = "OM" },
                { name = "ORPAT", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "SIBVA", type = "OM" },
                { name = "ODGAK", type = "OM" },
                { name = "SOBOB", type = "OM", speed = 185.0 },
                { name = "UKSUL", type = "OM", speed = 185.0 },
                { name = "GEXIK", type = "OM", altitude_min = 3000 },
            }
        },
        ["GIDI5Y"] = {
            name = "GIDI5Y",
            runway = "RW12",
            waypoints = {
                { name = "GIDIS", type = "OM", altitude_max = 12000, speed = 230.0 },
                { name = "RERAG", type = "OM", altitude_max = 10000, speed = 230.0 },
                { name = "SINPU", type = "OM" },
                { name = "DW416", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "ORPAT", type = "OM", altitude_max = 6000 },
                { name = "IVOPU", type = "OM" },
                { name = "DW400", type = "OM", speed = 185.0 },
                { name = "DW412", type = "OM" },
                { name = "NITRI", type = "OM", altitude_min = 3000 },
                { name = "GIDIS", type = "OM", altitude_max = 12000, speed = 230.0 },
                { name = "RERAG", type = "OM", altitude_max = 10000, speed = 230.0 },
                { name = "SINPU", type = "OM" },
                { name = "DW416", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "ORPAT", type = "OM", altitude_max = 6000 },
                { name = "IVOPU", type = "OM" },
                { name = "DW400", type = "OM", speed = 185.0 },
                { name = "DW412", type = "OM" },
                { name = "NITRI", type = "OM", altitude_min = 3000 },
            }
        },
        ["GIDI5Z"] = {
            name = "GIDI5Z",
            runway = "RW30",
            waypoints = {
                { name = "GIDIS", type = "OM", altitude_max = 11000, speed = 230.0 },
                { name = "RERAG", type = "OM", altitude_max = 10000, speed = 230.0 },
                { name = "SINPU", type = "OM", altitude_max = 7000, speed = 210.0 },
                { name = "UKSUL", type = "OM", speed = 185.0 },
                { name = "GEXIK", type = "OM", altitude_min = 3000 },
                { name = "GIDIS", type = "OM", altitude_max = 11000, speed = 230.0 },
                { name = "RERAG", type = "OM", altitude_max = 10000, speed = 230.0 },
                { name = "SINPU", type = "OM", altitude_max = 7000, speed = 210.0 },
                { name = "UKSUL", type = "OM", speed = 185.0 },
                { name = "GEXIK", type = "OM", altitude_min = 3000 },
            }
        },
        ["GONV5Y"] = {
            name = "GONV5Y",
            runway = "RW12",
            waypoints = {
                { name = "GONVI", type = "OM", altitude_max = 16000, speed = 230.0 },
                { name = "ALRAR", type = "OM" },
                { name = "LOVEM", type = "OM", altitude_max = 15000 },
                { name = "DW427", type = "OM", altitude_min = 10000 },
                { name = "DW406", type = "OM", altitude_max = 10000 },
                { name = "DW423", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "ORPAT", type = "OM", altitude_max = 6000 },
                { name = "IVOPU", type = "OM" },
                { name = "DW400", type = "OM", speed = 185.0 },
                { name = "DW412", type = "OM" },
                { name = "NITRI", type = "OM", altitude_min = 3000 },
                { name = "GONVI", type = "OM", altitude_max = 16000, speed = 230.0 },
                { name = "ALRAR", type = "OM" },
                { name = "LOVEM", type = "OM", altitude_max = 15000 },
                { name = "DW427", type = "OM", altitude_min = 10000 },
                { name = "DW406", type = "OM", altitude_max = 10000 },
                { name = "DW423", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "ORPAT", type = "OM", altitude_max = 6000 },
                { name = "IVOPU", type = "OM" },
                { name = "DW400", type = "OM", speed = 185.0 },
                { name = "DW412", type = "OM" },
                { name = "NITRI", type = "OM", altitude_min = 3000 },
            }
        },
        ["GONV5Z"] = {
            name = "GONV5Z",
            runway = "RW30",
            waypoints = {
                { name = "GONVI", type = "OM", altitude_max = 16000, speed = 230.0 },
                { name = "ALRAR", type = "OM" },
                { name = "LOVEM", type = "OM", altitude_max = 15000 },
                { name = "DW427", type = "OM", altitude_min = 10000 },
                { name = "DW406", type = "OM", altitude_max = 10000 },
                { name = "DW423", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "SIBVA", type = "OM" },
                { name = "ODGAK", type = "OM" },
                { name = "SOBOB", type = "OM", speed = 185.0 },
                { name = "UKSUL", type = "OM", speed = 185.0 },
                { name = "GEXIK", type = "OM", altitude_min = 3000 },
                { name = "GONVI", type = "OM", altitude_max = 16000, speed = 230.0 },
                { name = "ALRAR", type = "OM" },
                { name = "LOVEM", type = "OM", altitude_max = 15000 },
                { name = "DW427", type = "OM", altitude_min = 10000 },
                { name = "DW406", type = "OM", altitude_max = 10000 },
                { name = "DW423", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "SIBVA", type = "OM" },
                { name = "ODGAK", type = "OM" },
                { name = "SOBOB", type = "OM", speed = 185.0 },
                { name = "UKSUL", type = "OM", speed = 185.0 },
                { name = "GEXIK", type = "OM", altitude_min = 3000 },
            }
        },
        ["LORI3Y"] = {
            name = "LORI3Y",
            runway = "RW12",
            waypoints = {
                { name = "LORID", type = "OM", altitude_max = 9000, speed = 210.0 },
                { name = "TOVLA", type = "OM", altitude_max = 7000 },
                { name = "DW400", type = "OM", speed = 185.0 },
                { name = "DW412", type = "OM" },
                { name = "NITRI", type = "OM", altitude_min = 3000 },
                { name = "LORID", type = "OM", altitude_max = 9000, speed = 210.0 },
                { name = "TOVLA", type = "OM", altitude_max = 7000 },
                { name = "DW400", type = "OM", speed = 185.0 },
                { name = "DW412", type = "OM" },
                { name = "NITRI", type = "OM", altitude_min = 3000 },
            }
        },
        ["LORI3Z"] = {
            name = "LORI3Z",
            runway = "RW30",
            waypoints = {
                { name = "LORID", type = "OM", altitude_max = 11000, speed = 230.0 },
                { name = "TOVLA", type = "OM", altitude_max = 10000 },
                { name = "TATMO", type = "OM" },
                { name = "ORPAT", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "SIBVA", type = "OM" },
                { name = "ODGAK", type = "OM" },
                { name = "SOBOB", type = "OM", speed = 185.0 },
                { name = "UKSUL", type = "OM", speed = 185.0 },
                { name = "GEXIK", type = "OM", altitude_min = 3000 },
                { name = "LORID", type = "OM", altitude_max = 11000, speed = 230.0 },
                { name = "TOVLA", type = "OM", altitude_max = 10000 },
                { name = "TATMO", type = "OM" },
                { name = "ORPAT", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "SIBVA", type = "OM" },
                { name = "ODGAK", type = "OM" },
                { name = "SOBOB", type = "OM", speed = 185.0 },
                { name = "UKSUL", type = "OM", speed = 185.0 },
                { name = "GEXIK", type = "OM", altitude_min = 3000 },
            }
        },
        ["PUVA6Y"] = {
            name = "PUVA6Y",
            runway = "RW12",
            waypoints = {
                { name = "PUVAL", type = "OM", altitude_max = 16000, speed = 230.0 },
                { name = "DETGU", type = "OM", altitude_max = 15000 },
                { name = "SERSA", type = "OM" },
                { name = "IVOXI", type = "OM" },
                { name = "DW427", type = "OM", altitude_min = 10000 },
                { name = "DW406", type = "OM", altitude_max = 10000 },
                { name = "DW423", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "ORPAT", type = "OM", altitude_max = 6000 },
                { name = "IVOPU", type = "OM" },
                { name = "DW400", type = "OM", speed = 185.0 },
                { name = "DW412", type = "OM" },
                { name = "NITRI", type = "OM", altitude_min = 3000 },
                { name = "PUVAL", type = "OM", altitude_max = 16000, speed = 230.0 },
                { name = "DETGU", type = "OM", altitude_max = 15000 },
                { name = "SERSA", type = "OM" },
                { name = "IVOXI", type = "OM" },
                { name = "DW427", type = "OM", altitude_min = 10000 },
                { name = "DW406", type = "OM", altitude_max = 10000 },
                { name = "DW423", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "ORPAT", type = "OM", altitude_max = 6000 },
                { name = "IVOPU", type = "OM" },
                { name = "DW400", type = "OM", speed = 185.0 },
                { name = "DW412", type = "OM" },
                { name = "NITRI", type = "OM", altitude_min = 3000 },
            }
        },
        ["PUVA6Z"] = {
            name = "PUVA6Z",
            runway = "RW30",
            waypoints = {
                { name = "PUVAL", type = "OM", altitude_max = 16000, speed = 230.0 },
                { name = "DETGU", type = "OM", altitude_max = 15000 },
                { name = "SERSA", type = "OM" },
                { name = "IVOXI", type = "OM" },
                { name = "DW427", type = "OM", altitude_min = 10000 },
                { name = "DW406", type = "OM", altitude_max = 10000 },
                { name = "DW423", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "SIBVA", type = "OM" },
                { name = "ODGAK", type = "OM" },
                { name = "SOBOB", type = "OM", speed = 185.0 },
                { name = "UKSUL", type = "OM", speed = 185.0 },
                { name = "GEXIK", type = "OM", altitude_min = 3000 },
                { name = "PUVAL", type = "OM", altitude_max = 16000, speed = 230.0 },
                { name = "DETGU", type = "OM", altitude_max = 15000 },
                { name = "SERSA", type = "OM" },
                { name = "IVOXI", type = "OM" },
                { name = "DW427", type = "OM", altitude_min = 10000 },
                { name = "DW406", type = "OM", altitude_max = 10000 },
                { name = "DW423", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "SIBVA", type = "OM" },
                { name = "ODGAK", type = "OM" },
                { name = "SOBOB", type = "OM", speed = 185.0 },
                { name = "UKSUL", type = "OM", speed = 185.0 },
                { name = "GEXIK", type = "OM", altitude_min = 3000 },
            }
        },
        ["UMAM4Y"] = {
            name = "UMAM4Y",
            runway = "RW12",
            waypoints = {
                { name = "UMAMI", type = "OM", altitude_max = 12000, speed = 230.0 },
                { name = "DW422", type = "OM" },
                { name = "DW425", type = "OM", altitude_max = 10000 },
                { name = "SINPU", type = "OM" },
                { name = "DW416", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "ORPAT", type = "OM", altitude_max = 6000 },
                { name = "IVOPU", type = "OM" },
                { name = "DW400", type = "OM", speed = 185.0 },
                { name = "DW412", type = "OM" },
                { name = "NITRI", type = "OM", altitude_min = 3000 },
                { name = "UMAMI", type = "OM", altitude_max = 12000, speed = 230.0 },
                { name = "DW422", type = "OM" },
                { name = "DW425", type = "OM", altitude_max = 10000 },
                { name = "SINPU", type = "OM" },
                { name = "DW416", type = "OM" },
                { name = "DEDAX", type = "OM", altitude_max = 8000, speed = 210.0 },
                { name = "ORPAT", type = "OM", altitude_max = 6000 },
                { name = "IVOPU", type = "OM" },
                { name = "DW400", type = "OM", speed = 185.0 },
                { name = "DW412", type = "OM" },
                { name = "NITRI", type = "OM", altitude_min = 3000 },
            }
        },
        ["UMAM4Z"] = {
            name = "UMAM4Z",
            runway = "RW30",
            waypoints = {
                { name = "UMAMI", type = "OM", altitude_max = 12000, speed = 230.0 },
                { name = "DW422", type = "OM" },
                { name = "DW425", type = "OM", altitude_max = 10000 },
                { name = "SINPU", type = "OM", altitude_max = 7000, speed = 210.0 },
                { name = "UKSUL", type = "OM", speed = 185.0 },
                { name = "GEXIK", type = "OM", altitude_min = 3000 },
                { name = "UMAMI", type = "OM", altitude_max = 12000, speed = 230.0 },
                { name = "DW422", type = "OM" },
                { name = "DW425", type = "OM", altitude_max = 10000 },
                { name = "SINPU", type = "OM", altitude_max = 7000, speed = 210.0 },
                { name = "UKSUL", type = "OM", speed = 185.0 },
                { name = "GEXIK", type = "OM", altitude_min = 3000 },
            }
        },
    },

    -- Процедуры захода на посадку
    APPROACH = {
        ["I12"] = {
            name = "I12",
            type = "A",
            runway = "I12",
            waypoints = {
                { name = "NITRI", transition = "NITRI", type = "OM", altitude_min = 3000, speed = 185.0 },
                { name = "PUSVO", transition = "NITRI", type = "OM", altitude_min = 3000 },
                { name = "PUSVO", transition = "", type = "OM" },
                { name = "DW661", transition = "", type = "OM" },
                { name = "RW12", transition = "", type = "OM" },
                { name = "REVUL", transition = "", type = "OM", speed = 210.0 },
                { name = "REVUL", transition = "", type = "OM", speed = 210.0 },
            }
        },
        ["I30"] = {
            name = "I30",
            type = "A",
            runway = "I30",
            waypoints = {
                { name = "GEXIK", transition = "GEXIK", type = "OM", altitude_min = 3000, speed = 185.0 },
                { name = "REVUL", transition = "GEXIK", type = "OM", altitude_min = 3000 },
                { name = "REVUL", transition = "", type = "OM" },
                { name = "DW761", transition = "", type = "OM" },
                { name = "RW30", transition = "", type = "OM" },
                { name = "LADMO", transition = "", type = "OM", speed = 210.0 },
                { name = "LADMO", transition = "", type = "OM", speed = 230.0 },
            }
        },
        ["I31"] = {
            name = "I31",
            type = "A",
            runway = "I31",
            waypoints = {
                { name = "KUKPO", transition = "KUKPO", type = "OM", altitude_min = 3000 },
                { name = "EF870", transition = "KUKPO", type = "OM" },
                { name = "PEBER", transition = "KUKPO", type = "OM" },
                { name = "EF871", transition = "KUKPO", type = "OM" },
                { name = "SIBVA", transition = "SIBVA", type = "OM", altitude_min = 2000 },
                { name = "ODGAK", transition = "SIBVA", type = "OM", altitude_min = 2000 },
                { name = "EF870", transition = "SIBVA", type = "OM" },
                { name = "PEBER", transition = "SIBVA", type = "OM" },
                { name = "EF871", transition = "SIBVA", type = "OM" },
                { name = "SINPU", transition = "SINPU", type = "OM", altitude_max = 7000 },
                { name = "EF869", transition = "SINPU", type = "OM" },
                { name = "PEBER", transition = "SINPU", type = "OM" },
                { name = "EF871", transition = "SINPU", type = "OM" },
                { name = "EF871", transition = "", type = "OM" },
                { name = "EF813", transition = "", type = "OM" },
                { name = "RW31", transition = "", type = "OM" },
                { name = "EF868", transition = "", type = "OM" },
                { name = "EF872", transition = "", type = "OM" },
                { name = "SIBVA", transition = "", type = "OM", speed = 130.0 },
                { name = "SIBVA", transition = "", type = "OM", speed = 150.0 },
            }
        },
        ["R12"] = {
            name = "R12",
            type = "A",
            runway = "R12",
            waypoints = {
                { name = "NITRI", transition = "NITRI", type = "OM", altitude_min = 3000, speed = 185.0 },
                { name = "PUSVO", transition = "NITRI", type = "OM", altitude_min = 3000 },
                { name = "PUSVO", transition = "", type = "OM", altitude_min = 3000 },
                { name = "DW660", transition = "", type = "OM" },
                { name = "RW12", transition = "", type = "OM" },
                { name = "REVUL", transition = "", type = "OM", speed = 210.0 },
                { name = "REVUL", transition = "", type = "OM", speed = 210.0 },
            }
        },
        ["R13"] = {
            name = "R13",
            type = "A",
            runway = "R13",
            waypoints = {
                { name = "ORPAT", transition = "ORPAT", type = "OM" },
                { name = "IVOPU", transition = "ORPAT", type = "OM" },
                { name = "EF670", transition = "ORPAT", type = "OM" },
                { name = "EF671", transition = "ORPAT", type = "OM" },
                { name = "EF672", transition = "ORPAT", type = "OM" },
                { name = "TOVLA", transition = "TOVLA", type = "OM" },
                { name = "DW400", transition = "TOVLA", type = "OM" },
                { name = "EF671", transition = "TOVLA", type = "OM" },
                { name = "EF672", transition = "TOVLA", type = "OM" },
                { name = "EF672", transition = "", type = "OM" },
                { name = "EF667", transition = "", type = "OM" },
                { name = "RW13", transition = "", type = "OM" },
                { name = "EF673", transition = "", type = "OM" },
                { name = "SEVNU", transition = "", type = "OM", speed = 130.0 },
                { name = "SEVNU", transition = "", type = "OM", speed = 150.0 },
            }
        },
        ["R30"] = {
            name = "R30",
            type = "A",
            runway = "R30",
            waypoints = {
                { name = "GEXIK", transition = "GEXIK", type = "OM", altitude_min = 3000, speed = 185.0 },
                { name = "REVUL", transition = "GEXIK", type = "OM", altitude_min = 3000 },
                { name = "REVUL", transition = "", type = "OM", altitude_min = 3000 },
                { name = "DW760", transition = "", type = "OM" },
                { name = "RW30", transition = "", type = "OM" },
                { name = "LADMO", transition = "", type = "OM", speed = 210.0 },
                { name = "LADMO", transition = "", type = "OM", speed = 230.0 },
            }
        },
        ["R31"] = {
            name = "R31",
            type = "A",
            runway = "R31",
            waypoints = {
                { name = "KUKPO", transition = "KUKPO", type = "OM", altitude_min = 3000 },
                { name = "EF870", transition = "KUKPO", type = "OM" },
                { name = "PEBER", transition = "KUKPO", type = "OM" },
                { name = "EF871", transition = "KUKPO", type = "OM" },
                { name = "SIBVA", transition = "SIBVA", type = "OM", altitude_min = 2000 },
                { name = "ODGAK", transition = "SIBVA", type = "OM", altitude_min = 2000 },
                { name = "EF870", transition = "SIBVA", type = "OM" },
                { name = "PEBER", transition = "SIBVA", type = "OM" },
                { name = "EF871", transition = "SIBVA", type = "OM" },
                { name = "SINPU", transition = "SINPU", type = "OM", altitude_max = 7000 },
                { name = "EF869", transition = "SINPU", type = "OM" },
                { name = "PEBER", transition = "SINPU", type = "OM" },
                { name = "EF871", transition = "SINPU", type = "OM" },
                { name = "EF871", transition = "", type = "OM" },
                { name = "EF866", transition = "", type = "OM" },
                { name = "RW31", transition = "", type = "OM" },
                { name = "EF868", transition = "", type = "OM" },
                { name = "EF872", transition = "", type = "OM" },
                { name = "SIBVA", transition = "", type = "OM", speed = 130.0 },
                { name = "SIBVA", transition = "", type = "OM", speed = 150.0 },
            }
        },
    },

    -- Частоты
    Frequencies = {
        TOWER = 118.0,
        APPROACH = 121.0,
        DEPARTURE = 125.0,
        GROUND = 121.7,
        ATIS = 126.0,
    }
}

return AirportData
