local AirportData = {
    -- Метаданные аэропорта
    Metadata = {
        ICAO = "OTBD",
        Name = "OTBD Airport",
        Elevation = 0,
        MagVar = 0,
        Region = "PersianGulf"
    },

    -- Путевые точки
    Waypoints = {
        ["KIPIK"] = { lat = 25.221513889, lon = 51.483475, type = "ENRT" },
        ["EMISA"] = { lat = 25.782875, lon = 51.701855556, type = "ENRT" },
        ["GIBIN"] = { lat = 25.668397222, lon = 51.738291667, type = "ENRT" },
        ["LOVET"] = { lat = 25.367480556, lon = 51.862363889, type = "ENRT" },
        ["D155B"] = { lat = 25.210641667, lon = 51.587313889, type = "OTBD" },
        ["D335F"] = { lat = 50.443055556, lon = 137.182777778, type = "UHKD" },
        ["DATRI"] = { lat = 24.710938889, lon = 51.568688889, type = "ENRT" },
        ["GINTO"] = { lat = 25.268211111, lon = 51.071077778, type = "ENRT" },
        ["KINAP"] = { lat = 25.190322222, lon = 51.398191667, type = "ENRT" },
        ["MUTLI"] = { lat = 25.249691667, lon = 51.912563889, type = "ENRT" },
        ["DEKMI"] = { lat = 25.00185, lon = 51.540708333, type = "OTBD" },
        ["TOSNA"] = { lat = 25.27, lon = 52.687777778, type = "ENRT" },
        ["SOMAP"] = { lat = 25.103833333, lon = 51.535380556, type = "ENRT" },
        ["NAJMA"] = { lat = 25.016011111, lon = 51.6729, type = "OTBD" },
        ["EMALO"] = { lat = 25.123155556, lon = 51.967875, type = "ENRT" },
        ["ORBIV"] = { lat = 24.928338889, lon = 51.398988889, type = "ENRT" },
        ["IMKAT"] = { lat = 25.027380556, lon = 51.705661111, type = "ENRT" },
        ["MISEL"] = { lat = 26.151819444, lon = 51.147438889, type = "ENRT" },
        ["TULUB"] = { lat = 26.112222222, lon = 51.011388889, type = "ENRT" },
        ["MIVAL"] = { lat = 24.953186111, lon = 51.502844444, type = "ENRT" },
        ["ALNAK"] = { lat = 25.848191667, lon = 51.567191667, type = "ENRT" },
        ["SILDA"] = { lat = 25.350061111, lon = 51.525825, type = "OTBD" },
        ["KIVAM"] = { lat = 24.883202778, lon = 52.072436111, type = "ENRT" },
        ["BD701"] = { lat = 25.099455556, lon = 51.636244444, type = "OTBD" },
        ["KUTER"] = { lat = 25.030277778, lon = 51.468869444, type = "ENRT" },
        ["VAXIN"] = { lat = 25.678611111, lon = 52.363333333, type = "ENRT" },
        ["D295D"] = { lat = 25.260808333, lon = 51.519977778, type = "OTBD" },
        ["SENKI"] = { lat = 25.776944444, lon = 52.157777778, type = "ENRT" },
        ["IMTAL"] = { lat = 24.873322222, lon = 51.939105556, type = "ENRT" },
        ["SILSU"] = { lat = 25.312752778, lon = 51.542302778, type = "OTBD" },
        ["LABEX"] = { lat = 25.379002778, lon = 52.414655556, type = "ENRT" },
        ["GETOV"] = { lat = 25.705572222, lon = 52.185769444, type = "ENRT" },
        ["EMEXA"] = { lat = 24.847686111, lon = 51.601091667, type = "ENRT" },
        ["MUXED"] = { lat = 25.065583333, lon = 51.809105556, type = "ENRT" },
        ["LOVAN"] = { lat = 25.142133333, lon = 51.775558333, type = "ENRT" },
        ["MAXMO"] = { lat = 25.500861111, lon = 51.459141667, type = "OTBD" },
        ["LUGAM"] = { lat = 25.416147222, lon = 51.496622222, type = "OTBD" },
        ["SOKEN"] = { lat = 25.451336111, lon = 51.540386111, type = "ENRT" },
        ["GITNI"] = { lat = 25.442677778, lon = 51.449325, type = "OTBD" },
        ["SILBI"] = { lat = 25.553347222, lon = 52.520488889, type = "ENRT" },
        ["BD401"] = { lat = 14.822513889, lon = -17.074247222, type = "GOBD" },
        ["REVIN"] = { lat = 25.469191667, lon = 51.631855556, type = "ENRT" },
        ["EGNUG"] = { lat = 25.31195, lon = 51.700983333, type = "ENRT" },
        ["KUVLA"] = { lat = 25.119494444, lon = 52.442775, type = "ENRT" },
        ["BUNDU"] = { lat = 25.006666667, lon = 52.49, type = "ENRT" },
        ["ULDOR"] = { lat = 25.369477778, lon = 51.461341667, type = "OTBD" },
        ["GIRKA"] = { lat = 25.293994444, lon = 51.352302778, type = "ENRT" },
        ["VEDED"] = { lat = 26.099516667, lon = 51.774419444, type = "ENRT" },
        ["DATAL"] = { lat = 25.306325, lon = 52.559291667, type = "ENRT" },
        ["NOKTO"] = { lat = 25.283566667, lon = 51.456061111, type = "ENRT" },
        ["ELILO"] = { lat = 25.410977778, lon = 51.753716667, type = "OTBD" },
        ["EMORA"] = { lat = 24.143055556, lon = 55.599166667, type = "OMAL" },
        ["LUBET"] = { lat = 26.244630556, lon = 51.062927778, type = "ENRT" },
        ["GOBLU"] = { lat = 25.353797222, lon = 52.204797222, type = "ENRT" },
        ["KOBEN"] = { lat = 25.656105556, lon = 51.559552778, type = "ENRT" },
        ["UKOBA"] = { lat = 24.971113889, lon = 51.945683333, type = "ENRT" },
        ["HAYYA"] = { lat = 26.073716667, lon = 51.402047222, type = "ENRT" },
        ["AFNAN"] = { lat = 25.050222222, lon = 51.9997, type = "ENRT" },
        ["NADIG"] = { lat = 25.156355556, lon = 51.305516667, type = "ENRT" },
        ["NOLMA"] = { lat = 25.388580556, lon = 51.667255556, type = "ENRT" },
        ["SOLAL"] = { lat = -11.85, lon = 41.815, type = "ENRT" },
        ["SUVMA"] = { lat = 25.3933, lon = 52.010025, type = "OTBD" },
        ["ITIBA"] = { lat = 25.234625, lon = 51.614569444, type = "OTBD" },
        ["LUBAK"] = { lat = 25.618186111, lon = 51.93545, type = "ENRT" },
        ["ENELI"] = { lat = 25.499847222, lon = 51.417261111, type = "ENRT" },
        ["LOSEN"] = { lat = 25.37675, lon = 51.414838889, type = "ENRT" },
        ["IVOMO"] = { lat = 25.121533333, lon = 52.330419444, type = "ENRT" },
        ["IVIXU"] = { lat = 25.021477778, lon = 51.127530556, type = "ENRT" },
        ["KUBAR"] = { lat = 25.437566667, lon = 52.297780556, type = "ENRT" },
        ["REVAT"] = { lat = 25.172430556, lon = 51.825583333, type = "OTBD" },
        ["DINEX"] = { lat = 24.897188889, lon = 52.263433333, type = "ENRT" },
        ["BD411"] = { lat = 11.485666667, lon = 37.609416667, type = "HABD" },
        ["PURIN"] = { lat = 25.061430556, lon = 51.554058333, type = "ENRT" },
        ["SIVET"] = { lat = 25.624205556, lon = 51.820691667, type = "ENRT" },
        ["TUDOM"] = { lat = 25.776572222, lon = 52.017391667, type = "ENRT" },
        ["NORLU"] = { lat = 25.019941667, lon = 50.899841667, type = "ENRT" },
        ["IMSUN"] = { lat = 25.91265, lon = 51.642530556, type = "ENRT" },
        ["KATED"] = { lat = 25.469277778, lon = 51.373841667, type = "ENRT" },
        ["RW33"] = { lat = -23.016363889, lon = -47.121994444, type = "SBKP" },
        ["VUTAN"] = { lat = 25.837752778, lon = 51.871775, type = "ENRT" },
        ["GOKNI"] = { lat = 24.879147222, lon = 51.268983333, type = "ENRT" },
        ["BD702"] = { lat = 25.233630556, lon = 51.577172222, type = "OTBD" },
        ["BD412"] = { lat = 25.084202778, lon = 51.495388889, type = "OTBD" },
        ["KASIS"] = { lat = 25.113044444, lon = 51.790683333, type = "ENRT" },
        ["LAEEB"] = { lat = 24.685105556, lon = 51.521627778, type = "ENRT" },
        ["BD712"] = { lat = 25.098022222, lon = 51.470141667, type = "OTBD" },
        ["RESAR"] = { lat = 25.618611111, lon = 52.391111111, type = "ENRT" },
        ["EGMED"] = { lat = 25.249905556, lon = 51.609666667, type = "ENRT" },
        ["LONOG"] = { lat = 25.064722222, lon = 52.284586111, type = "ENRT" },
        ["OXAGO"] = { lat = 25.536811111, lon = 52.099041667, type = "ENRT" },
        ["DASIK"] = { lat = 24.984319444, lon = 51.587988889, type = "ENRT" },
        ["IVIKA"] = { lat = 25.471241667, lon = 51.607144444, type = "OTBD" },
        ["ALKAN"] = { lat = 25.870555556, lon = 52.270833333, type = "ENRT" },
        ["IMGOG"] = { lat = 25.637680556, lon = 51.557316667, type = "ENRT" },
        ["PATOM"] = { lat = 25.972613889, lon = 51.3101, type = "ENRT" },
        ["SIDMU"] = { lat = 25.192066667, lon = 51.753652778, type = "ENRT" },
        ["TOVOX"] = { lat = 24.894872222, lon = 52.407972222, type = "ENRT" },
        ["SERGA"] = { lat = 25.338097222, lon = 51.855425, type = "ENRT" },
        ["KUPRO"] = { lat = 25.134722222, lon = 52.586944444, type = "ENRT" },
        ["KIPEM"] = { lat = 24.859544444, lon = 51.756413889, type = "ENRT" },
        ["VELAM"] = { lat = 25.907255556, lon = 51.729758333, type = "ENRT" },
        ["DEMBO"] = { lat = 25.581477778, lon = 51.659036111, type = "ENRT" },
        ["ALSEM"] = { lat = 25.450958333, lon = 52.722788889, type = "ENRT" },
        ["BD711"] = { lat = 25.123877778, lon = 51.625508333, type = "OTBD" },
        ["BUBOG"] = { lat = 25.034661111, lon = 51.712758333, type = "OTBD" },
        ["BAYAN"] = { lat = 25.490555556, lon = 51.813611111, type = "ENRT" },
        ["PASIS"] = { lat = 25.531841667, lon = 51.696336111, type = "ENRT" },
        ["RAMPO"] = { lat = 25.075122222, lon = 51.646947222, type = "OTBD" },
        ["MUSTA"] = { lat = 25.072008333, lon = 51.338591667, type = "ENRT" },
        ["ALVEN"] = { lat = 25.905052778, lon = 51.887583333, type = "ENRT" },
        ["KOBAT"] = { lat = 25.368266667, lon = 51.555652778, type = "OTBD" },
        ["IVANI"] = { lat = 25.550613889, lon = 51.595797222, type = "ENRT" },
        ["PUTAN"] = { lat = 25.465197222, lon = 51.633491667, type = "ENRT" },
        ["UKTON"] = { lat = 25.038733333, lon = 51.357569444, type = "ENRT" },
        ["ULIKA"] = { lat = 25.262580556, lon = 50.646886111, type = "ENRT" },
        ["ORLEK"] = { lat = 25.428333333, lon = 50.62, type = "ENRT" },
        ["NORMU"] = { lat = 25.479816667, lon = 52.665830556, type = "ENRT" },
        ["EMUKI"] = { lat = 25.394655556, lon = 51.425941667, type = "OTBD" },
        ["LAGNO"] = { lat = 25.270277778, lon = 51.255, type = "ENRT" },
        ["SOBOM"] = { lat = 25.457905556, lon = 51.47815, type = "OTBD" },
        ["RUBOL"] = { lat = 24.919277778, lon = 51.410322222, type = "ENRT" },
        ["LOTUM"] = { lat = 25.290230556, lon = 52.0951, type = "ENRT" },
        ["MISOX"] = { lat = 25.2343, lon = 51.735111111, type = "ENRT" },
        ["NONBA"] = { lat = 25.072672222, lon = 51.450166667, type = "ENRT" },
    },

    -- Данные ВПП
    Runways = {
        ["RW15"] = {
            heading = 150,
            length = 0,
            width = 0,
            threshold = { lat = 25.273925, lon = 51.55942222222222 },
            end = { lat = 25.273925, lon = 51.55942222222222 }
        },
        ["RW33"] = {
            heading = 330,
            length = 0,
            width = 0,
            threshold = { lat = 25.24191111111111, lon = 51.57353611111112 },
            end = { lat = 25.24191111111111, lon = 51.57353611111112 }
        },
    },

    -- Процедуры SID
    SID = {
        ["ALSE3N"] = {
            name = "ALSE3N",
            runway = "RW33",
            waypoints = {
                { name = "SILSU", type = "P" },
                { name = "ULDOR", type = "P", altitude_min = 2500, speed = 210.0 },
                { name = "KIPIK", type = "E", speed = 230.0 },
                { name = "EGMED", type = "E", speed = 250.0 },
                { name = "SUVMA", type = "P" },
                { name = "GOBLU", type = "E" },
                { name = "ALSEM", type = "E", altitude_max = 21000 },
            }
        },
        ["ALSE3S"] = {
            name = "ALSE3S",
            runway = "RW15",
            waypoints = {
                { name = "EMORA", type = "P" },
                { name = "", type = "", altitude_min = 500 },
                { name = "PURIN", type = "E" },
                { name = "KUTER", type = "E", speed = 230.0 },
                { name = "GIRKA", type = "E", altitude_min = 10000 },
                { name = "KOBAT", type = "P", altitude_min = 12000 },
                { name = "LOTUM", type = "E" },
                { name = "GOBLU", type = "E" },
                { name = "ALSEM", type = "E", altitude_max = 21000 },
            }
        },
        ["ALVE3N"] = {
            name = "ALVE3N",
            runway = "RW33",
            waypoints = {
                { name = "SILSU", type = "P" },
                { name = "ULDOR", type = "P", altitude_min = 2500, speed = 210.0 },
                { name = "KIPIK", type = "E", speed = 230.0 },
                { name = "EGMED", type = "E", speed = 250.0 },
                { name = "REVIN", type = "E" },
                { name = "DEMBO", type = "E" },
                { name = "GIBIN", type = "E" },
                { name = "ALVEN", type = "E", altitude_max = 15000 },
            }
        },
        ["ALVE3S"] = {
            name = "ALVE3S",
            runway = "RW15",
            waypoints = {
                { name = "EMORA", type = "P" },
                { name = "", type = "", altitude_min = 500 },
                { name = "PURIN", type = "E" },
                { name = "KUTER", type = "E", speed = 230.0 },
                { name = "GIRKA", type = "E", altitude_min = 10000 },
                { name = "KOBAT", type = "P", altitude_min = 12000 },
                { name = "PASIS", type = "E" },
                { name = "GIBIN", type = "E" },
                { name = "ALVEN", type = "E", altitude_max = 15000 },
            }
        },
        ["BUND3N"] = {
            name = "BUND3N",
            runway = "RW33",
            waypoints = {
                { name = "SILSU", type = "P" },
                { name = "ULDOR", type = "P", altitude_min = 2500, speed = 210.0 },
                { name = "KIPIK", type = "E", speed = 230.0 },
                { name = "EGMED", type = "E", speed = 250.0 },
                { name = "SERGA", type = "E" },
                { name = "LOTUM", type = "E" },
                { name = "IVOMO", type = "E" },
                { name = "BUNDU", type = "E", altitude_max = 25000 },
            }
        },
        ["BUND3S"] = {
            name = "BUND3S",
            runway = "RW15",
            waypoints = {
                { name = "EMORA", type = "P" },
                { name = "", type = "", altitude_min = 500 },
                { name = "PURIN", type = "E" },
                { name = "KUTER", type = "E", speed = 230.0 },
                { name = "GIRKA", type = "E", altitude_min = 10000 },
                { name = "KOBAT", type = "P", altitude_min = 12000 },
                { name = "IMKAT", type = "E" },
                { name = "LONOG", type = "E" },
                { name = "BUNDU", type = "E", altitude_max = 25000 },
            }
        },
        ["DATR1N"] = {
            name = "DATR1N",
            runway = "RW33",
            waypoints = {
                { name = "SILSU", type = "P", speed = 210.0 },
                { name = "EMUKI", type = "P", altitude_min = 2500 },
                { name = "LAGNO", type = "E", speed = 250.0 },
                { name = "MUSTA", type = "E" },
                { name = "ORBIV", type = "E" },
                { name = "DATRI", type = "E", altitude_max = 12000 },
            }
        },
        ["DATR1S"] = {
            name = "DATR1S",
            runway = "RW15",
            waypoints = {
                { name = "EMORA", type = "P" },
                { name = "", type = "", altitude_min = 500 },
                { name = "PURIN", type = "E" },
                { name = "KUTER", type = "E", speed = 230.0 },
                { name = "GIRKA", type = "E", altitude_min = 10000 },
                { name = "KOBAT", type = "P", altitude_min = 12000 },
                { name = "IMKAT", type = "E", altitude_min = 16000 },
                { name = "SOLAL", type = "E" },
                { name = "DATRI", type = "E" },
            }
        },
        ["KUPR1N"] = {
            name = "KUPR1N",
            runway = "RW33",
            waypoints = {
                { name = "SILSU", type = "P" },
                { name = "ULDOR", type = "P", altitude_min = 2500, speed = 210.0 },
                { name = "KIPIK", type = "E", speed = 230.0 },
                { name = "EGMED", type = "E", speed = 250.0 },
                { name = "SERGA", type = "E" },
                { name = "LOTUM", type = "E" },
                { name = "KUPRO", type = "E", altitude_max = 25000 },
            }
        },
        ["KUPR1S"] = {
            name = "KUPR1S",
            runway = "RW15",
            waypoints = {
                { name = "EMORA", type = "P" },
                { name = "", type = "", altitude_min = 500 },
                { name = "PURIN", type = "E" },
                { name = "KUTER", type = "E", speed = 230.0 },
                { name = "GIRKA", type = "E", altitude_min = 10000 },
                { name = "KOBAT", type = "P", altitude_min = 12000 },
                { name = "ITIBA", type = "P" },
                { name = "KASIS", type = "E" },
                { name = "LOTUM", type = "E" },
                { name = "KUPRO", type = "E", altitude_max = 25000 },
            }
        },
        ["LUBE2N"] = {
            name = "LUBE2N",
            runway = "RW33",
            waypoints = {
                { name = "SILSU", type = "P" },
                { name = "ULDOR", type = "P", altitude_min = 2500, speed = 210.0 },
                { name = "KIPIK", type = "E", speed = 230.0 },
                { name = "EGMED", type = "E", speed = 250.0 },
                { name = "REVIN", type = "E" },
                { name = "DEMBO", type = "E" },
                { name = "EMISA", type = "E" },
                { name = "IMSUN", type = "E", altitude_max = 17000 },
                { name = "MISEL", type = "E" },
                { name = "LUBET", type = "E", altitude_min = 18000 },
            }
        },
        ["LUBE2S"] = {
            name = "LUBE2S",
            runway = "RW15",
            waypoints = {
                { name = "EMORA", type = "P" },
                { name = "", type = "", altitude_min = 500 },
                { name = "PURIN", type = "E" },
                { name = "KUTER", type = "E", speed = 230.0 },
                { name = "GIRKA", type = "E", altitude_min = 10000 },
                { name = "KOBAT", type = "P", altitude_min = 12000 },
                { name = "PASIS", type = "E" },
                { name = "GIBIN", type = "E" },
                { name = "EMISA", type = "E" },
                { name = "IMSUN", type = "E", altitude_max = 17000 },
                { name = "MISEL", type = "E" },
                { name = "LUBET", type = "E", altitude_min = 18000 },
            }
        },
        ["PATO3N"] = {
            name = "PATO3N",
            runway = "RW33",
            waypoints = {
                { name = "SILSU", type = "P" },
                { name = "ULDOR", type = "P", altitude_min = 2500, speed = 210.0 },
                { name = "KIPIK", type = "E", speed = 230.0 },
                { name = "EGMED", type = "E", speed = 250.0 },
                { name = "SOKEN", type = "E" },
                { name = "KOBEN", type = "E" },
                { name = "ALNAK", type = "E" },
                { name = "PATOM", type = "E", altitude_min = 16000 },
            }
        },
        ["PATO3S"] = {
            name = "PATO3S",
            runway = "RW15",
            waypoints = {
                { name = "EMORA", type = "P" },
                { name = "", type = "", altitude_min = 500 },
                { name = "PURIN", type = "E" },
                { name = "KUTER", type = "E", speed = 230.0 },
                { name = "GIRKA", type = "E", altitude_min = 9000 },
                { name = "ENELI", type = "E", altitude_max = 12000 },
                { name = "KOBEN", type = "E", altitude_min = 15000 },
                { name = "ALNAK", type = "E" },
                { name = "PATOM", type = "E", altitude_min = 16000 },
            }
        },
        ["TULU2N"] = {
            name = "TULU2N",
            runway = "RW33",
            waypoints = {
                { name = "SILSU", type = "P" },
                { name = "ULDOR", type = "P", altitude_min = 2500, speed = 210.0 },
                { name = "KIPIK", type = "E", speed = 230.0 },
                { name = "EGMED", type = "E", speed = 250.0 },
                { name = "SOKEN", type = "E" },
                { name = "KOBEN", type = "E" },
                { name = "ALNAK", type = "E" },
                { name = "PATOM", type = "E" },
                { name = "TULUB", type = "E", altitude_min = 18000 },
            }
        },
        ["TULU2S"] = {
            name = "TULU2S",
            runway = "RW15",
            waypoints = {
                { name = "EMORA", type = "P" },
                { name = "", type = "", altitude_min = 500 },
                { name = "PURIN", type = "E" },
                { name = "KUTER", type = "E", speed = 230.0 },
                { name = "GIRKA", type = "E", altitude_min = 9000 },
                { name = "ENELI", type = "E", altitude_max = 12000 },
                { name = "KOBEN", type = "E" },
                { name = "ALNAK", type = "E" },
                { name = "PATOM", type = "E" },
                { name = "TULUB", type = "E", altitude_min = 18000 },
            }
        },
        ["ULIK1N"] = {
            name = "ULIK1N",
            runway = "RW33",
            waypoints = {
                { name = "SILSU", type = "P", speed = 210.0 },
                { name = "EMUKI", type = "P", altitude_min = 2500 },
                { name = "LAGNO", type = "E", speed = 250.0 },
                { name = "MUSTA", type = "E" },
                { name = "IVIXU", type = "E" },
                { name = "NORLU", type = "E" },
                { name = "ULIKA", type = "E", altitude_max = 20000 },
            }
        },
        ["ULIK1S"] = {
            name = "ULIK1S",
            runway = "RW15",
            waypoints = {
                { name = "EMORA", type = "P" },
                { name = "", type = "", altitude_min = 500 },
                { name = "PURIN", type = "E" },
                { name = "KUTER", type = "E", speed = 230.0 },
                { name = "IVIXU", type = "E" },
                { name = "NORLU", type = "E" },
                { name = "ULIKA", type = "E", altitude_max = 20000 },
            }
        },
        ["VAXI3N"] = {
            name = "VAXI3N",
            runway = "RW33",
            waypoints = {
                { name = "SILSU", type = "P" },
                { name = "ULDOR", type = "P", altitude_min = 2500, speed = 210.0 },
                { name = "KIPIK", type = "E", speed = 230.0 },
                { name = "EGMED", type = "E", speed = 250.0 },
                { name = "SUVMA", type = "P" },
                { name = "GOBLU", type = "E" },
                { name = "VAXIN", type = "E", altitude_max = 15000 },
            }
        },
        ["VAXI3S"] = {
            name = "VAXI3S",
            runway = "RW15",
            waypoints = {
                { name = "EMORA", type = "P" },
                { name = "", type = "", altitude_min = 500 },
                { name = "PURIN", type = "E" },
                { name = "KUTER", type = "E", speed = 230.0 },
                { name = "GIRKA", type = "E", altitude_min = 10000 },
                { name = "KOBAT", type = "P", altitude_min = 12000 },
                { name = "LOTUM", type = "E" },
                { name = "GOBLU", type = "E" },
                { name = "VAXIN", type = "E", altitude_max = 15000 },
            }
        },
    },

    -- Процедуры STAR
    STAR = {
        ["ALKA1F"] = {
            name = "ALKA1F",
            runway = "RW15",
            waypoints = {
                { name = "ALKAN", type = "OT", altitude_min = 20000 },
                { name = "GETOV", type = "OT", speed = 250.0 },
                { name = "RESAR", type = "OT" },
                { name = "SILBI", type = "OT" },
                { name = "NORMU", type = "OT", speed = 250.0 },
                { name = "DATAL", type = "OT", speed = 250.0 },
                { name = "LABEX", type = "OT" },
                { name = "KUBAR", type = "OT" },
                { name = "OXAGO", type = "OT" },
                { name = "LUBAK", type = "OT" },
                { name = "BAYAN", type = "OT", altitude_min = 8000 },
                { name = "LOVET", type = "OT" },
                { name = "EGNUG", type = "OT" },
                { name = "KIPIK", type = "OT" },
                { name = "NOKTO", type = "OT" },
                { name = "LOSEN", type = "OT" },
                { name = "KATED", type = "OT", altitude_min = 3500, altitude_max = 4500, speed = 220.0 },
                { name = "KATED", type = "OT", speed = 220.0 },
            }
        },
        ["ALKA1H"] = {
            name = "ALKA1H",
            runway = "RW15",
            waypoints = {
                { name = "ALKAN", type = "OT", altitude_min = 20000 },
                { name = "SENKI", type = "OT" },
                { name = "LUBAK", type = "OT" },
                { name = "SIVET", type = "OT", altitude_max = 6000 },
                { name = "IMGOG", type = "OT", altitude_min = 4500, speed = 220.0 },
                { name = "IMGOG", type = "OT", altitude_min = 4500, speed = 220.0 },
            }
        },
        ["ALKA1L"] = {
            name = "ALKA1L",
            runway = "RW33",
            waypoints = {
                { name = "ALKAN", type = "OT", altitude_min = 20000 },
                { name = "GETOV", type = "OT", speed = 250.0 },
                { name = "RESAR", type = "OT" },
                { name = "SILBI", type = "OT" },
                { name = "NORMU", type = "OT", speed = 250.0 },
                { name = "DATAL", type = "OT", speed = 250.0 },
                { name = "LABEX", type = "OT" },
                { name = "KUBAR", type = "OT" },
                { name = "OXAGO", type = "OT" },
                { name = "LUBAK", type = "OT" },
                { name = "BAYAN", type = "OT" },
                { name = "KATED", type = "OT" },
                { name = "LOSEN", type = "OT", speed = 230.0 },
                { name = "KIPIK", type = "OT" },
                { name = "SOMAP", type = "OT" },
                { name = "PURIN", type = "OT" },
                { name = "DASIK", type = "OT", altitude_min = 3500, altitude_max = 4500, speed = 220.0 },
                { name = "DASIK", type = "OT", speed = 220.0 },
            }
        },
        ["ALKA1P"] = {
            name = "ALKA1P",
            runway = "RW15",
            waypoints = {
                { name = "ALKAN", type = "OT", altitude_min = 20000 },
                { name = "GETOV", type = "OT", speed = 250.0 },
                { name = "RESAR", type = "OT" },
                { name = "SILBI", type = "OT" },
                { name = "NORMU", type = "OT", speed = 250.0 },
                { name = "DATAL", type = "OT", speed = 250.0 },
                { name = "LABEX", type = "OT" },
                { name = "KUBAR", type = "OT" },
                { name = "OXAGO", type = "OT" },
                { name = "LUBAK", type = "OT" },
                { name = "BAYAN", type = "OT", altitude_min = 8000 },
                { name = "LOVET", type = "OT" },
                { name = "EGNUG", type = "OT" },
                { name = "NOLMA", type = "OT" },
                { name = "PUTAN", type = "OT" },
                { name = "IVANI", type = "OT", altitude_min = 4500, speed = 220.0 },
                { name = "IMGOG", type = "OT" },
                { name = "IMGOG", type = "OT" },
            }
        },
        ["ALKA1R"] = {
            name = "ALKA1R",
            runway = "RW33",
            waypoints = {
                { name = "ALKAN", type = "OT", altitude_min = 20000 },
                { name = "GETOV", type = "OT", speed = 250.0 },
                { name = "RESAR", type = "OT" },
                { name = "SILBI", type = "OT" },
                { name = "NORMU", type = "OT", speed = 250.0 },
                { name = "DATAL", type = "OT", speed = 250.0 },
                { name = "LABEX", type = "OT" },
                { name = "KUBAR", type = "OT" },
                { name = "OXAGO", type = "OT" },
                { name = "LUBAK", type = "OT" },
                { name = "BAYAN", type = "OT" },
                { name = "EGNUG", type = "OT", altitude_min = 8000, altitude_max = 9000 },
                { name = "MISOX", type = "OT", altitude_min = 6000 },
                { name = "SIDMU", type = "OB" },
                { name = "LOVAN", type = "OB" },
                { name = "MUXED", type = "OT", altitude_min = 4500, speed = 220.0 },
                { name = "MUXED", type = "OT", altitude_min = 4500, speed = 220.0 },
            }
        },
        ["ALKA1V"] = {
            name = "ALKA1V",
            runway = "RW33",
            waypoints = {
                { name = "ALKAN", type = "OT", altitude_min = 20000 },
                { name = "SENKI", type = "OT" },
                { name = "LUBAK", type = "OT" },
                { name = "BAYAN", type = "OT" },
                { name = "EGNUG", type = "OT", altitude_min = 8000, altitude_max = 9000 },
                { name = "MISOX", type = "OT", altitude_min = 6000 },
                { name = "SIDMU", type = "OB" },
                { name = "LOVAN", type = "OB" },
                { name = "MUXED", type = "OT", altitude_min = 4500, speed = 220.0 },
                { name = "MUXED", type = "OT", altitude_min = 4500, speed = 220.0 },
            }
        },
        ["HAYA1F"] = {
            name = "HAYA1F",
            runway = "RW15",
            waypoints = {
                { name = "HAYYA", type = "OT", altitude_min = 21000 },
                { name = "VELAM", type = "OT", altitude_min = 19000 },
                { name = "VUTAN", type = "OT", altitude_min = 18000 },
                { name = "TUDOM", type = "OT" },
                { name = "GETOV", type = "OT" },
                { name = "RESAR", type = "OT" },
                { name = "SILBI", type = "OT" },
                { name = "NORMU", type = "OT", speed = 250.0 },
                { name = "DATAL", type = "OT", speed = 250.0 },
                { name = "LABEX", type = "OT" },
                { name = "KUBAR", type = "OT" },
                { name = "OXAGO", type = "OT" },
                { name = "LUBAK", type = "OT" },
                { name = "BAYAN", type = "OT", altitude_min = 8000 },
                { name = "LOVET", type = "OT" },
                { name = "EGNUG", type = "OT" },
                { name = "KIPIK", type = "OT" },
                { name = "NOKTO", type = "OT" },
                { name = "LOSEN", type = "OT" },
                { name = "KATED", type = "OT", altitude_min = 3500, altitude_max = 4500, speed = 220.0 },
                { name = "KATED", type = "OT", speed = 220.0 },
            }
        },
        ["HAYA1H"] = {
            name = "HAYA1H",
            runway = "RW15",
            waypoints = {
                { name = "HAYYA", type = "OT", altitude_min = 21000 },
                { name = "VELAM", type = "OT", altitude_min = 19000 },
                { name = "VUTAN", type = "OT", altitude_min = 18000 },
                { name = "TUDOM", type = "OT", speed = 250.0 },
                { name = "LUBAK", type = "OT" },
                { name = "SIVET", type = "OT", altitude_max = 6000 },
                { name = "IMGOG", type = "OT", altitude_min = 4500, speed = 220.0 },
                { name = "IMGOG", type = "OT", altitude_min = 4500, speed = 220.0 },
            }
        },
        ["HAYA1L"] = {
            name = "HAYA1L",
            runway = "RW33",
            waypoints = {
                { name = "HAYYA", type = "OT", altitude_min = 21000 },
                { name = "VELAM", type = "OT", altitude_min = 19000 },
                { name = "VUTAN", type = "OT", altitude_min = 18000 },
                { name = "TUDOM", type = "OT" },
                { name = "GETOV", type = "OT" },
                { name = "RESAR", type = "OT" },
                { name = "SILBI", type = "OT" },
                { name = "NORMU", type = "OT", speed = 250.0 },
                { name = "DATAL", type = "OT", speed = 250.0 },
                { name = "LABEX", type = "OT" },
                { name = "KUBAR", type = "OT" },
                { name = "OXAGO", type = "OT" },
                { name = "LUBAK", type = "OT" },
                { name = "BAYAN", type = "OT" },
                { name = "KATED", type = "OT" },
                { name = "LOSEN", type = "OT", speed = 230.0 },
                { name = "KIPIK", type = "OT" },
                { name = "SOMAP", type = "OT" },
                { name = "PURIN", type = "OT" },
                { name = "DASIK", type = "OT", altitude_min = 3500, altitude_max = 4500, speed = 220.0 },
                { name = "DASIK", type = "OT", speed = 220.0 },
            }
        },
        ["HAYA1P"] = {
            name = "HAYA1P",
            runway = "RW15",
            waypoints = {
                { name = "HAYYA", type = "OT", altitude_min = 21000 },
                { name = "VELAM", type = "OT", altitude_min = 19000 },
                { name = "VUTAN", type = "OT", altitude_min = 18000 },
                { name = "TUDOM", type = "OT" },
                { name = "GETOV", type = "OT" },
                { name = "RESAR", type = "OT" },
                { name = "SILBI", type = "OT" },
                { name = "NORMU", type = "OT", speed = 250.0 },
                { name = "DATAL", type = "OT", speed = 250.0 },
                { name = "LABEX", type = "OT" },
                { name = "KUBAR", type = "OT" },
                { name = "OXAGO", type = "OT" },
                { name = "LUBAK", type = "OT" },
                { name = "BAYAN", type = "OT", altitude_min = 8000 },
                { name = "LOVET", type = "OT" },
                { name = "EGNUG", type = "OT" },
                { name = "NOLMA", type = "OT" },
                { name = "PUTAN", type = "OT" },
                { name = "IVANI", type = "OT", altitude_min = 4500, speed = 220.0 },
                { name = "IMGOG", type = "OT" },
                { name = "IMGOG", type = "OT" },
            }
        },
        ["HAYA1R"] = {
            name = "HAYA1R",
            runway = "RW33",
            waypoints = {
                { name = "HAYYA", type = "OT", altitude_min = 21000 },
                { name = "VELAM", type = "OT", altitude_min = 19000 },
                { name = "VUTAN", type = "OT", altitude_min = 18000 },
                { name = "TUDOM", type = "OT" },
                { name = "GETOV", type = "OT" },
                { name = "RESAR", type = "OT" },
                { name = "SILBI", type = "OT" },
                { name = "NORMU", type = "OT", speed = 250.0 },
                { name = "DATAL", type = "OT", speed = 250.0 },
                { name = "LABEX", type = "OT" },
                { name = "KUBAR", type = "OT" },
                { name = "OXAGO", type = "OT" },
                { name = "LUBAK", type = "OT" },
                { name = "BAYAN", type = "OT" },
                { name = "EGNUG", type = "OT", altitude_min = 8000, altitude_max = 9000 },
                { name = "MISOX", type = "OT", altitude_min = 6000 },
                { name = "SIDMU", type = "OB" },
                { name = "LOVAN", type = "OB" },
                { name = "MUXED", type = "OT", altitude_min = 4500, speed = 220.0 },
                { name = "MUXED", type = "OT", altitude_min = 4500, speed = 220.0 },
            }
        },
        ["HAYA1V"] = {
            name = "HAYA1V",
            runway = "RW33",
            waypoints = {
                { name = "HAYYA", type = "OT", altitude_min = 21000 },
                { name = "VELAM", type = "OT", altitude_min = 19000 },
                { name = "VUTAN", type = "OT", altitude_min = 18000 },
                { name = "LUBAK", type = "OT" },
                { name = "BAYAN", type = "OT" },
                { name = "EGNUG", type = "OT", altitude_min = 8000, altitude_max = 9000 },
                { name = "MISOX", type = "OT", altitude_min = 6000 },
                { name = "SIDMU", type = "OB" },
                { name = "LOVAN", type = "OB" },
                { name = "MUXED", type = "OT", altitude_min = 4500, speed = 220.0 },
                { name = "MUXED", type = "OT", altitude_min = 4500, speed = 220.0 },
            }
        },
        ["LAEB1F"] = {
            name = "LAEB1F",
            runway = "RW15",
            waypoints = {
                { name = "LAEEB", type = "OB", altitude_max = 15000 },
                { name = "EMEXA", type = "OT" },
                { name = "DASIK", type = "OT" },
                { name = "PURIN", type = "OT" },
                { name = "SOMAP", type = "OT" },
                { name = "KIPIK", type = "OT" },
                { name = "NOKTO", type = "OT" },
                { name = "LOSEN", type = "OT" },
                { name = "KATED", type = "OT", altitude_min = 3500, altitude_max = 4500, speed = 220.0 },
                { name = "KATED", type = "OT", speed = 220.0 },
            }
        },
        ["LAEB1J"] = {
            name = "LAEB1J",
            runway = "RW33",
            waypoints = {
                { name = "LAEEB", type = "OB" },
                { name = "GOKNI", type = "OT", altitude_min = 13000 },
                { name = "GINTO", type = "OT" },
                { name = "LAGNO", type = "OT" },
                { name = "KIPIK", type = "OT" },
                { name = "SOMAP", type = "OT" },
                { name = "PURIN", type = "OT" },
                { name = "DASIK", type = "OT", altitude_min = 3500, altitude_max = 4500, speed = 220.0 },
                { name = "DASIK", type = "OT", speed = 220.0 },
            }
        },
        ["LAEB1K"] = {
            name = "LAEB1K",
            runway = "RW15",
            waypoints = {
                { name = "LAEEB", type = "OB", altitude_max = 15000 },
                { name = "GOKNI", type = "OT" },
                { name = "GINTO", type = "OT" },
                { name = "LAGNO", type = "OT" },
                { name = "NADIG", type = "OT" },
                { name = "UKTON", type = "OT" },
                { name = "RUBOL", type = "OT" },
                { name = "DASIK", type = "OT" },
                { name = "PURIN", type = "OT" },
                { name = "SOMAP", type = "OT" },
                { name = "KIPIK", type = "OT" },
                { name = "NOKTO", type = "OT" },
                { name = "LOSEN", type = "OT" },
                { name = "KATED", type = "OT", altitude_min = 3500, altitude_max = 4500, speed = 220.0 },
                { name = "KATED", type = "OT", speed = 220.0 },
            }
        },
        ["LAEB1L"] = {
            name = "LAEB1L",
            runway = "RW33",
            waypoints = {
                { name = "LAEEB", type = "OB" },
                { name = "EMEXA", type = "OT" },
                { name = "MIVAL", type = "OT" },
                { name = "KUTER", type = "OT" },
                { name = "NONBA", type = "OT" },
                { name = "KINAP", type = "OT", speed = 220.0 },
                { name = "KIPIK", type = "OT" },
                { name = "SOMAP", type = "OT" },
                { name = "PURIN", type = "OT" },
                { name = "DASIK", type = "OT", altitude_min = 3500, altitude_max = 4500, speed = 220.0 },
                { name = "DASIK", type = "OT", speed = 220.0 },
            }
        },
        ["ORLE1F"] = {
            name = "ORLE1F",
            runway = "RW15",
            waypoints = {
                { name = "ORLEK", type = "OE", altitude_min = 21000 },
                { name = "GINTO", type = "OT" },
                { name = "LAGNO", type = "OT", altitude_min = 15000 },
                { name = "NADIG", type = "OT" },
                { name = "UKTON", type = "OT" },
                { name = "RUBOL", type = "OT" },
                { name = "DASIK", type = "OT" },
                { name = "PURIN", type = "OT" },
                { name = "SOMAP", type = "OT" },
                { name = "KIPIK", type = "OT" },
                { name = "NOKTO", type = "OT" },
                { name = "LOSEN", type = "OT" },
                { name = "KATED", type = "OT", altitude_min = 3500, altitude_max = 4500, speed = 220.0 },
                { name = "KATED", type = "OT", speed = 220.0 },
            }
        },
        ["ORLE1L"] = {
            name = "ORLE1L",
            runway = "RW33",
            waypoints = {
                { name = "ORLEK", type = "OE", altitude_min = 21000 },
                { name = "GINTO", type = "OT" },
                { name = "LAGNO", type = "OT" },
                { name = "KIPIK", type = "OT" },
                { name = "SOMAP", type = "OT" },
                { name = "PURIN", type = "OT" },
                { name = "DASIK", type = "OT", altitude_min = 3500, altitude_max = 4500, speed = 220.0 },
                { name = "DASIK", type = "OT", speed = 220.0 },
            }
        },
        ["TOSN1J"] = {
            name = "TOSN1J",
            runway = "RW33",
            waypoints = {
                { name = "TOSNA", type = "OM", altitude_min = 20000 },
                { name = "DATAL", type = "OT" },
                { name = "LABEX", type = "OT" },
                { name = "KUBAR", type = "OT" },
                { name = "OXAGO", type = "OT" },
                { name = "LUBAK", type = "OT" },
                { name = "BAYAN", type = "OT" },
                { name = "KATED", type = "OT" },
                { name = "LOSEN", type = "OT", speed = 230.0 },
                { name = "KIPIK", type = "OT" },
                { name = "SOMAP", type = "OT" },
                { name = "PURIN", type = "OT" },
                { name = "DASIK", type = "OT", altitude_min = 3500, altitude_max = 4500, speed = 220.0 },
                { name = "DASIK", type = "OT", speed = 220.0 },
            }
        },
        ["TOSN1P"] = {
            name = "TOSN1P",
            runway = "RW15",
            waypoints = {
                { name = "TOSNA", type = "OM", altitude_min = 20000 },
                { name = "KUVLA", type = "OB" },
                { name = "DINEX", type = "OB" },
                { name = "KIVAM", type = "OB", speed = 250.0 },
                { name = "UKOBA", type = "OB" },
                { name = "MUXED", type = "OT" },
                { name = "SIDMU", type = "OB", altitude_min = 8000 },
                { name = "EGNUG", type = "OT" },
                { name = "NOLMA", type = "OT" },
                { name = "PUTAN", type = "OT" },
                { name = "IVANI", type = "OT", altitude_min = 4500, speed = 220.0 },
                { name = "IMGOG", type = "OT" },
                { name = "IMGOG", type = "OT" },
            }
        },
        ["TOSN1R"] = {
            name = "TOSN1R",
            runway = "RW33",
            waypoints = {
                { name = "TOSNA", type = "OM", altitude_min = 20000 },
                { name = "KUVLA", type = "OB" },
                { name = "DINEX", type = "OB", speed = 250.0 },
                { name = "KIVAM", type = "OB", speed = 250.0 },
                { name = "AFNAN", type = "OT", altitude_min = 11000 },
                { name = "EMALO", type = "OT" },
                { name = "MUTLI", type = "OT" },
                { name = "LOVET", type = "OT" },
                { name = "EGNUG", type = "OT" },
                { name = "MISOX", type = "OT", altitude_min = 6000 },
                { name = "SIDMU", type = "OB" },
                { name = "LOVAN", type = "OB" },
                { name = "MUXED", type = "OT", altitude_min = 4500, speed = 220.0 },
                { name = "MUXED", type = "OT", altitude_min = 4500, speed = 220.0 },
            }
        },
        ["TOSN1T"] = {
            name = "TOSN1T",
            runway = "RW15",
            waypoints = {
                { name = "TOSNA", type = "OM", altitude_min = 20000 },
                { name = "DATAL", type = "OT" },
                { name = "LABEX", type = "OT" },
                { name = "KUBAR", type = "OT" },
                { name = "OXAGO", type = "OT" },
                { name = "LUBAK", type = "OT" },
                { name = "BAYAN", type = "OT", altitude_min = 8000 },
                { name = "LOVET", type = "OT" },
                { name = "EGNUG", type = "OT" },
                { name = "NOLMA", type = "OT" },
                { name = "PUTAN", type = "OT" },
                { name = "IVANI", type = "OT", altitude_min = 4500, speed = 220.0 },
                { name = "IMGOG", type = "OT" },
                { name = "IMGOG", type = "OT" },
            }
        },
        ["TOSN1V"] = {
            name = "TOSN1V",
            runway = "RW33",
            waypoints = {
                { name = "TOSNA", type = "OM", altitude_min = 20000 },
                { name = "DATAL", type = "OT" },
                { name = "LABEX", type = "OT" },
                { name = "KUBAR", type = "OT" },
                { name = "OXAGO", type = "OT" },
                { name = "LUBAK", type = "OT" },
                { name = "BAYAN", type = "OT" },
                { name = "EGNUG", type = "OT", altitude_min = 8000, altitude_max = 9000 },
                { name = "MISOX", type = "OT", altitude_min = 6000 },
                { name = "SIDMU", type = "OB" },
                { name = "LOVAN", type = "OB" },
                { name = "MUXED", type = "OT", altitude_min = 4500, speed = 220.0 },
                { name = "MUXED", type = "OT", altitude_min = 4500, speed = 220.0 },
            }
        },
        ["TOSN2F"] = {
            name = "TOSN2F",
            runway = "RW15",
            waypoints = {
                { name = "TOSNA", type = "OM", altitude_min = 20000 },
                { name = "KUVLA", type = "OB" },
                { name = "DINEX", type = "OB" },
                { name = "KIVAM", type = "OB" },
                { name = "IMTAL", type = "OB" },
                { name = "KIPEM", type = "OB", altitude_min = 11000, altitude_max = 12000 },
                { name = "EMEXA", type = "OT" },
                { name = "DASIK", type = "OT" },
                { name = "PURIN", type = "OT" },
                { name = "SOMAP", type = "OT" },
                { name = "KIPIK", type = "OT" },
                { name = "NOKTO", type = "OT" },
                { name = "LOSEN", type = "OT" },
                { name = "KATED", type = "OT", altitude_min = 3500, altitude_max = 4500, speed = 220.0 },
                { name = "KATED", type = "OT", speed = 220.0 },
            }
        },
        ["TOSN2L"] = {
            name = "TOSN2L",
            runway = "RW33",
            waypoints = {
                { name = "TOSNA", type = "OM", altitude_min = 20000 },
                { name = "KUVLA", type = "OB" },
                { name = "DINEX", type = "OB" },
                { name = "KIVAM", type = "OB" },
                { name = "IMTAL", type = "OB" },
                { name = "KIPEM", type = "OB", altitude_min = 11000, altitude_max = 12000 },
                { name = "EMEXA", type = "OT" },
                { name = "MIVAL", type = "OT" },
                { name = "KUTER", type = "OT" },
                { name = "NONBA", type = "OT" },
                { name = "KINAP", type = "OT", speed = 220.0 },
                { name = "KIPIK", type = "OT" },
                { name = "SOMAP", type = "OT" },
                { name = "PURIN", type = "OT" },
                { name = "DASIK", type = "OT", altitude_min = 3500, altitude_max = 4500, speed = 220.0 },
                { name = "DASIK", type = "OT", speed = 220.0 },
            }
        },
        ["TOVO1P"] = {
            name = "TOVO1P",
            runway = "RW15",
            waypoints = {
                { name = "TOVOX", type = "OB" },
                { name = "DINEX", type = "OB" },
                { name = "KIVAM", type = "OB" },
                { name = "UKOBA", type = "OB" },
                { name = "MUXED", type = "OT" },
                { name = "SIDMU", type = "OB", altitude_min = 8000 },
                { name = "EGNUG", type = "OT" },
                { name = "NOLMA", type = "OT" },
                { name = "PUTAN", type = "OT" },
                { name = "IVANI", type = "OT", altitude_min = 4500, speed = 220.0 },
                { name = "IMGOG", type = "OT" },
                { name = "IMGOG", type = "OT" },
            }
        },
        ["TOVO1R"] = {
            name = "TOVO1R",
            runway = "RW33",
            waypoints = {
                { name = "TOVOX", type = "OB" },
                { name = "DINEX", type = "OB" },
                { name = "KIVAM", type = "OB", speed = 250.0 },
                { name = "AFNAN", type = "OT", altitude_min = 11000 },
                { name = "EMALO", type = "OT" },
                { name = "MUTLI", type = "OT" },
                { name = "LOVET", type = "OT" },
                { name = "EGNUG", type = "OT" },
                { name = "MISOX", type = "OT", altitude_min = 6000 },
                { name = "SIDMU", type = "OB" },
                { name = "LOVAN", type = "OB" },
                { name = "MUXED", type = "OT", altitude_min = 4500, speed = 220.0 },
                { name = "MUXED", type = "OT", altitude_min = 4500, speed = 220.0 },
            }
        },
        ["TOVO2F"] = {
            name = "TOVO2F",
            runway = "RW15",
            waypoints = {
                { name = "TOVOX", type = "OB" },
                { name = "DINEX", type = "OB" },
                { name = "KIVAM", type = "OB" },
                { name = "IMTAL", type = "OB" },
                { name = "KIPEM", type = "OB", altitude_min = 11000, altitude_max = 12000 },
                { name = "EMEXA", type = "OT" },
                { name = "DASIK", type = "OT" },
                { name = "PURIN", type = "OT" },
                { name = "SOMAP", type = "OT" },
                { name = "KIPIK", type = "OT" },
                { name = "NOKTO", type = "OT" },
                { name = "LOSEN", type = "OT" },
                { name = "KATED", type = "OT", altitude_min = 3500, altitude_max = 4500, speed = 220.0 },
                { name = "KATED", type = "OT", speed = 220.0 },
            }
        },
        ["TOVO2L"] = {
            name = "TOVO2L",
            runway = "RW33",
            waypoints = {
                { name = "TOVOX", type = "OB" },
                { name = "DINEX", type = "OB" },
                { name = "KIVAM", type = "OB" },
                { name = "IMTAL", type = "OB" },
                { name = "KIPEM", type = "OB", altitude_min = 11000, altitude_max = 12000 },
                { name = "EMEXA", type = "OT" },
                { name = "MIVAL", type = "OT" },
                { name = "KUTER", type = "OT" },
                { name = "NONBA", type = "OT" },
                { name = "KINAP", type = "OT", speed = 220.0 },
                { name = "KIPIK", type = "OT" },
                { name = "SOMAP", type = "OT" },
                { name = "PURIN", type = "OT" },
                { name = "DASIK", type = "OT", altitude_min = 3500, altitude_max = 4500, speed = 220.0 },
                { name = "DASIK", type = "OT", speed = 220.0 },
            }
        },
        ["VEDE1F"] = {
            name = "VEDE1F",
            runway = "RW15",
            waypoints = {
                { name = "VEDED", type = "OT" },
                { name = "VELAM", type = "OT", speed = 250.0 },
                { name = "VUTAN", type = "OT", altitude_min = 18000 },
                { name = "TUDOM", type = "OT" },
                { name = "GETOV", type = "OT" },
                { name = "RESAR", type = "OT" },
                { name = "SILBI", type = "OT" },
                { name = "NORMU", type = "OT", speed = 250.0 },
                { name = "DATAL", type = "OT", speed = 250.0 },
                { name = "LABEX", type = "OT" },
                { name = "KUBAR", type = "OT" },
                { name = "OXAGO", type = "OT" },
                { name = "LUBAK", type = "OT" },
                { name = "BAYAN", type = "OT", altitude_min = 8000 },
                { name = "LOVET", type = "OT" },
                { name = "EGNUG", type = "OT" },
                { name = "KIPIK", type = "OT" },
                { name = "NOKTO", type = "OT" },
                { name = "LOSEN", type = "OT" },
                { name = "KATED", type = "OT", altitude_min = 3500, altitude_max = 4500, speed = 220.0 },
                { name = "KATED", type = "OT", speed = 220.0 },
            }
        },
        ["VEDE1H"] = {
            name = "VEDE1H",
            runway = "RW15",
            waypoints = {
                { name = "VEDED", type = "OT" },
                { name = "VELAM", type = "OT", speed = 250.0 },
                { name = "VUTAN", type = "OT", altitude_min = 18000 },
                { name = "TUDOM", type = "OT", speed = 250.0 },
                { name = "LUBAK", type = "OT" },
                { name = "SIVET", type = "OT", altitude_max = 6000 },
                { name = "IMGOG", type = "OT", altitude_min = 4500, speed = 220.0 },
                { name = "IMGOG", type = "OT", altitude_min = 4500, speed = 220.0 },
            }
        },
        ["VEDE1L"] = {
            name = "VEDE1L",
            runway = "RW33",
            waypoints = {
                { name = "VEDED", type = "OT" },
                { name = "VELAM", type = "OT", speed = 250.0 },
                { name = "VUTAN", type = "OT", altitude_min = 18000 },
                { name = "TUDOM", type = "OT" },
                { name = "GETOV", type = "OT" },
                { name = "RESAR", type = "OT" },
                { name = "SILBI", type = "OT" },
                { name = "NORMU", type = "OT", speed = 250.0 },
                { name = "DATAL", type = "OT", speed = 250.0 },
                { name = "LABEX", type = "OT" },
                { name = "KUBAR", type = "OT" },
                { name = "OXAGO", type = "OT" },
                { name = "LUBAK", type = "OT" },
                { name = "BAYAN", type = "OT" },
                { name = "KATED", type = "OT" },
                { name = "LOSEN", type = "OT", speed = 230.0 },
                { name = "KIPIK", type = "OT" },
                { name = "SOMAP", type = "OT" },
                { name = "PURIN", type = "OT" },
                { name = "DASIK", type = "OT", altitude_min = 3500, altitude_max = 4500, speed = 220.0 },
                { name = "DASIK", type = "OT", speed = 220.0 },
            }
        },
        ["VEDE1P"] = {
            name = "VEDE1P",
            runway = "RW15",
            waypoints = {
                { name = "VEDED", type = "OT" },
                { name = "VELAM", type = "OT", speed = 250.0 },
                { name = "VUTAN", type = "OT", altitude_min = 18000 },
                { name = "TUDOM", type = "OT" },
                { name = "GETOV", type = "OT" },
                { name = "RESAR", type = "OT" },
                { name = "SILBI", type = "OT" },
                { name = "NORMU", type = "OT", speed = 250.0 },
                { name = "DATAL", type = "OT", speed = 250.0 },
                { name = "LABEX", type = "OT" },
                { name = "KUBAR", type = "OT" },
                { name = "OXAGO", type = "OT" },
                { name = "LUBAK", type = "OT" },
                { name = "BAYAN", type = "OT", altitude_min = 8000 },
                { name = "LOVET", type = "OT" },
                { name = "EGNUG", type = "OT" },
                { name = "NOLMA", type = "OT" },
                { name = "PUTAN", type = "OT" },
                { name = "IVANI", type = "OT", altitude_min = 4500, speed = 220.0 },
                { name = "IMGOG", type = "OT" },
                { name = "IMGOG", type = "OT" },
            }
        },
        ["VEDE1R"] = {
            name = "VEDE1R",
            runway = "RW33",
            waypoints = {
                { name = "VEDED", type = "OT" },
                { name = "VELAM", type = "OT", speed = 250.0 },
                { name = "VUTAN", type = "OT", altitude_min = 18000 },
                { name = "TUDOM", type = "OT" },
                { name = "GETOV", type = "OT" },
                { name = "RESAR", type = "OT" },
                { name = "SILBI", type = "OT" },
                { name = "NORMU", type = "OT", speed = 250.0 },
                { name = "DATAL", type = "OT", speed = 250.0 },
                { name = "LABEX", type = "OT" },
                { name = "KUBAR", type = "OT" },
                { name = "OXAGO", type = "OT" },
                { name = "LUBAK", type = "OT" },
                { name = "BAYAN", type = "OT" },
                { name = "EGNUG", type = "OT", altitude_min = 8000, altitude_max = 9000 },
                { name = "MISOX", type = "OT", altitude_min = 6000 },
                { name = "SIDMU", type = "OB" },
                { name = "LOVAN", type = "OB" },
                { name = "MUXED", type = "OT", altitude_min = 4500, speed = 220.0 },
                { name = "MUXED", type = "OT", altitude_min = 4500, speed = 220.0 },
            }
        },
        ["VEDE1V"] = {
            name = "VEDE1V",
            runway = "RW33",
            waypoints = {
                { name = "VEDED", type = "OT" },
                { name = "VELAM", type = "OT", speed = 250.0 },
                { name = "VUTAN", type = "OT", altitude_min = 18000 },
                { name = "LUBAK", type = "OT" },
                { name = "BAYAN", type = "OT" },
                { name = "EGNUG", type = "OT", altitude_min = 8000, altitude_max = 9000 },
                { name = "MISOX", type = "OT", altitude_min = 6000 },
                { name = "SIDMU", type = "OB" },
                { name = "LOVAN", type = "OB" },
                { name = "MUXED", type = "OT", altitude_min = 4500, speed = 220.0 },
                { name = "MUXED", type = "OT", altitude_min = 4500, speed = 220.0 },
            }
        },
    },

    -- Процедуры захода на посадку
    APPROACH = {
        ["I15"] = {
            name = "I15",
            type = "A",
            runway = "I15",
            waypoints = {
                { name = "MAXMO", transition = "MAXMO", type = "OT", altitude_min = 4500 },
                { name = "SOBOM", transition = "MAXMO", type = "OT", altitude_min = 4500 },
                { name = "LUGAM", transition = "MAXMO", type = "OT", altitude_min = 3500 },
                { name = "LUGAM", transition = "", type = "OT" },
                { name = "BD411", transition = "", type = "OT" },
                { name = "RW15", transition = "", type = "OT" },
                { name = "D155B", transition = "", type = "OT" },
                { name = "", transition = "", type = "", speed = 200.0 },
                { name = "BD412", transition = "", type = "OT" },
            }
        },
        ["I33"] = {
            name = "I33",
            type = "A",
            runway = "I33",
            waypoints = {
                { name = "NAJMA", transition = "NAJMA", type = "OT", altitude_min = 4500 },
                { name = "RAMPO", transition = "NAJMA", type = "OB", altitude_min = 3500 },
                { name = "RAMPO", transition = "", type = "OB" },
                { name = "BD711", transition = "", type = "OT" },
                { name = "RW33", transition = "", type = "OT" },
                { name = "D335F", transition = "", type = "OT", altitude_min = 1500 },
                { name = "", transition = "", type = "" },
                { name = "D295D", transition = "", type = "OT" },
                { name = "", transition = "", type = "" },
                { name = "BD712", transition = "", type = "OT", speed = 210.0 },
            }
        },
        ["R15"] = {
            name = "R15",
            type = "R",
            runway = "R15",
            waypoints = {
                { name = "MAXMO", transition = "", type = "OT", altitude_min = 3000 },
                { name = "BD401", transition = "", type = "OT", altitude_min = 3000 },
                { name = "RW15", transition = "", type = "OT" },
                { name = "", transition = "", type = "" },
                { name = "DEKMI", transition = "", type = "OT", speed = 230.0 },
                { name = "BUBOG", transition = "", type = "OT", speed = 230.0 },
                { name = "REVAT", transition = "", type = "OT", speed = 230.0 },
                { name = "REVAT", transition = "", type = "OT", speed = 230.0 },
            }
        },
        ["R33"] = {
            name = "R33",
            type = "R",
            runway = "R33",
            waypoints = {
                { name = "NAJMA", transition = "", type = "OT", altitude_min = 3000 },
                { name = "BD701", transition = "", type = "OT", altitude_min = 3000 },
                { name = "BD702", transition = "", type = "OT" },
                { name = "SILDA", transition = "", type = "OT", altitude_min = 2500, speed = 210.0 },
                { name = "GITNI", transition = "", type = "OT", speed = 210.0 },
                { name = "IVIKA", transition = "", type = "OT", speed = 210.0 },
                { name = "ELILO", transition = "", type = "OT", speed = 230.0 },
                { name = "ELILO", transition = "", type = "OT", speed = 230.0 },
            }
        },
    },

    -- Частоты
    Frequencies = {
        TOWER = 118.0,
        APPROACH = 121.0,
        DEPARTURE = 125.0,
        GROUND = 121.7,
        ATIS = 126.0,
    }
}

return AirportData
